### ISSUE TITLE
Incompatibility with numpy versions >= 1.24

### ISSUE THREAD

**Issue by joalof** [SheffieldML/GPy#1004]
Hi, thanks for making this excellent software. I've recently noticed that in numpy 1.24 the deprecation of aliases like np.bool, np.str, etc has [expired](https://numpy.org/doc/stable/release/1.24.0-notes.html). These aliases are still in use in both GPy and paramz and will now result in a crash. This could be fixed either by substitution with the native python types or by enforcing a maximum numpy version <=1.23.5 in the setup.py (right now,  GPy installed in, e.g., a fresh venv will crash), but this option is maybe less appealing.

**Comment by AngelBerihuete** [comment]
Hi @joalof ! Yes, same problem here when GPy tries to use ```np.int``` within ```gp_plots.py```. I have versions 3.10.9 (python) and 1.24.2 (numpy). Do you have any solution to use GPy plots?

```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 17
     14 q1, q2 = m.predict_quantiles(newX)
     16 fig, ax = plt.subplots()
---> 17 m.plot(ax=ax, plot_data=False)
     18 ax.scatter(Xgrid, mu, c="b")
     19 ax.scatter(newX, mu1, marker=".", c="r")

File ~/.local/lib/python3.10/site-packages/GPy/plotting/gpy_plot/gp_plots.py:334, in plot(self, plot_limits, fixed_inputs, resolut
ion, plot_raw, apply_link, which_data_ycols, which_data_rows, visible_dims, levels, samples, samples_likelihood, lower, upper, plo
t_data, plot_inducing, plot_density, predict_kw, projection, legend, **kwargs)
    331     kwargs['ylim'] = (xmin[1], xmax[1])
    333 canvas, _ = pl().new_canvas(projection=projection, **kwargs)
--> 334 helper_prediction = helper_predict_with_model(self, helper_data[2], plot_raw,
    335                                       apply_link, np.linspace(2.5, 97.5, levels*2) if plot_density else (lower,upper),
    336                                       get_which_data_ycols(self, which_data_ycols),
    337                                       predict_kw, samples)
    338 if plot_raw and not apply_link:
    339     # It does not make sense to plot the data (which lives not in the latent function space) into latent function space.
    340     plot_data = False

File ~/.local/lib/python3.10/site-packages/GPy/plotting/gpy_plot/plot_util.py:75, in helper_predict_with_model(self, Xgrid, plot_r
aw, apply_link, percentiles, which_data_ycols, predict_kw, samples)
     73     predict_kw['Y_metadata'] = {}
     74 if 'output_index' not in predict_kw['Y_metadata']:
---> 75     predict_kw['Y_metadata']['output_index'] = Xgrid[:,-1:].astype(np.int)
     77 mu, _ = self.predict(Xgrid, **predict_kw)
     79 if percentiles is not None:

File ~/.local/lib/python3.10/site-packages/numpy/__init__.py:305, in __getattr__(attr)
    300     warnings.warn(
    301         f"In the future `np.{attr}` will be defined as the "
    302         "corresponding NumPy scalar.", FutureWarning, stacklevel=2)
    304 if attr in __former_attrs__:
--> 305     raise AttributeError(__former_attrs__[attr])
    307 # Importing Tester requires importing all of UnitTest which is not a
    308 # cheap import Since it is mainly used in test suits, we lazy import it
    309 # here to save on the order of 10 ms of import time for most users
    310 #
    311 # The previous way Tester was imported also had a side effect of adding
    312 # the full `numpy.testing` namespace
    313 if attr == 'testing':

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will 
not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the pre
cision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will 
not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the pre
cision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

```

**Comment by joaquinvanschoren** [comment]
+1 :)

**Comment by joalof** [comment]
@AngelBerihuete Until this is fixed the easiest solution is to just use numpy version <=1.23.5.

**Comment by AngelBerihuete** [comment]
> 

Done. I've downgraded numpy and GPy works again.

**Comment by milicasan** [comment]
Hi GPy team, any chance you can fix the inconsistency with numpy soon? Many thanks!

**Comment by oscarbranson** [comment]
Or at least add a version restriction to numpy in `setup.py`?

**Comment by MartinBubel** [comment]
This should be fixed now. However, we are a bit behind when it comes to linux wheels and keeping up with the changelog.

Since we are sorting out which issue to fix by the next release, could you please check if the issue persists after updating to the latest `GPy` release?

**Comment by joalof** [comment]
*Edited since I spoke too soon 

Thanks for the update! Using GPy 1.12 (note: only available from the github repo since there is no wheel/source distribution on pypi atm) some incompatibilities related to deprecated type aliases do still remain, for instance:
https://github.com/SheffieldML/GPy/blob/279f8e83f13c363c86b456862fd388df34671df2/GPy/kern/src/coregionalize.py#L75

For numpy >= 1.25 there is an additional issue due to the import of the [deprecated](https://github.com/numpy/numpy/pull/23041) `numpy.testing.Tester` in:
https://github.com/SheffieldML/GPy/blob/279f8e83f13c363c86b456862fd388df34671df2/GPy/__init__.py#L32

**Comment by MartinBubel** [comment]
thanks for checking. I will address this via #1025 and #1030 .

**Comment by MartinBubel** [comment]
Hi @joalof 

we adressed this in #1040 .
Though, there is no new release yet, but there are only few issues remaining on our board towards a hotfix.

In the meantime, you can use `GPy` via git dependency on the `devel` branch. It also uses an updated fork of `paramz` as it seems like `paramz` is no longer maintained.

I will close your issue for the sake of overview on our issue board. Feel free to reopen if you encounter any issues according to this issue when working with the `devel` branch or any of the upcoming releases.

Best regards

Martin
