### ISSUE TITLE
Fix for python3.11?

### ISSUE THREAD

**Issue by ego-thales** [SheffieldML/GPy#1018]
Is any release for python3.11 planned?

It is currently no possible to directly install this package under python3.11, and even from sources without diving into the code.
The big package [scikit-fda](https://github.com/GAA-UAM/scikit-fda) depends on it, and so accnot be installed on python3.11 :(

Thank you in advance.

**Comment by ekalosak** [comment]
https://github.com/SheffieldML/GPy/pull/1020 fixes, closing. As the fix is merged, it'll be part of 1.13.0 when released. Please re-open the issue if you run into the problem again after the release.

**Comment by ego-thales** [comment]
Thanks!
Tested installation from latest `devel` rev, it works fine for me :)
