### ISSUE TITLE
Missing GPy 1.12.0 wheels for linux

### ISSUE THREAD

**Issue by harahu** [SheffieldML/GPy#1021]
First of all, I really like this project; thank you for the work you are doing.

I am trying to install `GPy 1.12.0` on my linux box using poetry/pip. This fails because the 1.12.0 release on pypi only consists of prebuilt wheels for Windows, with neither a source tarball, nor wheels for Linux (and MacOS for that matter) having been published.

It would be lovely if you could expand the scope of this release. Thanks in advance!

Tagging you, @zhenwendai, since it seems you did the initial 1.12.0 release.

**Comment by Quentin62** [comment]
Same problem.

I install it through the github repo:

```bash
poetry add git+https://github.com/SheffieldML/GPy.git@devel
```

**Comment by spaceandtrade** [comment]
I'm experiencing something that could be related.
Poetry: 
> Unable to find installation candidates for gpy (1.12.0)

PIP: 
> ERROR: Could not find a version that satisfies the requirement 1.12.0 (from versions: none)
> ERROR: No matching distribution found for 1.12.0

1.11.0 also does not install. 1.10.0 does. Experiencing this from a WSL docker container and experienced the same on Mac.

**Comment by 86mm86** [comment]
I have experienced a similar problem as the ones mentioned above. GPy 1.12.0 can be installed on Windows but not on Mac OS. Any plan to release wheels also for Unix? Thank you!

**Comment by MartinBubel** [comment]
We are working on new release soon. I don't know why there are no linux builds for the latest releases but I will take a look at it. Consider the next release to provide linux builds again.

**Comment by MartinBubel** [comment]
Linux and MacOS build Jobs have been added as off #1053 
Also wheel Files will Cover Python 3.9 to 3.12
Wheel Files will be available soon, maybe still this year.
