### ISSUE TITLE
MAINTAINER RESPONSIBILITY

### ISSUE THREAD

**Issue by MartinBubel** [SheffieldML/GPy#1026]
I see many PRs that are stuck in the final stages as there is nobody available that gives final comments or merges a PR.
Until we haven't found some brave developer(s) with write access / or new ones are announced, I am afraid that there aren't going to see many fixes anytime soon.

**Comment by ekalosak** [comment]
@MartinBubel good call out. Could you help prioritize some of them? i.e. what's on your must-have list?

**Comment by ekalosak** [comment]
Also @lawrennd why not add Martin to maintainer list?

**Comment by lawrennd** [comment]
Great idea, @MartinBubel are you happy to take a lead on some of this?

**Comment by MartinBubel** [comment]
> Great idea, @MartinBubel are you happy to take a lead on some of this?

Thanks for inviting me. I will try to help out on some of them.

**Comment by MartinBubel** [comment]
> @MartinBubel good call out. Could you help prioritize some of them? i.e. what's on your must-have list?

I haven't found the time yet to look at all of them. But I can do so over the next days. I would suggest to focus solely on stability for now, which mainly means "compatibility with new python versions". Anything else comes later IMHO.

**Comment by ekalosak** [comment]
Yep, let's get right before we move forward, agreed. Welcome aboard.
Should we consider this issue closed vis https://github.com/SheffieldML/GPy/pull/1020 being merged?
