### ISSUE TITLE
How do I suppress printing/logging

### ISSUE THREAD

**Issue by jsgordon999** [SheffieldML/GPy#1027]
Hi, using version 1.10.0 . How do I modify the source code to suppress the printing of the statements 
"[GP] initializing inference method
[GP] adding kernel and likelihood as parameters
[GP] initializing Y"
which appear somewhere in the calling of the GPy.kern.RBF() and GPy.models.GPRegression() functions. Neither redirecting sys.stdout or using the logging module to try and disable GPy logging have worked for me.
Thanks.

**Comment by ekalosak** [comment]
GPy logging uses the stdlib Python logger, see for example: https://github.com/SheffieldML/GPy/blob/devel/GPy/core/gp.py#L14-L16

Moreover, it uses a _named_ logger, which lets you get and modify GPy's logging. Here's what ChatGPT says:

"""Prompt:
python logging quiet a named logger
"""

"""ChatGPT

To quiet a named logger in Python, you can set its logging level to a higher level, such as WARNING, ERROR, or CRITICAL, which will effectively suppress less severe log messages. Here's how you can do it using the Python logging module:

```py
import logging

# Create a named logger
logger = logging.getLogger("my_logger")

# Set the logging level to suppress less severe log messages
logger.setLevel(logging.WARNING)  # You can use other levels like logging.ERROR or logging.CRITICAL

# Example log messages
logger.debug("This message won't be displayed")
logger.info("This message won't be displayed")
logger.warning("This message will be displayed")
logger.error("This message will be displayed")
logger.critical("This message will be displayed")
```

In this example, the logger named "my_logger" is configured to only display log messages with a severity level of WARNING or higher. As a result, debug and info messages won't be displayed, but warning, error, and critical messages will be displayed.

You can adjust the logging level to suit your needs depending on how much detail you want in your log output.
"""


So you just need to get the logger named "GP" and set its level. You can use this approach on any project that uses the stdlib logger.

**Comment by jsgordon999** [comment]
I see, it was called "GP" not "GPy", thanks!
