### ISSUE TITLE
Let's drop support for all Python < 3.7?

### ISSUE THREAD

**Issue by ekalosak** [SheffieldML/GPy#1028]
It's a big maintenance burden.

**Comment by lawrennd** [comment]
I agree with this, it should make code simpler moving forward and reduce technical debt. Thoughts from others?

**Comment by MartinBubel** [comment]
Absolutely. I would even drop support for python == 3.7, as it reached end of support, officially. However, there might still be many people using it so dropping support for python 3.7 might be a bit too hard yet. On the other side, I see furhter maintenance coming soon when more and more dependencies start dropping support for python 3.7. It can, and in fact is, causing conflicts if modern numpy or matplotlib versions are desired by users, which have dropped support for python 3.7 quite a while ago. So it might be helpful to orientate on what our dependencies do about this?

What do you think?

**Comment by ekalosak** [comment]
I'm in favor of supporting only those versions supported by numpy.

As for matplotlib, that should be an optional dependency here IMHO. This is perhaps out of scope though.

Returning to the issue at hand:
- Dropping support for Python <= 3.7 will require updating the docs and CI. Beyond that, I don't foresee code changes.
- We aught to be a little slow to execute this change so there is time for maintainer, contributor, and user feedback. We don't need to wait to put the changes in a PR, of course, but maybe it's best to plan this depreciation for 1.14 rather than the next 1.13 release. If we don't drop the ball then 1.14 would be end of calendar year.

Thoughts on scope, timing, and waiting for input?

**Comment by MartinBubel** [comment]
develop addresses this now
