### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by MartinBubel** [SheffieldML/GPy#1035]
devel branch is at 1.12 but tags/releases are at 1.10 and changelog.md is at 1.9.8

I propose that we move directly to 1.13 where we provide fixes for anything that is urgend for others to use this project.

Anything that is not urgent will be another patch/minor or even major.

**Comment by MartinBubel** [comment]
I also created milestones for sorting issues as its getting a bit difficult to keep an overview.

**Comment by lawrennd** [comment]
Sounds good to me, thanks so much for pushing this forward Martin.
