### ISSUE TITLE
Installation fails when pip installing into conda environment

### ISSUE THREAD

**Issue by AndrewFalkowski** [SheffieldML/GPy#1042]
Attempting to pip install into a conda environment with python 3.10.12 produces a build error:
```terminal
  Building wheel for GPy (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
  
  ...
  
  /Users/.../miniconda3/envs/GPy_env/lib/python3.10/site-packages/setuptools/dist.py:745: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'upload-dir' will not be supported in future
              versions. Please use the underscore name 'upload_dir' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /Users/.../miniconda3/envs/GPy_env/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.

...

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for GPy
Failed to build GPy
ERROR: Could not build wheels for GPy, which is required to install pyproject.toml-based projects
```

However, I am able to pip install and successfully build within a Google Colab environment running the same python version without issue. Is this a result of using a conda environment or are ARM chips not supported by GPy?

**Comment by MartinBubel** [comment]
Hi @AndrewFalkowski 
you are rising an interesting question regarding the ARM support. Honestly, I can't tell right now. I probably will have to do some tests myself and see.
Will keep you updated.

**Comment by MartinBubel** [comment]
Seems like this is due to the fact, that there are no linux builds available to date.

@AndrewFalkowski I assume you are using Mac?

I will add linux builds to the CI as off the next release. This will be adressed in #1021 . I will close this issue for the sake of better overview on our issue board.

Feel free to reopen if the issue persists after the next release (should be available before the end of the year).
