### ISSUE TITLE
GPy is not compatible with numpy 1.26.2

### ISSUE THREAD

**Issue by wangcj05** [SheffieldML/GPy#1049]
Got the following error: 

```
$ python caus_id_GP.py
Traceback (most recent call last):
  File "/Users/wangc/projects/LDRD_causal/identifying_causal_structure/caus_id_GP.py", line 4, in <module>
    import GPy
  File "/Users/wangc/miniconda3/envs/causal_libs/lib/python3.10/site-packages/GPy/__init__.py", line 32, in <module>
    from numpy.testing import Tester
ImportError: cannot import name 'Tester' from 'numpy.testing' (/Users/wangc/miniconda3/envs/causal_libs/lib/python3.10/site-packages/numpy/testing/__init__.py)
```

**Comment by MartinBubel** [comment]
Hi @wangcj05 
this is already fixed in the `develop` branch but not yet released. This is no promise but there will be a patch on this (and other compatibility issues) by the new year.
A potential workaround for now: you may use `GPy` as a git-dependency.

**Comment by MartinBubel** [comment]
I will close the issue here as it is adressed. Feel free to reopen if the issue persists or you cannot apply the proposed workaround.

Best regards
Martin
