### ISSUE TITLE
Provide Sensible Inititalization if kern isn't provided

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#105]
For GP model constructions, if the user doesn't provide a covariance, we should do some sensible heuristic initialization of the covariance function.

**Comment by mzwiessele** [comment]
Any updates/news on that? Can someone think of other initialisations? Or has empirical ways of initialising?

How are you guys initialising your GPs?

**Comment by mzwiessele** [comment]
Will close this issue with milestone GPy 0.8.10 if no one cares.
