### ISSUE TITLE
Issue building GPy-1.10.0.tar.gz offline

### ISSUE THREAD

**Issue by rameezdev** [SheffieldML/GPy#1052]
Problem:
I am encountering difficulties while trying to build GPy-1.10.0.tar.gz without an internet connection. The process is not working as expected. I have all the required whl files already in the same folder.

Details:

Environment: Python 3.10, Windows 11, VS Studio C++ build tool installed
Error Messages: 

![image](https://github.com/SheffieldML/GPy/assets/88757321/0a9f07e1-99dd-40e7-bab0-04d97860de58)

**Comment by MartinBubel** [comment]
Hi @rameezdev 
I cannot read anything on the image and also cannot open or download it. Could you please copy-paste your error message?

Also, I am not sure what your issue is about? Please describe in more detail what you are trying to do, what you are expecting, and what error you are getting.

**Comment by rameezdev** [comment]
I'm trying to install GPy-1.10.0 in a closed network i.e. without internet connectivity.
I already downloaded all the required whl/tar files in the folder.  
Is it possible to install without internet connectivity?

**Comment by rameezdev** [comment]
> Hi @rameezdev I cannot read anything on the image and also cannot open or download it. Could you please copy-paste your error message?
> 
> Also, I am not sure what your issue is about? Please describe in more detail what you are trying to do, what you are expecting, and what error you are getting.

 I'm trying to install GPy-1.10.0 in a closed network i.e. without internet connectivity. I already downloaded all the required whl/tar files in the folder. Is it possible to install GPy using python 3.10 without internet connectivity?

**Comment by MartinBubel** [comment]
`GPy` has dependencies, e.g. `numpy`, and we don't pack them into the tar file. This makes sense as `GPy` is compatible with many different versions of its dependencies and thus, shipping the dependencies with it does not make sense ihmo.

I suggest you check the setup.py file for its dependencies and make sure you have them installed in your environment before you try installing `GPy` from its wheel/tar file.

**Comment by MartinBubel** [comment]
Hi @rameezdev 
Did you retry using the wheel/source dust of GPy==1.13.1?

**Comment by MartinBubel** [comment]
closing this as there is no response
