### ISSUE TITLE
Test with Python 2 style print statements

### ISSUE THREAD

**Issue by oysstu** [SheffieldML/GPy#1056]
The following test function has python 2 style print statements
https://github.com/SheffieldML/GPy/blob/bf4dc0aaa319fe00a579cdb1acabda7f366c22b2/GPy/testing/mpi_test__.py#L16-L20

**Comment by MartinBubel** [comment]
Hi @oysstu
thanks for putting this up. Could be contribute a PR fixing this one?

**Comment by ekalosak** [comment]
Is it a good idea, I wonder, to continue with Python 2 support?

**Comment by MartinBubel** [comment]
Hell no. We should get rid of any python2 stuff here.

**Comment by lawrennd** [comment]
I also can't think of a reason to maintain Python 2 any more.

**Comment by MartinBubel** [comment]
I'm a little busy at the moment but I hope I'll find some time to finish some issues and PRs over summer.
