### ISSUE TITLE
Extending Combination Covariances

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#106]
Let's say we have two functions drawn from a Gaussian process, f_1, and f_2. We are given (perhaps) some observations of f_1, some of f_2 and some of f_1 + f_2. We want to build a model that allows easily for this case.

It think we need to expand the capabilities of the combination covariance, with a 'which parts' type facility which works for each data point, allowing us to specify which parts of the combined covariance function are active for any particular data point. 
This might be enacted by a flag (like we have been doing tensor, although I know we are scheduled to discuss that). This reflects the fact that, in actuality, any combination of covariance functions *is* a multi output model. Normally we ignore this, but there are situations when it's useful. I need this functionality in the base class to extend the sympy kernel with covariances that apply linear operators to existing covariance functions (I believe). So that we could have

f_3 = L_1(f_1) + L_2(f_2) 

For example. But this is a facility that we need to have a team discussion around so that we get the implementation right for everyone.

**Comment by mzwiessele** [comment]
It needs to be done in the way we do it for the coregionalization with an additional indexing dimension, so that underlying inferences do not have to know about this. The Hierarchical kernel does that for you. Have a look.
