### ISSUE TITLE
matplotlib dependency in setup.py

### ISSUE THREAD

**Issue by DManowitz** [SheffieldML/GPy#1077]
Starting with v1.13.0, [`setup.py`](https://github.com/SheffieldML/GPy/blob/devel/setup.py), specifies `matplotlib==3.3.4` as a dependency for the `plotting` extra.  This seems like an old version of `matplotlib` to be requiring for a newer version of this package.  Also, according to issue #1069, it looks like this package should be supporting very new versions of `matplotlib`.  Is the version in `setup.py` actually the correct dependency?

**Comment by MartinBubel** [comment]
Hi @DManowitz 
yeah it should be fixed as off #1070 but that change is not available as a release just yet.
I am a bit short on time and still haven't got everything dialed for the next patch #1071.
I will try to find some time. If you cannot wait, in the meanwhile, you can use `GPy`'s develop branch as a git-dependency.

Btw. I'm grateful for anybody willing to pick up issues and make contributions.

**Comment by MartinBubel** [comment]
I will close this issue as it is already adressed as off #1069 . Feel free to reopen if you disagree.

Also, feel free to give #1071 a thumbs up to increase to show intersted in a patch. No guarantee that this speeds up the process but maybe it gives me some extra motivation :)
