### ISSUE TITLE
When is the next release ?

### ISSUE THREAD

**Issue by keldack** [SheffieldML/GPy#1079]
Hi all.

First of all, a great thanks for your work, it is a pleasure to use you library.

A correction has been done - [](https://github.com/SheffieldML/GPy/commit/741bb0b0da302cfd4b19258aa230e7b3b3abfcdf)
in the GPy/plotting/matplot_dep/variational_plots.py file considering the import were done. We faced the issue with the error ImportError: cannot import name 'numpy' from 'matplotlib' . 

So now we are waiting for this modification be officially released.

Have a nice day !

Keldack

**Comment by MartinBubel** [comment]
Hi @keldack 

I cannot give you an exact date but declaring your immediate interest will definitely speed things up.
So far my plan was to stack patch updates for as long as someone asks for a new version.

I guess it should be possible for me to get it done until end of next week.


Martin

**Comment by keldack** [comment]
Thanks a lot, Martin, for your reactivity in answering me and the proposed release date.

**Comment by tremblerz** [comment]
+1 for the release as soon as possible, the numpy error is preventing from even importing the library right now. Thanks!

**Comment by MartinBubel** [comment]
I'm almost there. However, I want to get #1080 through first, as it currently shows some issues (also with newer numpy versions) on Mac OS.
I was hoping to get my hands on a mac device today but that thing has some network connection issues. Probably will take a couple more days for me to get the patch out.
But see this as a status update: It's on my todo list and I am working on it :)

**Comment by MartinBubel** [comment]
after battleing both linux and mac runners for multiple evening-sessions in a row, GPy 1.13.2 is finally available on pypi.
