### ISSUE TITLE
Not return/calculate the variance?

### ISSUE THREAD

**Issue by Cargonher** [SheffieldML/GPy#1085]
Is there a way to not return (and not compute!) the variance when using predict_noiseless() ? I don't need that information for the moment and I want to save as much computational time as possible

Thank you

**Comment by MartinBubel** [comment]
Accessing variance may differentiate depending on your setup.

Without more information, I cannot help, I'm afraid. Did you consider looking into the code and trace how predict_noiseless works and where you could acquire the information you won't without additional computations? That might be the best way to get there.

**Comment by Cargonher** [comment]
Hi Martin,

Maybe I wasn't clear - my question is whether the computation of the variance can be toggled off in predict_noiseless (e.g. there's a boolean variable for this on scikit). I did have a look into the code but couldn't trace back the variance computation nor the corresponding covariance matrices multiplication.

Thank you.

**Comment by MartinBubel** [comment]
you can set `full_covar=False`, which onley computes the diagonal entries, surely being less expensive, if that is what you want.
I hope that answers your question?

**Comment by MartinBubel** [comment]
I'm gonna close tihs issue. If you feel like your question has not been answered, feel free to reopen.
