### ISSUE TITLE
module 'GPy' has no attribute 'kern'

### ISSUE THREAD

**Issue by ToMdAvI** [SheffieldML/GPy#1094]
Hello,

I have also just got this error. Using Python 3.12.4 in Spyder/Anaconda. GPy has been downloaded within last few hours.

Thanks
![Screenshot 2024-07-25 164552](https://github.com/user-attachments/assets/74692a7d-37ee-41cb-a5e7-03fe3a065526)

**Comment by MartinBubel** [comment]
Hi @ToMdAvI 
I just tested it by creating a new python3.12 venv, installing GPy and running import GPy.kern, and everything worked fine (though I get some unepxected warnings but that's another story). 
Pasting some command line screenshot is not enough for me to help you.

Please elaborate a little more an what you are doing, what the conflicting section (code) looks like, what your installation setup is ...

**Comment by ToMdAvI** [comment]
Thanks for the reply @MartinBubel.

I managed to sort the issue. I realised my code was calling a folder within the main GPy folder I installed, also called GPy, which I think was causing my confusion. I did not need the whole repository.

As a novice to Python, working this out is all a part of the learning process. And hopefully I can help other people who may experience this problem in the future.

**Comment by MartinBubel** [comment]
Thanks for the reply @ToMdAvI and glad you sorted it out 👍
