### ISSUE TITLE
Heteroscedastic Regression References

### ISSUE THREAD

**Issue by Artraxon** [SheffieldML/GPy#1096]
Hi,
I don't know much about the specifics of implementing Gaussian Process Regressions, but I am using the heteroscedastic gaussian process regression with learned variances as shown in this notebook https://github.com/SheffieldML/notebook/blob/master/GPy/heteroscedastic_regression.ipynb .

Does someone have some references on how the heteroscedastic Gaussian Process Regression in this library is implemented (from a mathematical perspective)?

**Comment by MartinBubel** [comment]
Hi @Artraxon 
generally in heteroscedastic Gaussian Process regression, the variance is learned as a function of x based on known variances for the training data.

As far as I could check the GPy implementation does not fully account for that atm, I'm afraid. It seems like the variance is fixed for the training data but not learned as a function of the features/inputs (x) for the prediction of new points, as it is said at the bottom of the notebook you commented.

[Here](https://github.com/pytorch/botorch/blob/main/botorch/models/gp_regression.py#L258) is a reference to an implementation from botorch which may be helpful in understanding the implementation.

Does this answer you question?

**Comment by Artraxon** [comment]
Hi,
I'm aware that it does not calculate a variance estimate for new points, I was interested in the variance estimation for the trainings data.

If there is no high-level write up available thats also fine, its not super important for me

**Comment by MartinBubel** [comment]
I'm afraid there is no such write-up here. Sorry for that.
