### ISSUE TITLE
Implementing new Likelihoods

### ISSUE THREAD

**Issue by ingmarschuster** [SheffieldML/GPy#114]
I want to modify a linear model of mine to use Gaussian processes. Now I had been using a Dirichlet-Compound-Multinomial (DCM) likelihood for discrete RVs which doesn't exist in GPy.
I'm not exactly sure where to start - the poisson likelihood, which is closest to my application, seems to be implemented as a noise model, so should I start by modifying this? (As an aside: in my linear model I had also evaluated a Poisson likelihood but the performance was poor, so I'd really want to go for implementing a DCM likelihood)

Maybe the generative model helps:

m_i ~ N(0,I) for i in 1,...,n
w ~ GP(0, K)
data ~ DCM(w(m_i, m_j), num_draws)

Also: when optimizing the parameters of the GP, can I optimize additional variables at the same time (in particular the m_i)? Thanks for any pointers and hints,

Ingmar

**Comment by jameshensman** [comment]
Hi @ingmarschuster , 

what you're describing is moderately tricky I think. Let me expand on the model a bit, let me know if I'm wrong:

1) there are multiple (independent?) GPs w_j
2) there is a link function which transforms the w_j(m_i) variables (exponent presumably) into the alpha variables of the Dirichlet. 

Did you see this paper? looks relevant to me: http://arxiv.org/abs/1506.05843
Also this:
http://mlg.eng.cam.ac.uk/yarin/PDFs/Latent_Gaussian_Processes_for_Distribution_Estimation_of_Multivariate_Categorical_Data.pdf

A simpler case of what you're describing is multi-class classification (where each of the num_draws is 1). I've been working on that a little, code coming soon, paper here: http://arxiv.org/pdf/1506.04000.pdf

The good news is that most of the bits and bobs are in place for what you want in GPy. The bad news is that nonlinear latent variable models with non-Gaussian likelihoods is hard in general. The problem stem s from the fact that the latent variables (m in your model) need to be optimized alongside some variational variables which account for the non-Gaussianity. The two are strongly linked, so it can be hard to find a good mode of the posterior. 

>Also: when optimizing the parameters of the GP, can I optimize additional variables at the same time (in particular the m_i)? Thanks for any pointers and hints,
Yes absolutely. Se our implementation of the (Bayesian) GPLVM or Stochastic variational GP, or many other projects!

James.
