### ISSUE TITLE
Using GPy for data imputation?

### ISSUE THREAD

**Issue by jamesmcm** [SheffieldML/GPy#120]
How can one use GPy for data imputation? For example, if I have say, 4 floats, but each of them have missing values for different samples, how can I impute the missing values from the relationship between all of them?

For example, one could imagine using several (multi-output) GPs for each of the circumstances where just A is missing, or A and B are missing, etc. - but there must be a simpler way of doing this, right?

**Comment by zhehe** [comment]
According to this page:
http://pythonhosted.org/GPy/GPy.inference.latent_function_inference.html

The GPy.inference.latent_function_inference.var_dtc.VarDTCMissingData() is no longer valid?
If using GPy to optimize the model with missing data, what choices do we have?

I also found there is argument missing_data=True/False, could we simply set this flag, and pass in missing value as numpy.nan?
Thanks

**Comment by mzwiessele** [comment]
You should use the models from sparsegp_minibatch and bgplvm_minibatch, which have a init argument missing_data = True.

**Comment by max-li-dd** [comment]
Hi @mzwiessele, are there notebooks demonstrating the use case described in section 6.2 (GP Regression with Missing Inputs and Data Imputation ) of the following paper 
"Variational Inference for Latent Variables and Uncertain Inputs in Gaussian Processes". 
If not, is the algorithm used in section 6.2 implemented in GPy? Thanks!
