### ISSUE TITLE
Can't import GPy

### ISSUE THREAD

**Issue by rtrangucci** [SheffieldML/GPy#125]
used: 
pip3 install GPy 
with python3.4 on OS X Mavericks. 

I can't seem to figure out how to get the package to import correctly.

Here's the traceback from ipython:
## In [1]: import GPy

ImportError                               Traceback (most recent call last)
<ipython-input-1-c6d42d62ab4a> in <module>()
----> 1 import GPy

/Users/rtrangucci/GPy-master/GPy/**init**.py in <module>()
     11 **version** = read('version')
     12 
---> 13 import core
     14 import models
     15 import mappings

ImportError: No module named 'core'

Any idea what's going on?

**Comment by andrew-hill** [comment]
Since Python 2 is considered legacy, could you please note this limitation clearly on the github project page, main project page, online documentation and/or tutorial index?
