### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#130]
- Model Tests
- Inference Tests

Anything I forgot?

**Comment by mzwiessele** [comment]
@alansaul @jameshensman @zhenwendai @ric70x7 have worked to get those tests done:

* Likelihood Tests
* Kernel Tests (for every kernel)
* Parameterized Tests
* Caching Tests
* Pickle Tests

**BUT** these tests are still not good enough:

* Model Tests
* Inference Tests

will delete the covered tests from inital comment

**Comment by mzwiessele** [comment]
* Test samplers
* Test sparse models with ep
* test BGPLVM with ep

**Comment by mzwiessele** [comment]
We need to put the util functions into a good state. I'd suggest for everyone to have a look and write tests for functions which are still used, or delete modules in there, which are not used. The util module got way too big for being called util, so either we get rid of some part of it, or we put the functions into their respective use cases, I'd suggest.

**Comment by mzwiessele** [comment]
- Posterior tests!

**Comment by ekalosak** [comment]
Stale.
