### ISSUE TITLE
Examples.classification.crescent_data()

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#142]
This example isn't working, no attribute m.pseudo_EM(). 

Ricardo, I think this is your old code from Master? It would be cool to get it working again ... is it a big issue to fix?

**Comment by mzwiessele** [comment]
Is this going anywhere? I have not launched the example in a long time.

**Comment by lawrennd** [comment]
I thought at the last (and only!) developers meeting we decided to convert
examples to benchmarks/tests and have the real examples in the notebooks. I
 may have misremembered though! We can rediscuss when we start developer
meetings. Thanks for clearing up all these issues Max!
