### ISSUE TITLE
Bayesian GPLVM with MPI does not run properly.

### ISSUE THREAD

**Issue by zhenwendai** [SheffieldML/GPy#144]
Due to some unknown recent changes, Bayesian GPLVM with MPI does not run properly. If you want to use parallel bgplvm now, please checkout the tag: bgplvm-mpi.

**Comment by jameshensman** [comment]
@zhenwendai , did you look into this? Will it work for 0.8?

**Comment by mzwiessele** [comment]
@zhenwendai says fixed
