### ISSUE TITLE
config notebook is out of date

### ISSUE THREAD

**Issue by jameshensman** [SheffieldML/GPy#153]
datasets have been moved to pods: how does this work with the config files now?

**Comment by mzwiessele** [comment]
Not sure if I understand. 

The config files are for configurations of GPy settings. 
Pods is for datasets (and examples).

Where is the clash here?

**Comment by mzwiessele** [comment]
The mentioned config notebook is 
https://github.com/SheffieldML/notebook/blob/master/GPy/config.ipynb

@lawrennd @jameshensman could you have a look? Maybe we do not need this anymore anyway?

**Comment by mzwiessele** [comment]
No one cares, closing
