### ISSUE TITLE
metropolis hastings does not work

### ISSUE THREAD

**Issue by jameshensman** [SheffieldML/GPy#154]

**Comment by mzwiessele** [comment]
Updates?

**Comment by mzwiessele** [comment]
Who wrote the metropolis hastings algorithm, and can we have this updated?

**Comment by mzwiessele** [comment]
Hello?

**Comment by mzwiessele** [comment]
@zhenwendai Can we close this, by either deleting hmc or implementing it?

**Comment by zhenwendai** [comment]
I think we could either close this and delete the mcmc sampler code or 
implement this (if somebody really need it).

Zhenwen

**Comment by lawrennd** [comment]
@zhenwendai @mzwiessele ... don't delete hmc ... that works right? This is
for metropolis hastings right?

**Comment by zhenwendai** [comment]
hmc sampler works fine and we have test cases for that. This is for the 
old metropolis hasting implementation that hasn't adapted to the param 
framework.

Zhenwen

**Comment by lawrennd** [comment]
I'd agree on removal then as a tidying up step.

**Comment by mzwiessele** [comment]
Is it deleted? Can we close the issue? @zhenwendai

**Comment by zhenwendai** [comment]
Not yet. I can do the deletion in the fix negative prediction pull 
request that I will get it done tomorrow.

Zhenwen

**Comment by mzwiessele** [comment]
Is the pull request in? It still seems to fail...
