### ISSUE TITLE
Coregionalization oddities with numpy 1.9.1

### ISSUE THREAD

**Issue by alansaul** [SheffieldML/GPy#156]
Gradients w.r.t kappa fail with numpy 1.9.1, works perfectly on 1.8.1, will need investigating

Try
%run GPy/examples/regression
m = coregionalization_sparse(optimize=False)
m.checkgrad(verbose=1)
passes with numpy 1.8.1, fails with 1.9.1

**Comment by jameshensman** [comment]
@ric70x7 the plotting seems to be broken for the coregionalization model, could you take a look please (the above code errors)

**Comment by ric70x7** [comment]
Hi,
Plotting seems to be working, but let me know if it is not.

About the gradients of kappa, this was the issue:

dkappa = np.diag(dL_dK_small) # .copy() was missing
dL_dK_small += dL_dK_small.T dW = (self.W[:, None, :]*dL_dK_small[:, :, None
]).sum(0) self.W.gradient = dW self.kappa.gradient = dkappa
I assume in numpy 1.8.1 np.diag(A) created a copy of A, so the second line
of the code above didn't modified dkappa (first line)
In the current code, the second line was duplicating the values of dkappa.

I've just pushed the changes.

Cheers,
Ricardo


2015-08-13 12:38 GMT+01:00 James Hensman <notifications@github.com>:
