### ISSUE TITLE
GPy examples depend on pods?

### ISSUE THREAD

**Issue by nfusi** [SheffieldML/GPy#163]
It looks like GPy examples (e.g. GPy.examples.regression.toy_rbf_1d()) depend on https://github.com/sods/ods 

Given that the examples are probably the first thing that users run, would it make sense to upload ods to pypi and list it as a dependency in setup.py?

**Comment by jameshensman** [comment]
@lawrennd Could you take a look at this please? This is a bug in PODS, I have submitted a bug over there.

**Comment by lawrennd** [comment]
It should be installable. I think you just need the prerelease flag on some
systems. @mikecroucher and @mzwiessele are putting together the priorities
for next release. Examples should probably be reviewed alongside tests and
and benchmarks.

@lawrennd <https://github.com/lawrennd> Could you take a look at this
please? This is a bug in PODS, I have submitted a bug over there.

—
Reply to this email directly or view it on GitHub
<https://github.com/SheffieldML/GPy/issues/163#issuecomment-131014489>.
