### ISSUE TITLE
Figure1 not responding

### ISSUE THREAD

**Issue by AImeka** [SheffieldML/GPy#170]
Please can you help me as I am unable to get any plot from GPy, The graphic window opens up with the following message: Figure 1 not responding

**Comment by jameshensman** [comment]
Hi Almeka, 

I don't think this is a GPy bug, more likely related to your matplotlib installation. If you're using anaconda, try 'conda update matplotlib'. Or, make sure that matplotlib is in interactive mode: 

    from matplotlib import pyplot as plt; plt.ion()

Best wishes, 
James.
