### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by befelix** [SheffieldML/GPy#171]
Are there any plans to introduce (backwards-compatible) support for python 3?
Would you accept patches to enable python 3 support? This would require some imports from __future__ and would depend on something like six, so that would probably have to be added. 
Additionally for the C speedups weave would need to be replaced with cython.

**Comment by andrew-hill** [comment]
According to comment on #125 there's no plans for Python 3 support :/

**Comment by mikecroucher** [comment]
Hi

A couple of us are working on Python 3 support now but the work is not yet ready for general consumption. Stay tuned!

**Comment by mikecroucher** [comment]
OK, I have some progress to report. Don't use this fork for production work yet - It's almost certainly not ready.

* All tests in the testsuite now run on both Python 3 and Python 2.

To see this for yourself, in Ubuntu 14.04, you can do

    git clone https://github.com/mikecroucher/GPy.git
    cd GPy
    git checkout devel
    nosetests3 GPy/testing
    nosetests GPy/testing

nosetests3 is Ubuntu's way of referring to the Python 3 version of nosetests. You install it with

    sudo apt-get install python3-nose

* Test coverage is less than 100% so it is expected that there is still more work to be done. We need more tests and examples to try out.

* All weave functions not covered by the test suite are *simply commented out*. Can add equivalents later as test functions become available

* A set of benchmarks would be useful! I'm not a GPy user and am new to the project. Some problems that take a while to execute, along with acceptance tests would be immeasurably useful.

If you find something's broken, please give me an example that demonstrates the problem.

Cheers,
Mike

**Comment by arranger1044** [comment]
If I get it correctly, even if not fully supported, GPy can be used with python3. My question is, how can I install it with (pip3 for instance)?

**Comment by lawrennd** [comment]
We are planning for Python3 support for next release (fingers crossed).
@mikecroucher any thoughts on pip3?

**Comment by mikecroucher** [comment]
You can use it now direct from git
https://github.com/SheffieldML/GPy/tree/devel
Python 3 support might be broken again though since the python 3 tests are
not run by default yet.
It will be available via pip3 once we do a proper release.

**Comment by arranger1044** [comment]
Thanks, @mikecroucher and @lawrennd!
I do not know if it is better to open another issue, or continue here (so pardon me). After cloning and checking the devel branch, when I try to import GPy I get:
 
      /home/valerio/Petto Redigi/high-hopes/GPy/GPy/util/linalg.py:50: UserWarning: warning: caught this exception:/usr/local/lib/python3.4/dist-packages/numpy/core/_dotblas.cpython-34m.so: undefined symbol: dsyrk_
     warnings.warn("warning: caught this exception:" + str(e))
        File "/home/valerio/Petto Redigi/high-hopes/GPy/GPy/likelihoods/likelihood.py", line 610
          print "Finding predictive mean and variance via sampling rather than quadrature"
                                                                                   ^
        SyntaxError: invalid syntax

implying that some file needs to be converted yet. Or am I missing some step?

**Comment by mikecroucher** [comment]
That's a new file. Sorry!
I'll fix tomorrow

**Comment by mikecroucher** [comment]
Nothing major, just a bad print statement as you found (need to educate all
our devs, brackets are good mmmkay!), and a few indentation errors.
The tests now run under Python 3 but there are some failures -- this IS The
dev branch after all :)

Test coverage is not 100% so there might be Python 3 errors elsewhere in
the code. Please do report them so we can fix!

Hopefully, things will start to look tidier was we move towards release.

Cheers,
Mike


On 11 August 2015 at 21:57, Mike Croucher <michael.p.croucher@googlemail.com
> wrote:

> That's a new file. Sorry!
> I'll fix tomorrow

**Comment by befelix** [comment]
Might be a good idea to enforce all files to start with ```from __future__ import print_function```
On 12 Aug 2015 16:40, mikecroucher <notifications@github.com> wrote:Nothing major, just a bad print statement as you found (need to educate all
our devs, brackets are good mmmkay!), and a few indentation errors.
The tests now run under Python 3 but there are some failures -- this IS The
dev branch after all :)

Test coverage is not 100% so there might be Python 3 errors elsewhere in
the code. Please do report them so we can fix!

Hopefully, things will start to look tidier was we move towards release.

Cheers,
Mike


On 11 August 2015 at 21:57, Mike Croucher <michael.p.croucher@googlemail.com
> wrote:

> That's a new file. Sorry!
> I'll fix tomorrow

**Comment by arranger1044** [comment]
Thank you @mikecroucher , after I update the repo and try to reinstall, I get a missing `kern` module:

    In [1]: import GPy
    /home/valerio/Petto Redigi/high-hopes/GPy/GPy/util/linalg.py:50: UserWarning: warning: caught this exception:/usr/local/lib/python3.4/dist-packages/numpy/core/_dotblas.cpython-34m.so: undefined     symbol: dsyrk_
      warnings.warn("warning: caught this exception:" + str(e))
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-c6d42d62ab4a> in <module>()
    ----> 1 import GPy

    /home/valerio/Petto Redigi/high-hopes/GPy/GPy/__init__.py in <module>()
          4 warnings.filterwarnings("ignore", category=DeprecationWarning)
          5 
    ----> 6 from . import core
          7 from .core.parameterization import transformations, priors
          8 constraints = transformations

    /home/valerio/Petto Redigi/high-hopes/GPy/GPy/core/__init__.py in <module>()
          7 from .parameterization.observable_array import ObsAr
          8 
    ----> 9 from .gp import GP
         10 from .svgp import SVGP
         11 from .sparse_gp import SparseGP

    /home/valerio/Petto Redigi/high-hopes/GPy/GPy/core/gp.py in <module>()
          4 import numpy as np
          5 import sys
    ----> 6 from .. import kern
          7 from .model import Model
          8 from .parameterization import ObsAr

    /home/valerio/Petto Redigi/high-hopes/GPy/GPy/kern/__init__.py in <module>()
         18 from ._src.splitKern import SplitKern,DEtime
         19 from ._src.splitKern import DEtime as DiffGenomeKern
    ---> 20 from ._src.spline import Spline
         21 from ._src.eq_ode2 import EQ_ODE2
         22 from ._src.basis_funcs import LinearSlopeBasisFuncKernel, BasisFuncKernel,     ChangePointBasisFuncKernel, DomainKernel

    /home/valerio/Petto Redigi/high-hopes/GPy/GPy/kern/_src/spline.py in <module>()
          3 
          4 import numpy as np
    ----> 5 from kern import Kern
          6 from ...core.parameterization import Param
          7 from ...core.parameterization.transformations import Logexp

    ImportError: No module named 'kern'

**Comment by jameshensman** [comment]
Yep, that line should have been 

from .kern import Kern

for py3 compatibility. Fixed.
