### ISSUE TITLE
Polynomial covariance missing scale and bias

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#173]
Just noticed after Thomas's query that the new implementation of the polynomial covariance is incorrect. There should be a scale and a bias in it so it takes the form:

(w x^T x' + b)^d

to allow down scaling of data. The generalisation of this scaling also allows for an ARD variant.

It's worth noting that any inner product based covariance function might benefit from such scaling (e.g. the MLP has it, and in the RBF it's effectively the lengthscale). 

We did have this implementation before the major changes. We need to be a lot more careful about dropping functionality that people have already worked to integrate.

**Comment by mzwiessele** [comment]
fixed: 01a7f85
