### ISSUE TITLE
inferenceX test depends on random seed

### ISSUE THREAD

**Issue by alansaul** [SheffieldML/GPy#182]
The inferenceX test depends on a seed and doesn't always pass which is understandable. Could do with reformulating the test.

**Comment by alansaul** [comment]
This is still a stochastically failing test! @zhenwendai when you get a minute could you take a look? I know we discussed it previously and we decided it was a floored test, but it is useful to have something like this in here! Maybe we can just fix the seed!

**Comment by jameshensman** [comment]
I fixed this by setting a seed.
