### ISSUE TITLE
nan in Y values

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#185]
If someone passes 'nan' as part of a target matrix, we currently don't throw a warning, we just return nan on the likelihood (presumably because we compute with it returning a nan). Perhaps we should warn the user they've passed a nan in the data, and by default remove that point from X and Y.

**Comment by alansaul** [comment]
I agree in general but in some cases we need it, for example in @mzwiessele missing data BGPLVM code which ultimately inherits from a GP, it makes sense to allow missing values. Perhaps we could put a warning which is suppressed in some cases?

**Comment by mzwiessele** [comment]
Please refer to #138
