### ISSUE TITLE
EP Algorithms Distributed across Files and missing FITC

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#186]
We don't seem to have any inheritance structure or code reuse between our EP-implementations, for example there is a lot of overlapping code between expectation_propagation_dtc.py and expectation_propagation.py. This means if someone comes up with clever tricks for update ordering (like Joe is suggesting) they would need to be implemented in multiple places, which feels wrong. Also somehow, along the way we've lost expectation_propagation_fitc.py ... it would be nice to get this back in.

**Comment by mzwiessele** [comment]
Fixed with commit 383cf41
