### ISSUE TITLE
hyperparameters correspondence for RBF ARD betweem GPy and gpml

### ISSUE THREAD

**Issue by zaikazoo** [SheffieldML/GPy#188]
I have an algorithm implemented in matlab, I used a gpml lib from Carl Rasmussen. I use a sparce GP approximation for my regression problem. As a covariance I use a RBF ARD kernel. I pass the same input data, same induction points and same covariance function for both implementation (matlab gpml and python GPy), and I  estimate marginal likelihood  before optimization. I obtain very different values for both implementation. I guess I have an error passing the hyperparameters. The cov function is described by K(r)  
![render](https://cloud.githubusercontent.com/assets/7488057/6920203/0835d448-d7b5-11e4-8845-8c7bbe71e33d.png)
 For gpml I  pass log values of parameters ell, sigma and noise variance (according to the online documentation). 
As I understand for GPy I should pass directly the values of ell, sigma and noise variance. 
In my understanding, after passing the same input parameters (data, inducing points, hyperparameters values) to both implementations I should obtain the same value of marginal likelihood.  Could you please help me to identify what I am doing wrong?

**Comment by jameshensman** [comment]
hi @zaikazoo , 

This question is probably better on the user mailing-list. To be able to help, we'd need to see the GPy code you're using.

Closing for now, see you on the list I hope,

James.

**Comment by tinutjoy** [comment]
Hi  @zaikazoo, zaikazoo. Check the implementation of the kernel function in the both cases. In Gpml, implementation they take the exponential of the values suggested by the optimization algorithms. So even if your bound is large values, the exponential function will take care of it. Could you please check the bounds for the hyper parameters in both the implementations? Try to use the same bound and in your kernel implementation, take the exponential of the values suggested by optimization algorithm Hope this helps.
