### ISSUE TITLE
Tensor Parameter does not work

### ISSUE THREAD

**Issue by antonywaldock** [SheffieldML/GPy#192]
When using the simple example below
kern1 = GPy.kern.RBF(1) + GPy.kern.White(1)
kern2 = GPy.kern.RBF(1)
kernx = kern1.prod(kern2,tensor=True)

but I get the error

TypeError: prod() got an unexpected keyword argument 'tensor'

tensor does not appear to be a valid option. The code used to work in an older version (July 2014)

**Comment by jameshensman** [comment]
Hi @antonywaldock , 

The interface for this has changed between releases. Sorry if it caused you trouble. the correct way to implement this would be

kern1 = GPy.kern.RBF(1, active_dims=[0]) + GPy.kern.White(1)
kern2 = GPy.kern.RBF(1, active_dims=[1])
kernx = kern1 * kern2

(note that the active dimensions of the white kernel are irrelevant)
