### ISSUE TITLE
Constructing GPRegression object without samples.

### ISSUE THREAD

**Issue by btabibian** [SheffieldML/GPy#193]
Initializing a GPRegression model without samples would be useful as sometimes we start with a model without observations and iteratively add samples and compute posterior.

**Comment by alansaul** [comment]
Hi @btabibian, that does sound like this could be useful in certain cases, but without any X or Y, a GP can't really do anything (including evaluate the log_likelihood, evaluate the kernel, etc). The way GPy is set up at the moment is to take the bare minimum we need to do the above. Even with two data points, we expect the GP to be essentially useless.

**Comment by btabibian** [comment]
@alansaul Thank you for your response. I got similar answer on the mailing list. The best scenario I can think of is in Online settings. Having such initialization can help avoid extra steps that might be needed to use GPy.

**Comment by bela127** [comment]
Any updates on this?
This is very needed for a “streaming” / “online” / “active” learning setting, where one has only assumptions about the prior distribution at the start and then slowly refines the model and the model /prior parameters as data comes in.
Also, most of you have in mind the “learning” setting, but you could also use GPs for data generation from prior distributions, in which case you don't have any data to start with.

**Comment by ekalosak** [comment]
Stale.
