### ISSUE TITLE
No module named linalg_cython

### ISSUE THREAD

**Issue by mdepasca** [SheffieldML/GPy#194]
I pulled the last version of devel branch, and I'm not able to import GPy. It claims there is no module named linalg_cython.

This happens on two different machines both running Ubuntu 14.02.

Marco

**Comment by alansaul** [comment]
Hi Marco,

I believe this is as a result of our recent move to using cython. I believe
all that is necessary is to reinstall GPy which will compile the C for you,

You can either do

    python setup.py build_ext --inplace

and put GPy on your PYTHONPATH

or use

    pip install -e .

when in the top level of the GPy directory.

Let us know if this doesn't work.

**Comment by mdepasca** [comment]
Hi Saul,

I used

python setup.py build_ext --inplace

and that worked. Now the import gives no issues.

Great! thanks a lot.

Marco
