### ISSUE TITLE
.predict() is missing output

### ISSUE THREAD

**Issue by Dapid** [SheffieldML/GPy#195]
The documentation on [GPy.core.predict()][1] defines the return values as `(mean, var, lower_upper)`, but only the first two are actually returned.

Either the documentation should be fixed, or the code adapted to return the missing features.

   [1]: https://gpy.readthedocs.org/en/latest/GPy.core.html

**Comment by mzwiessele** [comment]
Fixed in documentation, thanks!

**Comment by rocreguant** [comment]
I still find it in the documentation: http://gpy.readthedocs.org/en/latest/GPy.core.html?highlight=predict#GPy.core.gp.GP.predict

and even the code:
http://gpy.readthedocs.org/en/latest/_modules/GPy/core/gp.html

What's the alternative to get the lower and upper boundaries?

**Comment by mzwiessele** [comment]
You can use predict_quantiles to get the different percentiles for the output prediction.
