### ISSUE TITLE
The bug in _raveled_index() when two level indexing 

### ISSUE THREAD

**Issue by zhenwendai** [SheffieldML/GPy#197]
The _raveled_index() for a Param object with two level indexing does not give the right indices. This affects the operations like setting constraints.

```python
In [18]: m = GPy.examples.regression.sparse_GP_regression_1D(optimize=False, plot=False, checkgrad=False)

In [19]: m.Z[:2][1:]._raveled_index()
Out[19]: array([1, 2, 3, 4])
The right index should [1]

**Comment by mzwiessele** [comment]
this is expected behaviour and will not be fixed, do not use two level indexing!
