### ISSUE TITLE
Kernel Tutorial Needs updating

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#199]
This page needs updating to the new style of kernel objects (or removing and an appropriate link to a relevant notebook). 

https://gpy.readthedocs.org/en/latest/tuto_kernel_overview.html?highlight=kernel%20tutorial

**Comment by mzwiessele** [comment]
this is weird, i thought this has been done already? i remember on one hackday we had a distribution of doc updates, i did the model part and someone else said he or she would do the kernel part, does that ring a bell for someone?

**Comment by lawrennd** [comment]
Can you pop up a link to how this material is accessed in case someone is
willing but unable due to not knowing (like I was in a brief window when I
saw this problem).

Neil

**Comment by mzwiessele** [comment]
ne just needs to update the corresponding file in GPy/doc/<something i dont remember>/tuto_kernel_overview.rst

the build is being done automatically on commit, thanks to @asaul!

**Comment by jameshensman** [comment]
We need to ensure these changes get carried over to 0.8 (They should, when devel is merged onto master)
