### ISSUE TITLE
Issue with using dimension reduction of GPy

### ISSUE THREAD

**Issue by OscarLiXi** [SheffieldML/GPy#200]
After using GPLVM to do a dimension reduction, how to reconstruct the data from low dimension to higher dimension? In the ealier version, we use gplvm.predict but now it seems it didn't work now. Can someone give me an example of how to do this?

Best,
Oscar

**Comment by mzwiessele** [comment]
You can still use model.predict(model.X.mean) for the point estimate of the first moment and when you are working with the devel branch, you can also use the full latent distribution, by calling model.predict(model.X).

**Comment by alansaul** [comment]
Closing for now, please post on the user mailing list if you are having any further problems after following @mzwiessele suggestion!
