### ISSUE TITLE
FAILED test in GPy.testing.pickle_tests.py (test_modelcreation)

### ISSUE THREAD

**Issue by mathDR** [SheffieldML/GPy#201]
When running GPy.tests() the following error occurs:
On line 143 of  test_modelrecreation:
np.testing.assert_allclose(pcopy.param_array, par.param_array, atol=1e-6)
This line fails.  My computer computes:
pcopy.param_array = [  3.09445348e-01   1.63745336e+00   1.23195228e-15]
par,param_array =  [  6.45484765e-01   2.14052788e+00   1.23195228e-15]
        
Note, I am running Mac OSX 10.9.5, GPy version GPy-0.6.0

**Comment by mzwiessele** [comment]
Can you recreate this error using 0.8? 
It should be fixed now.

Thanks for spotting it.

**Comment by mathDR** [comment]
Thanks.  All tests pass now.
