### ISSUE TITLE
Negative Variances from predictive_gradients()

### ISSUE THREAD

**Issue by smason** [SheffieldML/GPy#202]
I'm trying to get at the gradient of the predictions, but the variance of the estimate is coming back negative.  Not sure if what I'm doing is wrong, but as a MWE, the following seems to demonstrate the issue:

    import GPy
    import numpy as np

    # keep deviates deterministic (actual seed not important)
    np.random.seed(123)

    # draw from our function
    X = np.random.uniform(-3.,3.,(20,1))
    Y = np.sin(X) + np.random.randn(20,1)*0.05
    
    # set up model
    m = GPy.models.GPRegression(X, Y)
    
    # optimise parameters (optional)
    m.optimize()
    
    # where do we want to predict our function
    Xp = np.linspace(-4,4,51)[:,None]
    
    # get our predictions of mean and gradient
    mu,var = m.predict(Xp)
    mug,varg = m.predictive_gradients(Xp)
    
    # display variance in estimate of gradient?
    print(varg)

I get back a number of negative values for the variance, which I'm not expecting…  If I plot my test points and the function being fit they look fine:

![gpy-dx-var](https://cloud.githubusercontent.com/assets/1433005/8157071/857578e4-1349-11e5-9100-ef9718527553.png)

But the variance seems to have a lot of unexpected structure, i.e. doesn't just look like numerical instability to me.  Not sure if this matters, but I'm running without Weave (I'm under OS X and am currently struggling to get OMP code compiling) so don't know if the C version is correct.

I've just started to use GPy, so sorry if this issue/question is malformed!  While poking around I've just seen `m._raw_predict()` which looks useful as well.  The underscore prefix makes it look as though it should be internal/private, is it recommended to be using this function?

**Comment by smason** [comment]
Just tried under Linux with latest versions (Python=2.7.9, numpy=1.9.2, scipy=0.15.1, GPy=0.6.0) and I get the same result, so probably nothing to do with the lack of working Weave under OS X.

**Comment by befelix** [comment]
As far as I know predictive gradients actually returns the derivative of the mean and variance predictions, not the predictions of the derivative of the GP. So what you're seeing is that the variance of your function is decreasing between -4 and -1, is roughly constant up to 3 and then starts increasing between 3 and 4.

**Comment by smason** [comment]
OK, thanks for the note.
AFAICT, the derivative of the mean should be the same as the derivative of the latent function—at least for the RBF kernel that I care about!  Not that this matters for me, but I presume this holds for most covariance functions?

I'm still unsure how to get at the variance of an estimate of the derivative of the latent function using the framework provided by `GPy`. I'll continue to read around the subject, but any pointers would be greatly appreciated!

**Comment by befelix** [comment]
The derivative of the mean should be the same for all kernel functions.

So I actually had to implement that myself for RBF functions. Couldn't figure out an easy generic way for all kernels either, mostly because there doesn't seem to be a way to get the second derivative of the kernel, which is needed for the prior. 

Anyways, since your just interested in RBFs anyways, here's my rbf-specific code....without any warranty or me saying that this is a good implementation in any way. There might be some way that is a lot better, I'm not involved in this project at all, just a user. If you find a bug please let me know.

```
def predict_derivatives(self, x_new):
    """
    Predict derivatives of a gp at the points x_new.

    Author: Felix Berkenkamp (befelix)

    Parameters:
    -----------derivative
    self: instance of GPy.core.gp
        With RBF kernel function
    x_new: 2d-array
        Every row is a new data point at which to evaluate the derivative
derivative
    Returns:
    --------
    mu: 2d-array
        The mean derivative
    var: 2/3d-array
        If there is only one data point to predict var is a 2d array with
        the variance matrix. Otherwise it is a 3d matrix where
        var[i, :, :] is the ith covariance matrix.
    """
    if not self.kern.name == 'rbf':
        raise AttributeError('The variance prior only works for RBF kernels.')
    x_new = np.atleast_2d(x_new)

    # Compute mean, initialize variancederivative
    mu = self.kern.gradients_X(self.posterior.woodbury_vector.T, x_new, self.X)
    var = np.empty((x_new.shape[0], x_new.shape[1], x_new.shape[1]),
                   dtype=mu.dtype)

    # Make sure lengthscales are of the right dimensions
    lengthscales = self.kern.lengthscale.values
    if not lengthscales.shape[0] == self.X.shape[1]:
        lengthscales = np.tile(lengthscales, (self.X.shape[1],))
        
    def dk_dx(X, X2):
        """Compute the derivative of k(X, X2) with respect to X."""

        # Derivative with respect to r
        dK_dr = self.kern.dK_dr_via_X(X, X2)

        # Temporary stuff
        tmp = self.kern._inv_dist(X, X2) * dK_dr

        # dK_dX = dK_dr * dr_dx
        # dr_dx1 = invdist * (x1 - x'1) / l1**2
        dk_dx = np.empty((X2.shape[0], X.shape[1]), dtype=np.float64)
        for q in range(self.input_dim):
            dk_dx[:, q] = tmp * (X[:, q, None] - X2[None, :, q])
        return dk_dx / (lengthscales ** 2)

    # Compute derivative variance for each test point
    for i in range(x_new.shape[0]):
        dk = dk_dx(x_new[None, i, :], self.X)
        # Would be great if there was a way to get the prior directly from the
        # library
        # But I think only d1 is implemented
        var[i, :, :] = np.diag(self.kern.variance / (lengthscales ** 2)) -\
            np.dot(dk.T, np.dot(self.posterior.woodbury_inv, dk))

    # If there was only one test point to begin with, squeeze the
    # corresponding dimension
    if x_new.shape[0] <= 1:
        var = var.squeeze(0)
    return mu, var
```

**Comment by smason** [comment]
Wow, thanks!

I've got few different blobs of code to do the same thing now, but this is the first that has any integration into GPy.  I'll spend some time making sure they are consistent, should help with debugging as well as my understanding.  

Have you asked on the gpy-users mailing list about ways to approach this?

**Comment by befelix** [comment]
Wasn't even aware there was an active user mailing list, guess I'll subscribe to that :)
If you figure out a better/faster way to do this please let me know!

**Comment by smason** [comment]
Yes, have a look at:
  https://lists.shef.ac.uk/sympa/info/gpy-users

I've just had a play with your code and it's consistent with my numerical estimates…  Will play more tomorrow.

**Comment by jameshensman** [comment]
This bug arose as a misnderstanding of the predictive_gradients function. Have opened a new bug to request a function with the desired behaviour. #213
