### ISSUE TITLE
Using GPy with Big Data, MemoryError

### ISSUE THREAD

**Issue by VivekSrinivasan** [SheffieldML/GPy#203]
I'm sorry if this is the wrong place to post this, but does GPy work with big data? I have a dataset that's about 50,000 instances large, and when I try and call GPy.models.GPRegression(x, y, kernel), I get a MemoryError. I've tried this on both my Mac with 16GB of RAM (and on Activity Monitor I see Python using 16GB!) and on a CentOS virtual machine that has 32GB of RAM. Here's the Traceback that I received:
![Traceback](https://cloud.githubusercontent.com/assets/2747226/8336989/093f98f2-1a5d-11e5-8a74-184822a02cba.png)
My kernel that I provide is GPy.kern.RBF(input_dim=1)
And here is a sample of my data (x and y):

X | Y
------------ | -------------
9 | 7899
9 | 7999
9 | 7799
9 | 7500
9 | 7500
9 | 7500
9 | 7500
9 | 7699
9 | 7799
9 | 7500
9 | 7500
9 | 7699
9 | 7999
9 | 7699
9 | 7500
10 | 7999
10 | 8099
10 | 7899
10 | 7799
10 | 9399
10 | 7999
10 | 7500
10 | 7500
10 | 7500
10 | 7899
10 | 7899
10 | 7699
10 | 8599
10 | 7699
10 | 7899
10 | 9099
10 | 7899
10 | 7500
10 | 8099
10 | 8099
10 | 7799
10 | 8099
10 | 7999
10 | 7999
10 | 7799
10 | 7799
10 | 7699
10 | 7699
10 | 7699
10 | 7699
10 | 7799
10 | 7999
10 | 7999
10 | 8199
10 | 7999
10 | 7500

X goes on like this from 0 -> 100, and there are about 500 y values for every x. 
If it is the case that GPy can't handle data this big, do you have any other recommendations? Would it make sense to split the data up by X so that I have several Gaussian models for every 20 x or so?

I would greatly appreciate any input. Thanks in advance.
-- Vivek

**Comment by Dapid** [comment]
A Gaussian Process requires storing a matrix of NxN. In your case, in float32, that alone means 10 TB of RAM!

You want to look at sparse GP. Here are two references (implemented in GPy):

[1] M. Titsias, Variational learning of inducing variables in sparse Gaussian processes, presented at the International Conference on Airtificial Inteligence and Statistical Learning, 2009, pp. 567 - 574.
[2] J. Hensman, N. Fusi, and N. D. Lawrence, Gaussian Processes for Big Data, presented at the Uncertainty in Artificial Intelligence, 2013.

**Comment by alansaul** [comment]
As @Dapid said I'm afraid handling such a massive X with a standard GP would be impossible regardless of the computer you were using, however the following tutorial might be useful, it shows how to use the model described in [2]:
https://github.com/SheffieldML/notebook/blob/master/GPy/SVI.ipynb

If you have any problems please don't hesitate to post on the GPy user mailing list!

[2] J. Hensman, N. Fusi, and N. D. Lawrence, Gaussian Processes for Big Data, presented at the Uncertainty in Artificial Intelligence, 2013.
