### ISSUE TITLE
[devel] missing "cblas.h"

### ISSUE THREAD

**Issue by zhenwendai** [SheffieldML/GPy#205]
The current devel branch needs "cblas.h". Cross-platform support needs to be properly solved in future.

A quick fix for Ubuntu:
apt-get install libblas-dev

**Comment by nfusi** [comment]
Yes, this doesn't work on Windows and doesn't take advantage of MKL on Linux and Mac. Scipy.linalg.blas seems to have all the required functions (ddot,  dsymv, dscal). @jameshensman do you know if there's anything that prevents a cython rewrite? Looks like you were working on cython choleskies at the time of the commit.

**Comment by alansaul** [comment]
The reason for the cblas import was to make a super quick c implementation which is wrapped up with Cython, but the c implementation relies on a BLAS routine (about 10x faster than the pure Cython implementation we had previously I believe). I hadn't realised that it doesn't use MKL though? I thought the BLAS routines would use them by default but your probably right!

We should definitely make it fall back if cblas it can't be found, as for the real bottlenecks it would be nice to be able to make C + BLAS + MKL implementations, but we shouldn't make BLAS a dependency for obvious reasons. @mikecroucher has said that he will look at this when he gets a minute. In cholesky_backprop.c there is a pure c version for the routine in question chol_backprop / old_chol_backprop.

**Comment by nfusi** [comment]
Great! I _think_ that you can call scipy.linalg.blas functions from cython code, so that you don't have to give up the BLAS (and MKL) speedup when going from C to cython.

**Comment by alansaul** [comment]
Cool! We'll look into that thanks Nicolo! Hope you're well.

**Comment by mathDR** [comment]
I just posted an issue resolving this on Yosemite.  The vecLib header files were moved on 10.10.4

**Comment by jameshensman** [comment]
the problem with calling the scipy.linalg.blas routins from cython is they don;t release the gil, so you['ll get almost no speedup over a python implementation. 

In the upcoming scipy release (16? 17?), there are cython bindings for lapack and blas, which will release the gil. So the fix is either:

 1) wait for the next scipy, re-write the reverse-model cholesky differentiation in cython (cf cython + c)
 2) work out how to compile against a local blas cleanly

@mikecroucher is looking at (2).

**Comment by Dapid** [comment]
They are in Scipy 0.16 in `scipy.linalg.cython_blas` and `scipy.linalg.cython_lapack`. It was released the 24th of July.

Here are the wrapped functions:
https://github.com/scipy/scipy/blob/master/scipy/linalg/cython_blas.pyx

**Comment by jameshensman** [comment]
Thanks @Dapid , a little help would be much appreciated. 

The only function requiring the blas library at the moment is chol_backprop in util/cholesky_backprop.c

It's only 20 line of code, so should be so easy enough to translate to cython, but the issue might be in understanding the indexing/slicing that's happening, and translating the cblas_dsymv call into cython_blas.dsymv. Perhaps you could help out there?

Code which utilises this routine is being added to the main repo this afternoon.

**Comment by Dapid** [comment]
Can this be closed? Or is it there any other raw blas call?

**Comment by mikecroucher** [comment]
closing. This is no longer an issue thanks to Dapid's PR.
