### ISSUE TITLE
m.plot missing "which_parts=" kwarg

### ISSUE THREAD

**Issue by Dapid** [SheffieldML/GPy#206]
In the docs, there is a way of plotting the contribution of each kernel part to the whole function:

https://gpy.readthedocs.org/en/latest/tuto_kernel_overview.html?highlight=kernel%20tutorial

This functionality is currently missing.

Is there any way to recover it?

**Comment by mzwiessele** [comment]
Im not sure what you mean, there is three plotting routines you can use.

Suppose you have a GPy kernel k=k1+k2 in a model m:

 - You can plot the input significances of both kernels:
  k.plot_ARD() #or every single kernel:
  k1.plot_ARD()
  k2.plot_ARD() # This will plot them into the same plt figure

 - You can plot the kernels shape:
  k.plot()# or
  k1.plot()
  k2.plot()

 - You can plot only the posterior probability of the whole GP:
  m.plot()# or for the kernel parts:
  m.plot(predict_kw=dict(kern=k1)# For the posterior induced by k1
  m.plot(predict_kw=dict(kern=k2)# For the posterior induced by k2
Note(!): If the two kernels are differently composed then a sum, there
might be interactions and the whole posterior could be NOT the independent
sum of the two parts.

Best,
Max


2015-07-17 17:45 GMT+02:00 Dapid <notifications@github.com>:

**Comment by Dapid** [comment]
Thanks for looking into this.

    m.plot(predict_kw=dict(kern=k1))

This doesn't work, I get "plot() got an unexpected keyword argument 'predict_kw'". I have realised, I am doing a heteroscedastic regression, maybe both classes are not fully in sync. Nevertheless, this suggested:

    plt.scatter(X, m.predict(X, kern=k1)[0])

that works like a charm.

**Comment by mzwiessele** [comment]
The one I wrote is working on the devel branch, but it is just a shortcut
for your solution. Thus, as long as you use the master branch you can use
your solution only.

2015-07-17 18:48 GMT+02:00 Dapid <notifications@github.com>:

**Comment by jameshensman** [comment]
Seems like this is fixed on devel (to be released very shortly). Closing.
