### ISSUE TITLE
How to compile devel on mac OSX 10.10.4 Yosemite

### ISSUE THREAD

**Issue by mathDR** [SheffieldML/GPy#207]
Maybe this will help those of you trying to compile the cython on Yosemite:

Step one:  brew install gcc (mine installed gcc-5.2)

Also, since Yosemite moved the headers for vecLib, you need to extend the extra_compile_args in setup.py by adding: '-I/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers'

Then when building:  
export CC=gcc-5; export CXX=gcc-5; python setup.py build_ext --inplace

And this gave a whole bunch of warnings but no errors!  ;-)

**Comment by alansaul** [comment]
Thanks @mathDR thats really useful! We will try and sort out our slightly odd cblas dependencies out soon so hopefully such hacks won't be necessary!

Alan

**Comment by mikecroucher** [comment]
Such hacks are no longer required :)
