### ISSUE TITLE
Anaconda MKL blas libraries don't get loaded in Linux

### ISSUE THREAD

**Issue by befelix** [SheffieldML/GPy#209]
The Anaconda MKL blas libraries don't get used on Linux. The problem seems to be the following line in util/linalg.py:
```mkl_rt = ctypes.cdll.LoadLibrary(os.path.join(anaconda_path, 'DLLs', 'mkl_rt.dll'))```
which, on my machine, and I'm guessing Linux in general, should be
```mkl_rt = ctypes.cdll.LoadLibrary(os.path.join(anaconda_path, 'lib', 'libmkl_rt.so'))```

I'm not sure what the best way to fix this is, but probably either check which system is being used or try loading both before throwing an exception.

**Comment by jameshensman** [comment]
@nfusi , would you mind taking a quick look? I suspect this code is dated. 

James.

**Comment by mikecroucher** [comment]
no longer an issue thanks to Dapid.
