### ISSUE TITLE
Ability to predict the derivative

### ISSUE THREAD

**Issue by jameshensman** [SheffieldML/GPy#213]
We currently have the ability to make predictions m(x), v(x) and get the derivative of these functions. But we don't have the ability (in general) to predict the derivate of the GP. @mzwiessele is working on this a little, and there's some helpful code in #202 .

this is unlikely to be done for 0.8, would be nice for 0.10.

**Comment by mzwiessele** [comment]
It is done and commited to 0.8, alongside the magnification factor of @alessandratosi

**Comment by jwangjie** [comment]
Hi @jameshensman , I wonder if the `predict the derivative of the GP` function was added tp GPy? If so, how can we use it? Thank you very much.

**Comment by jwangjie** [comment]
Hi @mzwiessele , I wonder how to use the `predict the derivative of the GP` function in GPy? Thank you very much.
