### ISSUE TITLE
python3 compatibility (devel branch)

### ISSUE THREAD

**Issue by arranger1044** [SheffieldML/GPy#217]
I'm opening an issue to list some more incompatibility issues I found while trying to use GPy under python3:

   - a parenthesisless print statement on line GPy/GPy/inference/latent_function_inference/laplace.py:174, `print ll` probably from this commit https://github.com/SheffieldML/GPy/commit/624d65493c75618262d0b7991e4ed766872a3028

   - another print GPy/GPy/testing/misc_tests.py:21 `print w`

   - one more here GPy/GPy/plotting/matplot_dep/models_plots.py:124 `print Ysim.shape`

**Comment by lawrennd** [comment]
Thanks so much! @mikecroucher will add these to fixes required for next
release!

**Comment by mikecroucher** [comment]
All fixed. Thanks.
