### ISSUE TITLE
Pypi and github sources inconsistent for tag 0.6.0

### ISSUE THREAD

**Issue by saihttam** [SheffieldML/GPy#220]
I was trying the tutorial [1] based on 0.6.0 github sources and it failed due to opt_SGD still being in there (was removed later).
--optimization.py-- (github 0.6.0)
def get_optimizer(f_min):
    from sgd import opt_SGD

    optimizers = {'fmin_tnc': opt_tnc,
          'simplex': opt_simplex,
          'lbfgsb': opt_lbfgsb,
          'scg': opt_SCG,
          'sgd': opt_SGD}
....
----
The sources on https://pypi.python.org/pypi/GPy for 0.6.0 work fine, since the opt_SGD is gone.
--optimization.py-- (pypi 0.6.0)
def get_optimizer(f_min):

    optimizers = {'fmin_tnc': opt_tnc,
          'simplex': opt_simplex,
          'lbfgsb': opt_lbfgsb,
          'scg': opt_SCG}
....
----

[1] http://nbviewer.ipython.org/github/SheffieldML/notebook/blob/master/GPy/basic_gp.ipynb

**Comment by mzwiessele** [comment]
So this is fixed now? Can I close?
