### ISSUE TITLE
Scipy 0.16 dependancy, belayed release

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#221]
Scipy 0.16 was not officially released yet, see http://www.scipy.org/#news. This means the distribution packages yet (Anaconda, Canopy). Thus, if we want to depend on the features of Scipy 0.16 we need to wait with the release, or make it work with older versions of Scipy as well...

**Comment by Dapid** [comment]
That page is out of date. Scipy 0.16 is released and on Pypi:

https://pypi.python.org/pypi/scipy/0.16.0

Scipy 0.16 is also available in Conda.

**Comment by mzwiessele** [comment]
Hmm, it is not available in Canopy, though... We need it to be widely available, for a master release. I will perform a major system upgrade and see if it will be available then.

**Comment by Dapid** [comment]
Canopy doesn't seem to have it yet:

https://www.enthought.com/products/canopy/package-index/

Anyway, it has been out for more than a month, I think it is fair to ask them to update.

**Comment by mzwiessele** [comment]
I have put in a request with enthought, lets see how it goes. In the version of conda, which you download scipy 0.16 is not installed, though, so it might be good to inform the user somehow that he has to install scipy 0.16.

**Comment by alansaul** [comment]
Is the only dependency on 0.16 the Cython+BLAS thing?

**Comment by mzwiessele** [comment]
yes

**Comment by Dapid** [comment]
The dependency on Scipy 0.16 is specified in `setup.py`, so Conda should upgrade Scipy automatically; otherwise, it is a bug.

**Comment by mzwiessele** [comment]
yes that is true, not tested...

**Comment by mzwiessele** [comment]
Answer from Enthought support:

*I'm sorry, but I expect that scipy will be updated in Q4 so that the build team can focus on fundamental improvements.*

Thus, there is two options:

  1. We support the older versions still
  2. We make people use Anaconda and make good instructions of how to install scipy 0.16

**Comment by mzwiessele** [comment]
An automated install is not possible, this is the traceback when performing an automated install:

```
Searching for scipy>=0.16
Reading https://pypi.python.org/simple/scipy/
Best match: scipy 0.16.0
Downloading https://pypi.python.org/packages/source/s/scipy/scipy-0.16.0.zip#md5=1764bd452a72698b968ad13e51e28053
Processing scipy-0.16.0.zip
Writing /tmp/easy_install-CfxfgJ/scipy-0.16.0/setup.cfg
Running scipy-0.16.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-CfxfgJ/scipy-0.16.0/egg-dist-tmp-f2WiyP
/home/maxz/anaconda/lib/python2.7/site-packages/numpy/distutils/system_info.py:1505: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
/home/maxz/anaconda/lib/python2.7/site-packages/numpy/distutils/system_info.py:1516: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  warnings.warn(LapackNotFoundError.__doc__)
/home/maxz/anaconda/lib/python2.7/site-packages/numpy/distutils/system_info.py:1519: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  warnings.warn(LapackSrcNotFoundError.__doc__)
Running from scipy source directory.
error: no lapack/blas resources found
```

**Comment by mzwiessele** [comment]
Instead what you have to do, **before** install GPy:

```$ conda update scipy```

**Comment by mzwiessele** [comment]
Readthedocs cannot install scipy, but this is on the readme front page now, so releasing
