### ISSUE TITLE
Brnaches

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#222]
We need to get rid of the branches, which are not needed anymore. 
 You can easily view old branches, which are not updated anymore by going into the branchs/stale section of the github page of GPy:

https://github.com/SheffieldML/GPy/branches/stale

Please delete the branches you do not need anymore, so we can focus on the release.

Thanks!

**Comment by mzwiessele** [comment]
It has been a while since our repo has been cleansed from unused branches.
That is why more consequent actions will be taken soon.
Please look through the list of [stale branches](https://github.com/SheffieldML/GPy/branches/stale) and make sure your branch on there is not still in use.

If it is, make sure to either unstale it, by pushing some commits or drop a note in the [issue 222](https://github.com/SheffieldML/GPy/issues/222), so the branch gets not deleted.

Every, I repeat **every stale branch not tagged in the issue 222 will be deleted** by the end of next week (**September 18th 2015**)!

**Comment by mzwiessele** [comment]
It has been a while since our repo has been cleansed from unused branches.
That is why more consequent actions will be taken soon.
Please look through the list of stale branches and make sure your branch on there is not still in use.

If it is, make sure to either unstale it, by pushing some commits or drop a note in the issue 222, so the branch gets not deleted.

Every, I repeat every stale branch not tagged in the issue 222 will be deleted by the end of next week (September 18th 2015)!

**Comment by alansaul** [comment]
Can we maybe do this after the GPSS? Looks to me like we maybe don't want
to delete the tie_params branch?

Alan

**Comment by mzwiessele** [comment]
Everyone had 2 weeks to look at it. All it takes is a post to this issue and I won't delete the branch. 
This should be enough time to put a note into this issue here. 

As of yet, only the tie_params has been tagged as not delete, **every other branch will be deleted tomorrow!**

**Comment by mu2013** [comment]
Max can you please leave kalman branch for few weeks? I have put most of
the code in kalman_new. But I want to make sure everything work well as in
kalman branch.

cheers
mu

**Comment by alansaul** [comment]
Hi Max, I'll try take a look tomorrow but can't promise, been pretty busy
with this summer school hence haven't had a minute.

Alan
