### ISSUE TITLE
RuntimeWarning:invalid value encountered in greater

### ISSUE THREAD

**Issue by mikecroucher** [SheffieldML/GPy#223]
On running the unit tests in devel on Ubuntu 64bit using Anaconda Python and Python 2.7:

   GPy/GPy/core/parameterization/transformations.py:77:  RuntimeWarning:invalid value encountered in greater
   GPy/GPy/core/parameterization/transformations.py:82: RuntimeWarning:invalid value encountered in greater

Can others confirm please?

**Comment by Dapid** [comment]
I don't get them on Fedora 21, GCC 4.9.2 and Python 2.7.8 (virtualenv).

I do get a failure:

    ======================================================================
    FAIL: test_safe_exp_upper (GPy.testing.misc_tests.MiscTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/david/.virtualenvs/py27/lib/python2.7/site-packages/GPy-0.6.1-py2.7-linux-x86_64.eg/GPy/testing/misc_tests.py", line 23, in test_safe_exp_upper
        assert len(w)==1 # should have one overflow warning
    AssertionError: 

In case it matters, my CFLAGS are tuned to my CPU: `-march=core-avx2 -O2 -pipe -mtune=native`

**Comment by alansaul** [comment]
Thats interesting Dapid, I've not managed to duplicate that error on any machine other than Travis either! For some reason on some machines something which is obviously a overflow warning doesn't get reported as one. Anyone any idea why this might be?

I believe the line that should show a warning:

```
np.finfo(np.float64).max
np.isinf(np.exp(_lim_val_exp + 1))
```

Has anyone managed to make this happen on their machine? Do you think there might be a reason why Travis wouldn't allow us to capture these warnings?

**Comment by mzwiessele** [comment]
Dont get them anymore, the test suite is now catching runtime errors. Also the len(w)==1 is now len(w)<=1, so that if no runtimewarning was thrown, it still passes.
