### ISSUE TITLE
Devel: Intermittent test failures on Mac OS X

### ISSUE THREAD

**Issue by mikecroucher** [SheffieldML/GPy#226]
Some of the tests fail intermittently on Mac OS X.
Is there still unseeded randomisation in these tests?

Run 1 is OK:

nosetests GPy/testing/    SSSSSSS........./Users/walkingrandomly/myGPY/GPy/GPy/core/parameterization/transformations.py:77:RuntimeWarning:invalid value encountered in greater
 /Users/walkingrandomly/myGPY/GPy/GPy/core/parameterization/transformations.py:82: RuntimeWarning:invalid value encountered in greater
........................................................................................................................................................................................................................................S.S...............................................................
----------------------------------------------------------------------
Ran 314 tests in 10.560s

OK (SKIP=9)

Run 2 is OK

client-172-18-33-1:GPy walkingrandomly$ nosetests GPy/testing/
SSSSSSS......... /Users/walkingrandomly/myGPY/GPy/GPy/core/parameterization/transformations.py:77: RuntimeWarning:invalid value encountered in greater
 /Users/walkingrandomly/myGPY/GPy/GPy/core/parameterization/transformations.py:82: RuntimeWarning:invalid value encountered in greater
........................................................................................................................................................................................................................................S.S...............................................................
----------------------------------------------------------------------
Ran 314 tests in 10.539s

OK (SKIP=9)

Run 3, not so much

client-172-18-33-1:GPy walkingrandomly$ nosetests GPy/testing/
SSSSSSS......... /Users/walkingrandomly/myGPY/GPy/GPy/core/parameterization/transformations.py:77: RuntimeWarning:invalid value encountered in greater
 /Users/walkingrandomly/myGPY/GPy/GPy/core/parameterization/transformations.py:82: RuntimeWarning:invalid value encountered in greater
.............................................................................................................F..........................................................................................................................S.S...............................................................
======================================================================
FAIL: GPy.testing.likelihood_tests.TestNoiseModels.test_scale2_models(<GPy.likelihoods.gaussian.Gaussian object at 0x109bc43d0>, array([[ 0.76308289,  7.79918792,  4.38409231],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/walkingrandomly/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/walkingrandomly/myGPY/GPy/GPy/testing/likelihood_tests.py", line 592, in t_laplace_fit_rbf_white
    assert m.checkgrad(verbose=1, step=step)
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Warning, Exact inference is not implemeted for non-identity link functions,            if you are not already, ensure Laplace inference_method is used

t_laplace_fit_rbf_white
-15.0297605729
-2.95343012959
-34.5696741291
-2.95343012959
-7.56617769197
-4.71534289239
-2.95343025035
-2.95343025035
-2.95343012959
-15.0297605729
-2.95343012959
-2.95343012959
-2.95343012959
-2.95343012959
-2.95343012959
-2.95343012959
-2.95343012959

<REDACTED>

**Comment by mzwiessele** [comment]
#249

**Comment by mzwiessele** [comment]
Havent got them anymore, thanks @mikecroucher
