### ISSUE TITLE
Test failure on Windows

### ISSUE THREAD

**Issue by mikecroucher** [SheffieldML/GPy#228]
Windows 7. Anaconda Python 2.3. Python 2.7.10

......................................................... C:\Users\Mike Croucher
\GPy\GPy\likelihoods\link_functions.py:103: RuntimeWarning:overflow encountered
in exp
 C:\Users\Mike Croucher\GPy\GPy\likelihoods\link_functions.py:99: RuntimeWarning
:overflow encountered in exp
 C:\Users\Mike Croucher\GPy\GPy\likelihoods\link_functions.py:107: RuntimeWarnin
g:overflow encountered in exp
 C:\Users\Mike Croucher\GPy\GPy\likelihoods\link_functions.py:113: RuntimeWarnin
g:overflow encountered in exp
. C:\Users\Mike Croucher\GPy\GPy\likelihoods\link_functions.py:143: RuntimeWarni
ng:overflow encountered in log1p
 C:\Users\Mike Croucher\GPy\GPy\core\model.py:377: RuntimeWarning:invalid value
encountered in absolute
 C:\Users\Mike Croucher\GPy\GPy\core\model.py:384: RuntimeWarning:invalid value
encountered in absolute
 C:\Users\Mike Croucher\GPy\GPy\core\model.py:386: RuntimeWarning:invalid value
encountered in absolute
F. C:\Users\Mike Croucher\GPy\GPy\testing\link_function_tests.py:102: RuntimeWar
ning:overflow encountered in log1p

**Comment by mikecroucher** [comment]
Might be related to this http://www.walkingrandomly.com/?p=5852

Issue opened with numpy https://github.com/numpy/numpy/issues/6286

**Comment by lawrennd** [comment]
Nice spot Mike!

**Comment by mikecroucher** [comment]
This has been fixed :)
The trick is to use the scipy implementation of log1p as recommended in the comments of the WalkingRandomly post.

**Comment by mzwiessele** [comment]
#249
