### ISSUE TITLE
import fails with python 3.4 on Windows 32bit

### ISSUE THREAD

**Issue by CatherallConsulting** [SheffieldML/GPy#233]
When using Anaconda 32 bit python 3.4 version, SciPy 0.16 for 32bit python 3.4, manual install of GPy 0.8 (via: python setup.py install). Command import GPy (in ipython) gives error about missing module named 'hmc', here is the output from ipython:

Python 3.4.3 |Anaconda 2.3.0 (32-bit)| (default, Mar  6 2015, 12:08:17) [MSC v.1600 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.
 
IPython 3.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.
 
In [1]: import GPy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c6d42d62ab4a> in <module>()
----> 1 import GPy
 
C:\Anaconda3\lib\site-packages\gpy-0.8-py3.4-win32.egg\GPy\__init__.py in <module>()
      4 warnings.filterwarnings("ignore", category=DeprecationWarning)
      5 
----> 6 from . import core
      7 from .core.parameterization import transformations, priors
      8 constraints = transformations
 
C:\Anaconda3\lib\site-packages\gpy-0.8-py3.4-win32.egg\GPy\core\__init__.py in <module>()
      2 # Licensed under the BSD 3-clause license (see LICENSE.txt)
      3 
----> 4 from .model import *
      5 from .parameterization.parameterized import adjust_name_for_printing, Parameterizable
      6 from .parameterization.param import Param, ParamConcatenation
 
C:\Anaconda3\lib\site-packages\gpy-0.8-py3.4-win32.egg\GPy\core\model.py in <module>()
      4 
      5 from .. import likelihoods
----> 6 from ..inference import optimization
      7 from ..util.misc import opt_wrapper
      8 from .parameterization import Parameterized
 
C:\Anaconda3\lib\site-packages\gpy-0.8-py3.4-win32.egg\GPy\inference\__init__.py in <module>()
      1 from . import latent_function_inference
      2 from . import optimization
----> 3 from . import mcmc
 
C:\Anaconda3\lib\site-packages\gpy-0.8-py3.4-win32.egg\GPy\inference\mcmc\__init__.py in <module>()
----> 1 from hmc import HMC
      2 from samplers import *
 
ImportError: No module named 'hmc'

**Comment by Dapid** [comment]
I saw the same in Linux in Travis, but it is now behaving.

**Comment by mikecroucher** [comment]
I've just tried this on a 32bit VM and can reproduce it.

**Comment by mikecroucher** [comment]
Should be fixed now. 
I expect more problems like this but they should be easy to fix. Thanks so much for reporting.
