### ISSUE TITLE
GPy pip install fails on 0.8.2

### ISSUE THREAD

**Issue by befelix** [SheffieldML/GPy#238]
The install of the new version fails on my system.
This is on top of an up-to-date anaconda with python2.
```
>>> pip install GPy

Collecting GPy
  Downloading GPy-0.8.2.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 503kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/felix/pip-build-FpGBYe/GPy/setup.py", line 90, in <module>
        long_description=read_to_rst('README.rst'),
      File "/tmp/felix/pip-build-FpGBYe/GPy/setup.py", line 18, in read_to_rst
        return read(fname)
      File "/tmp/felix/pip-build-FpGBYe/GPy/setup.py", line 10, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/felix/pip-build-FpGBYe/GPy/README.rst'
```

**Comment by befelix** [comment]
Oh, looks like this is already fixed on the devel branch. Sorry

**Comment by mzwiessele** [comment]
Yes bad commit of me! I will submit a hotfix tomorrow first thing in the morning onto pip.

**Comment by Dapid** [comment]
There is a testing version of [PyPi](https://testpypi.python.org/pypi). You can pass the flag `--pre` to pip to fetch packages from there.

**Comment by johann-petrak** [comment]
For some reason trying to use `sudo pip install --pre GPy` produced the same error for me.
I ended up downloading https://testpypi.python.org/packages/source/G/GPy/GPy-0.8.4.tar.gz , unpacking it and then running `sudo python setup.py  install` which worked.
