### ISSUE TITLE
Test failing randomly on MacOSX

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#249]
I am implementing travis to testing python 2.7, 3.3, 3.4 on both Linux and MacOSX see #248 

And there testing of `transofrmations + priors` 
https://github.com/SheffieldML/GPy/blob/master/GPy/testing/rv_transformation_tests.py
fails randomly on different platforms:

Compare branch travis testing on travis: 
https://travis-ci.org/SheffieldML/GPy/builds/80021492
https://travis-ci.org/SheffieldML/GPy/builds/80021500
https://travis-ci.org/SheffieldML/GPy/builds/80067531
https://travis-ci.org/SheffieldML/GPy/builds/80067538

**Comment by mzwiessele** [comment]
And if it fails it fails exactly the same:
https://travis-ci.org/SheffieldML/GPy/jobs/80067539
https://travis-ci.org/SheffieldML/GPy/jobs/80067533

What is this trickery?

**Comment by mzwiessele** [comment]
!TRICKERY!

**Comment by alansaul** [comment]
Wew crazy, what could that be?! Another platform specific log1p problem @mikecroucher ?

**Comment by mzwiessele** [comment]
@jameshensman in commit 01b501e078a2647c1c28dfd2e37107d57f1cd89b you added the log jacobian to the priors and I am not sure why you did that. This is the commit, which makes the gradient check mentioned here fail. There seems to be something wrong with the correction.

**Comment by mzwiessele** [comment]
Skipping the gradient tests for now, the rest of the failing tests are fixed by #262.
