### ISSUE TITLE
Wrapper for SVI GP

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#254]
With automatic batch selection?

Along the lines of SparseGP.

**Comment by alansaul** [comment]
At the moment we do mini batches by just randomising and slicing up the data. Once a run through all the data has been completed, we randomise and repeat. How does the SparseGP stochastics work? Are you suggesting doing inference for each output separately (with shared model parameters) or something so we can deal with missing output values?

**Comment by mzwiessele** [comment]
Do we have an easy wrapper like model.SparseGPRegression?

as in model.SVIGPRegression?

**Comment by mzwiessele** [comment]
Any updates? @alansaul

**Comment by alansaul** [comment]
I've whipped something together, but it is a very thin wrapper. I've also integrated Zhenwens Adadelta optimizer, so that now if you have set a batchsize, you can call m.optimize('adadelta') and it will optimize with adadelta with batches.

**Comment by mzwiessele** [comment]
This is great thanks! The tests never check the batch update, though. Is there a mechanic (like method) which selects the new batch and and updates the model accordingly? You know the sparse gp minibatch code, in there the new batches get only selected on a call to do_stochastics on the stochastics object. I updated it to be used in GPy now. This is off for gradient checking and so on, so it works on one batch only until we want to optimize. Optimization goes as follows:
1. optimize gets overriden in SparseGPMinibatch and sets a flag _update_stochastics = True
2. in parameters_changed, we check for stochastics (as the same code handles missing data as well) and then we check if _update_stochastics is True. If so, we call do_stochastics on the stochastics object, which selects a new batch, which we then work on. 
3. in optimize it is a try: finally: block. This allways sets _update_stochastics to False, no matter what happens during optimization.

You can use the great package coverage to test the branching (like if statements) of you implementation.
When installed you can run (from the root dir)

coverage run travis_tests.py
coverage html

which will create a folder htmlcov with the local coverage in html files. In there branching code is highlighted in yellow, if it is not fully covered. The goal of this is to write tests once, and it fully covers the code so that it will not create surprises later on. If code gets run in tests it is a good start, especially if it is difficult to tests correctness, at least the code runs during test time. 

I have added the RProp optimizer to paramz (https://github.com/sods/paramz/pull/6), this can be added to stochastic optimizers, if I'm not mistaken?

**Comment by mzwiessele** [comment]
#323

**Comment by mzwiessele** [comment]
Just waiting for tests to pass and then merging in
