### ISSUE TITLE
Matplotlib testing and codecoverage

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#258]
The matplotlib guys have a testing suite for testing and comparing images created by GPy:

http://matplotlib.org/devel/testing.html

This could be added in a test script for travis.

Additionally we need an extra script `travis_testing.py` for travis to know to use the right backend:

```
#!/usr/bin/env python
import matplotlib 
import nose 
matplotlib.use('agg')

nose.main('GPy.testing')
```

and run this file on travis:

```
script:
  - python travis_testing.py
```

additionally, we can use codecov to produce nice coverage reports and a coverage badge in the readme:

```
before_install:
  - pip install codecov

after_success:
  - codecov
```

We only need to link GPy to the codecov project.

**Comment by alansaul** [comment]
Great idea Max! Good find. I want to set up some integration tests for the
basic GP methods we use that are available in GPStuff and GPML aswell. I'll
take a look in a couple of weeks!

Alan

**Comment by mzwiessele** [comment]
Codecoverage is done and in devel branch

have to look at the cross compilation tomorrow and then 
upload the new patch.
