### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#260]
I got to read the docs and it doesn't work : ( Maybe the script doesnt get run or something?

**Comment by mzwiessele** [comment]
As described in 

http://sphinx-doc.org/markup/toctree.html#special-names

sphinx now cannot create the documentation for our kern._src package anymore, it seems.

What did we do in order to force it to generate the doc anyway?

**Comment by zhenwendai** [comment]
The current documentation does not have any details. One alternative choice would be updated the produced documentation to PyPi, where it can be easily accessed.

**Comment by mzwiessele** [comment]
we can let travis compile the doc and upload it. find a way to get the password to travis securely, so no one can read the password out!
