### ISSUE TITLE
pip install and manual install both fail

### ISSUE THREAD

**Issue by leondz** [SheffieldML/GPy#267]
Hi!

I can't install GPy through either pip or the direct compilation method suggested.

    leon@t430:/tmp/GPy$ pip install GPy
    Collecting GPy
      Downloading GPy-0.8.8.tar.gz (1.2MB)
        100% |████████████████████████████████| 1.2MB 561kB/s 
    Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in /usr/local/lib/python3.4/dist-packages (from GPy)
    Requirement already satisfied (use --upgrade to upgrade): scipy>=0.16 in /usr/local/lib/python3.4/dist-packages (from GPy)
    Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python3.4/dist-packages (from GPy)
    Building wheels for collected packages: GPy
      Running setup.py bdist_wheel for GPy
    ... snip   
      In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                       from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                       from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                       from GPy/kern/_src/stationary_cython.c:242:
      /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       #warning "Using deprecated NumPy API, disable it by " \
        ^
      GPy/kern/_src/stationary_cython.c:244:30: fatal error: stationary_utils.h: No such file or directory
       #include "stationary_utils.h"
                                    ^
      compilation terminated.
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      
      ----------------------------------------
      Failed building wheel for GPy
    Failed to build GPy
    ... snip
        compilation terminated.
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
        
        ----------------------------------------
    Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-oqkulno1/GPy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gnnk4pes-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-oqkulno1/GPy

Building GPy from a checkout, as recommended as an alternative, also fails when it comes to the tests:

    leon@t430:/tmp/GPy$ nosetests3 GPy/testing/
    E
    ======================================================================
    ERROR: Failure: ValueError (numpy.dtype has the wrong size, try recompiling)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/usr/lib/python3/dist-packages/nose/loader.py", line 414, in loadTestsFromName
        addr.filename, addr.module)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/usr/lib/python3.4/imp.py", line 245, in load_module
        return load_package(name, filename)
      File "/usr/lib/python3.4/imp.py", line 217, in load_package
        return methods.load()
      File "<frozen importlib._bootstrap>", line 1220, in load
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/tmp/GPy/GPy/__init__.py", line 6, in <module>
        from . import core
      File "/tmp/GPy/GPy/core/__init__.py", line 4, in <module>
        from .model import *
      File "/tmp/GPy/GPy/core/model.py", line 5, in <module>
        from .. import likelihoods
      File "/tmp/GPy/GPy/likelihoods/__init__.py", line 1, in <module>
        from .bernoulli import Bernoulli
      File "/tmp/GPy/GPy/likelihoods/bernoulli.py", line 5, in <module>
        from ..util.univariate_Gaussian import std_norm_pdf, std_norm_cdf
      File "/tmp/GPy/GPy/util/__init__.py", line 5, in <module>
        from . import linalg
      File "/tmp/GPy/GPy/util/linalg.py", line 15, in <module>
        from . import linalg_cython
      File "__init__.pxd", line 155, in init GPy.util.linalg_cython (GPy/util/linalg_cython.c:4238)
    ValueError: numpy.dtype has the wrong size, try recompiling

    ----------------------------------------------------------------------
    Ran 1 test in 0.001s

    FAILED (errors=1)

any ideas?

**Comment by mzwiessele** [comment]
This might have been my fault, try again pls, as I have updated the pipit project structure.

**Comment by leondz** [comment]
Still failing with:

    leon@t430:/tmp$ sudo pip3 install GPy
    ...
    GPy/kern/_src/stationary_cython.c:244:30: fatal error: stationary_utils.h: No such file or directory
         #include "stationary_utils.h"
                                      ^
        compilation terminated.
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
        
        ----------------------------------------
    Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-uzanhxvn/GPy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-i8mbbxhv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-uzanhxvn/GPy

**Comment by mzwiessele** [comment]
@MikeSmith

You had this problem coming up at some point right?
How did you fix it?

Otherwise, it will be beneficial for you leon if you install the devel branch as follows:

pip install --upgrade https://github.com/SheffieldML/GPy/tarball/devel

This will download the latest version and install it. You can rerun this again to install the newest fixes for the devel branch.

**Comment by leondz** [comment]
Thanks, that pip install line works.

**Comment by bil724** [comment]
```
cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
      cl : Command line warning D9002 : ignoring unknown option '-O3'
      stationary_cython.c
      GPy/kern/src/stationary_cython.c(196): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
      error: command 'E:\\Microsoft Visual Studio\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for GPy
  Running setup.py clean for GPy
Failed to build GPy
ERROR: Could not build wheels for GPy, which is required to install pyproject.toml-based projects
```

I can't pass by this error either way, can somebody help me?
