### ISSUE TITLE
Source builds are shipping binaries

### ISSUE THREAD

**Issue by Dapid** [SheffieldML/GPy#270]
The source distribution includes compiled binaries. One of my systems has an older `libc` version and it is built with a different unicode configuration, so pip install is broken. Also, since the headers (`GPy/kern/_src/stationary_utils.h`) are not included, I need to check out the full repo to build it.

Here are the offending files:

    [david@LCARS GPy-0.8.8]$ find . -name *so
    ./GPy/util/choleskies_cython.so
    ./GPy/util/linalg_cython.so
    ./GPy/kern/_src/coregionalize_cython.so
    ./GPy/kern/_src/stationary_cython.so

MANIFEST.in includes the line `recursive-include GPy *.so`, but lacks `recursive-include GPy *.h`.

**Comment by Dapid** [comment]
I believe https://github.com/SheffieldML/GPy/pull/280 closes this. Thanks, Max!

**Comment by mzwiessele** [comment]
Thanks for the reminder Dapid, forgot to close the issue : )

**Comment by Dapid** [comment]
A comment: this bug prevents GPy from being installed on Python3 directly from pypi. In case someone comes complaining (as I almost did).
