### ISSUE TITLE
Predict function dies with "'NoneType' object has no attribute '__getitem__' " in GPHeteroscedasticRegression

### ISSUE THREAD

**Issue by aginika** [SheffieldML/GPy#277]
When I try to use GPRegression as below, it works.
```python
import GPy
import numpy as np
x = [[0],[1],[2],[3]]
y = [[3.5],[-2.3],[5.3],[0.3]]
m = GPy.models.GPRegression(np.array(x), np.array(y))
m.predict(np.array([[0.3]]))
```

But when I tried to use with GPHeteroscedasticRegression, it will dies with the error "'NoneType' object has no attribute '__getitem__' ".
```python
import GPy
import numpy as np
x = [[0],[1],[2],[3]]
y = [[3.5],[-2.3],[5.3],[0.3]]
m = GPy.models.GPHeteroscedasticRegression(np.array(x), np.array(y))
m.predict(np.array([[0.3]]))
```

Is my program wrong?
Error detail is below
```
$ python test.py 
warning in stationary: failed to import cython module: falling back to numpy
(array([[ 0.83570718]]), array([[ 1.40891673]]))
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    print m.predict(np.array([[0.3]]))
  File "~/SheffieldML/GPy/core/gp.py", line 272, in predict
    mean, var = self.likelihood.predictive_values(mu, var, full_cov, Y_metadata=Y_metadata)
  File "~/SheffieldML/GPy/likelihoods/gaussian.py", line 347, in predictive_values
    _s = self.variance[Y_metadata['output_index'].flatten()]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by ric70x7** [comment]
To make predictions with the heteroscedastic model you would need to decide which noise term to use. At the moment there is no implementation to interpolate the noise at new input locations.
For the set of inputs you want to predict, you would need to pass a Y_metadata dictionary with an index that maps the observations with the noise terms. For example if you wanted to use the first noise term, you would have to do something like this:
m.predict(np.array([[0.3]]),Y_metadata={'output_index':np.zeros((1,1))[:,None].astype(int)})

**Comment by aginika** [comment]
@ric70x7 
Thank you so much! I understood.
I hope it will be implemented before long.

**Comment by lionfish0** [comment]
(for anyone who comes across this thread)
It might be that you want to predict the latent function rather than the observation's distribution.
(quoting Max):
see predict_noiseless, or predict(Xnew, include_likelihood=False), the former is a shortcut for the latter.
This (presumably) won't need to have a noise term chosen.

Note that these new methods were introduced in March 2016, so weren't available when you raised the issue.
