### ISSUE TITLE
Running GPy on Python > 3

### ISSUE THREAD

**Issue by finmod** [SheffieldML/GPy#278]
I have been struggling for months on trying to run the set of Sheffield notebooks on python 3 in both Windows 10 and linux/ubuntu to no avail. Let me share the following points: 
- GPy-master does not install on both OS because it is not fully converted to python 3. See setup file<py3. In addition, scipy 0.16.1 for weave and matplotlib 1.5.0 do not install on anaconda 2.4.0 (python 3.5) on windows and the former only on ubuntu;
- GPy-devel installs only partially in ubuntu. A lot of problems with plotting using matplotlib 1.5.0 and many folders are different with respect to GPy-master. the conversion from python 2 to 3 of the folders is inconsistent and incomplete;
- the conversion from python 2 to 3 should be automatic for the complete GPy project. This can be achieved with the 2to3 command i.e. !2to3 -n -w myfile.py or inserted in the setup file when using pip install and upgrade as suggested here: http://stackoverflow.com/questions/14501502/is-there-a-way-to-run-2to3-with-pip-install. The list of fixers is exhaustive. This would confer a true compatibility with Python3 to GPy-master that does not exist at present.
- the collection of GPy notebooks should be revised in this light to run spotlessly on both Python 2 and 3. This implies that the plotting folder of GPy should probably be harmonized to the accepted good standard of matplotlib 1.5.0;
- GPy/Anaconda should be advocated for both windows and linux for a consistent distribution.

My goal was to run deepGPy ASAP and the outcome appears dimmer by the day!

**Comment by mzwiessele** [comment]
Have you tried to use the devel branch of GPy?

**Comment by finmod** [comment]
In this issue, I am reporting on both GPy-devel and GPy-master in two OS: Windows 10 and Ubuntu 15.04. 

As mentioned below, in GPy-devel Python 3 is inconsistent from file to file and folder to folder. Then when a notebook calls a different file or folder, the issues #277, #276, #272 and other persistent warnings arise.

**Comment by mzwiessele** [comment]
The inconsistencies arrived through big structural changes. It was necessary, exactly for the reasons you are mentioning. Unifying the plotting, pulling the paramz package out and and and. We are working on the new master branch, so that it conforms with devel and we'll go from there.

**Comment by finmod** [comment]
Is the new GPy-devel expected to be python 2 and 3 compliant or not? The conversion from to 2 3 using “2to3” can then be applied at the Gpy project level or at the .py level. The conversion at the file level, which I have done several times recently, has produced incompletely converted folders (inference, util, model etc) and the next big step is using a suite of testing notebook, specifically your “notebook-master” to prove that it works. Let me know if and where I can help.

**Comment by mzwiessele** [comment]
The devel branch is as far as I can tell both python 2 and 3 compliant. The travis tests run on python versions
- 2.7
- 3.3
- 3.4
- 3.5

And the tests pass all nicely. Including plotting.

**Comment by finmod** [comment]
In this user group, I do not see much actual testing of GPy-devel and the notebooks in python 3. Users of canopy cannot be testing python 3 as it is not on offer. In testing GPy-devel 0.9 with paramz, the coregionalized  notebook throws the following error:

In [8]:

K = GPy.kern.Matern32(1)
icm = GPy.util.multioutput.ICM(input_dim=1,num_outputs=2,kernel=K)
​
m = GPy.models.GPCoregionalizedRegression([X1,X2],[Y1,Y2],kernel=icm)
m['.*Mat32.var'].constrain_fixed(1.) #For this kernel, B.kappa encodes the variance now.
m.optimize()
print (m)
plot_2outputs(m,xlim=(0,100),ylim=(-20,60))

Name : gp
Objective : 367.2950289887061
Number of Parameters : 8
Number of Optimization Parameters : 7
Updates : True
Parameters:
  gp.                                    |           value  |  constraints  |  priors
  ICM.Mat32.variance                     |             1.0  |   +ve fixed   |  
  ICM.Mat32.lengthscale                  |   225.921627546  |      +ve      |  
  ICM.B.W                                |          (2, 1)  |               |  
  ICM.B.kappa                            |            (2,)  |      +ve      |  
  mixed_noise.Gaussian_noise_0.variance  |  0.245511876346  |      +ve      |        

##   mixed_noise.Gaussian_noise_1.variance  |   5.26288548219  |      +ve      |        

AttributeError                            Traceback (most recent call last)
<ipython-input-8-c119aa301b59> in <module>()
      6 m.optimize()
      7 print (m)
----> 8 plot_2outputs(m,xlim=(0,100),ylim=(-20,60))

<ipython-input-4-027842743d2e> in plot_2outputs(m, xlim, ylim)
      5     ax1.set_xlim(xlim)
      6     ax1.set_title('Output 1')
----> 7     m.plot(plot_limits=xlim,fixed_inputs=[(1,0)],which_data_rows=slice(0,100),ax=ax1)
      8     ax1.plot(Xt1[:,:1],Yt1,'rx',mew=1.5)
      9     #Output 2

C:\Users\Denis\Anaconda3\lib\site-packages\GPy\plotting\gpy_plot\gp_plots.py in plot(self, plot_limits, fixed_inputs, resolution, plot_raw, apply_link, which_data_ycols, which_data_rows, visible_dims, levels, samples, samples_likelihood, lower, upper, plot_data, plot_inducing, plot_density, predict_kw, projection, legend, *_kwargs)
    320     :param bool legend: convenience, whether to put a legend on the plot or not.
    321     """
--> 322     canvas, _ = pl().new_canvas(projection=projection, *_kwargs)
    323     X = get_x_y_var(self)[0]
    324     helper_data = helper_for_plot_data(self, X, plot_limits, visible_dims, fixed_inputs, resolution)

AttributeError: 'NoneType' object has no attribute 'new_canvas'

This bug extends to many other GPy notebooks. My config is:

Software    Version
Python  3.5.0 64bit [MSC v.1900 64 bit (AMD64)]
IPython 4.0.0
OS  Windows 10.0.10586
conda   3.18.6
GPy 0.9.0
matplotlib  1.5.0
numpy   1.10.1
scipy   0.16.0
pandas  0.17.1
cython  0.23.4
Mon Nov 30 11:08:21 2015 W. Europe Standard Time

**Comment by mzwiessele** [comment]
Hi fin,

Could you check what you get when you run:

$ GPy.util.config.config.get('plotting', 'library’)

This should print ‘matplotlib’. Otherwise your configuration file has not been updated. This should have been done by running the setup again, i.e:

$ python setup.py develop

In your case most probably.

**Comment by Dapid** [comment]
On 30 November 2015 at 11:15, Max Zwiessele notifications@github.com
wrote:

> $ python setup.py develop

A warning: this usually works, but sometimes distutils/setuptools opens a
whole can of worms here, specially when compiled extensions are involved.
If that is the case, it is best to clean the repo and reinstall.

**Comment by mzwiessele** [comment]
Oh is that true? Sry didn’t know about that. Updating readme

**Comment by Dapid** [comment]
I read it in the numpy mailing list. It sometimes works, and then it is
convenient, but not always.

**Comment by finmod** [comment]
No change. My .config folder with user.cfg had been untouched by recent remove and pip install of Gpy-devel. Now, all installation.cfg and user.cfg are: 

---

[parallel]

# Enable openmp support. This speeds up some computations, depending on the number

# of cores available. Setting up a compiler with openmp support can be difficult on

# some platforms, hence by default it is off.

openmp = False # True

[datasets]

# location for the local data cache

dir=$HOME/Finmod/GPy-devel/datasets/ # Any other path you choose

[cython]

working = True # False

[plotting]

library = matplotlib # plotly

Still “None Type”

**Comment by mzwiessele** [comment]
This is getting mysterious. The travis tests are testing the plotting and it works nicely.
Is it only the one plot, which is not working? Or is it any plotting whatsoever?

**Comment by finmod** [comment]
The .config direction does not appear to be relevant since ln[1} sets up systematically:

%matplotlib inline

import matplotlib

import matplotlib.pyplot as plt

import numpy as np

import Gpy

and clearly says that matplotlib is the only package in use.

Then everything is fine until ln[7] including the graphs at ln[3]. The bug appears with the setting-up and use of “plot_2outputs” in ln[4] and continues for every plot until the end of the notebook. See the debug report in my first post. Probably a syntax problem with matplotlib 0.15.0py35.

**Comment by finmod** [comment]
Success. 

After upgrading Gpy-devel to 0.9.3 and checking all installation.cfg and user.cfg for accuracy, the coregionalized regression ipynb runs as intended.

**Comment by finmod** [comment]
Before you start celebrating the success just achieved on running coregionalized regression, here is another bug in “heteroscedastic” ipynb, my configuration throws the following error:

m = GPy.models.GPHeteroscedasticRegression(X[:,None],Y[:,None],kern)

m['.*Gaussian_noise'] = abs(error)#.flatten() #Set the noise parameters to the error in Y

m.likelihood['Gaussian_n.*'].unconstrain()

m.likelihood['Gaussian_n.*'].fix() #We can fix the noise term, since we already know it

m.optimize()

fig,ax = plt.subplots(1)

m.plot_f(ax=ax) #Show the predictive values of the GP.

ax.errorbar(X,Y,yerr=np.array(m.likelihood.flattened_parameters).flatten(),fmt=None,ecolor='r',zorder=1)

ax.grid()

ax.plot(X,Y,'kx',mew=1.5)

---

AttributeError                            Traceback (most recent call last)

<ipython-input-5-a087f73b6db5> in <module>()

```
  1 m = GPy.models.GPHeteroscedasticRegression(X[:,None],Y[:,None],kern)
```

----> 2 m['.*Gaussian_noise'] = abs(error)#.flatten() #Set the noise parameters to the error in Y

```
  3 m.likelihood['Gaussian_n.*'].unconstrain()

  4 m.likelihood['Gaussian_n.*'].fix() #We can fix the noise term, since we already know it

  5 m.optimize()
```

C:\Users\Denis\Anaconda3\lib\site-packages\paramz\parameterized.py in **setitem**(self, name, value, paramlist)

```
332             self.trigger_update()

333         else:
```

--> 334             param = self.**getitem**(name, paramlist)

```
335             param[:] = value

336 
```

C:\Users\Denis\Anaconda3\lib\site-packages\paramz\parameterized.py in **getitem**(self, name, paramlist)

```
313             if paramlist is None:

314                 paramlist = self.grep_param_names(name)
```

--> 315             if len(paramlist) < 1: raise AttributeError(name)

```
316             if len(paramlist) == 1:

317                 #if isinstance(paramlist[-1], Parameterized) and paramlist[-1].size > 0:
```

AttributeError: .*Gaussian_noise

Should be quite simple to fix.

**Comment by finmod** [comment]
Hello Max,

Thank you for the upgrade of Gpy to 0.9.3 and the corresponding adjustment of notebooks in the GPy folder. This is moving now.

For my configuration of a x64 machine with Windows 10 and latest Anaconda3 (2.4.0 November 3, 2015), let me report the following:

1)      A systematic conversion of import calls at the beginning of each notebook to:

%matplotlib inline

Import matplot

Import matplotlib.pyplot as plt

Import numpy as np

2)      The following notebooks are running fine: “ParametricNonparametricInference”; “Poisson regression”; “basic kernel”; “coregionalized” and “sparse”.

3)      In “Sampling” it has to be completely converted to matplotlib.pyplot as plt

4)      In “model.basic” at ln[7] print (‘allvariances:\n”, m[‘,*var’]) there is a “list index out of range” in param.py at line 505

5)      In “basic classification”, all the import…rcParameters at the beginning are superfluous. Comment them out.

6)      In “hetesoscedastic”, should be fmt=”None” instead of fmt=None. In the hetero and homo plotting of ln[9], there is no noticeable difference in the graphs. It seems that the same graph is printed twice;

7)      In “MagnificationFactor”, there are some plot_inducing=True are unknown; In latent space magnification “the total size of new array must be unchanged”;

8)      In “SVI”, ln[4} “generator” object has no attribute ‘next’;

9)      In “basic_gp” at ln[15] Gpy.plotting.show gives –init—() got an unexpected keyword;

With respect to the folder “classes” the subfolder gprs runs fine everywhere whereas the subfolder gpss is full of bugs. Gprs may be best and enough.

The smooth folder of GPY notebooks running on Windows, Python 3.5 and Ananconda could be made available to you when complete.

**Comment by mzwiessele** [comment]
I think we fixed everything now with the current devel branch and notebooks.

An updated release will follow soon, so that we finally get on one base again : )

**Comment by jorgeloaiza** [comment]
Hello.
¿How can i update GPy on python 3.6.2. Anaconda Custom (64 bits)?
Thanks
