### ISSUE TITLE
One vs all

### ISSUE THREAD

**Issue by alansaul** [SheffieldML/GPy#287]
models/one_vs_all_classification.py appears to be unfinished (has a stop in it) is there a reason for this? Should have a test at least for in the future.

Would also be nice to have a multi-class implementation of Laplace or EP.

**Comment by mzwiessele** [comment]
We talked about this, there is two possibilities:
1. We delete the module, which would be my choice, explanation below.
2. We fix the module and provide with it a higher order functionality, which should be implemented by the user in my honest opinion. One vs All classification is a very crude way of doing classification and users might be mislead by results being not as expected.
