### ISSUE TITLE
How to use GPy as a dependency?

### ISSUE THREAD

**Issue by vote539** [SheffieldML/GPy#288]
I'm working on a project in which I would like to be able to call GPy as a dependency.

One of the issues I've been running into is that whenever I try to "import GPy", it prints a bunch of GTK errors to the console.  I've been able to make most of those errors go away by changing my own copy of "default.cfg", but I can't expect users of my project to go in and manually change their GPy settings.

Ultimately, I need to perform GP prediction and optimization.  I do not need the plotting functionality for the purposes of the released project (although that is very handy for debugging).

Any suggestions?

**Comment by mzwiessele** [comment]
We are still working on the next stable release of GPy, which will be installable from every machine. If you want to see of how to use it as a library, you could have a look at 

https://github.com/mzwiessele/applygpy

Where GPy is a dependency and it is stable for other people to install.
