### ISSUE TITLE
Add/Sum of kernels in Coregionalize

### ISSUE THREAD

**Issue by finmod** [SheffieldML/GPy#289]
With this configuration
Software    Version
Python  2.7.11 64bit [MSC v.1500 64 bit (AMD64)]
IPython 4.0.1
OS  Windows 10 10.0.10586
conda   The 'conda' distribution was not found and is required by the application
numpy   1.10.1
scipy   0.16.0
matplotlib  1.5.0
sympy   0.7.6.1
GPY 0.9.4
pods    0.0.2a0
version_information 1.0.3
Mon Jan 04 11:14:57 2016 W. Europe Standard Time

and running the gprs/multiple outputs.ipynb of notebook, ln[22] model.add.mul_1.coregion_1.W throws the following error

AttributeError                            Traceback (most recent call last)
<ipython-input-22-0a643130b08b> in <module>()
----> 1 model.add.mul_1.coregion_1.W

AttributeError: 'GPRegression' object has no attribute 'add'

There is no answer in the docstring on the syntax for "add".

**Comment by finmod** [comment]
Any chance of closing this issue as efficiently as #290?

**Comment by mzwiessele** [comment]
fixed
