### ISSUE TITLE
ODE_st in SpatioTemporalGeneProteinDrosophila no attribute 'add_parameters'

### ISSUE THREAD

**Issue by finmod** [SheffieldML/GPy#290]
With this configuration
Software    Version
Python  2.7.11 64bit [MSC v.1500 64 bit (AMD64)]
IPython 4.0.1
OS  Windows 10 10.0.10586
conda   The 'conda' distribution was not found and is required by the application
numpy   1.10.1
scipy   0.16.0
matplotlib  1.5.0
pandas  0.17.1
GPY 0.9.4
pods    0.0.2a0
version_information 1.0.3
Mon Jan 04 21:49:13 2016 W. Europe Standard Time

and running the compbio/SpatioTemporalGeneProteinDrosophila.ipynb notebook, ln[4]  
kern = GPy.kern.ODE_st(input_dim=3,
                       a=1., b=1., c=1.,
                       variance_Yx=1., variance_Yt=1.,
                       lengthscale_Yx=15.,
                       lengthscale_Yt=15.) 

throws the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-22bb2b502b6d> in <module>()
      9                        variance_Yx=1., variance_Yt=1.,
     10                        lengthscale_Yx=15.,
---> 11                        lengthscale_Yt=15.) 

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\paramz\parameterized.pyc in **call**(self, _args, *_kw)
     46         self._in_init_ = True
     47         #import ipdb;ipdb.set_trace()
---> 48         self = super(ParametersChangedMeta, self).**call**(_args, *_kw)
     49         #logger.debug("finished init")
     50         self._in_init_ = False

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\GPy\kern\src\ODE_st.pyc in **init**(self, input_dim, a, b, c, variance_Yx, variance_Yt, lengthscale_Yx, lengthscale_Yt, active_dims, name)
     39         self.c = Param('c', c, Logexp())
     40 
---> 41         self.add_parameters(self.a, self.b, self.c, self.variance_Yt, self.variance_Yx, self.lengthscale_Yt,self.lengthscale_Yx)
     42 
     43 

AttributeError: 'ODE_st' object has no attribute 'add_parameters'

**Comment by lawrennd** [comment]
@cdguarnizo  would you be able to take a look at this?

**Comment by cdguarnizo** [comment]
Sure, I'm going to look what is going on with add_parameters attribute.

2016-01-05 3:30 GMT-05:00 Neil Lawrence notifications@github.com:

> @cdguarnizo https://github.com/cdguarnizo would you be able to take a
> look at this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SheffieldML/GPy/issues/290#issuecomment-168933807.

## 

M. Sc. Cristian Guarnizo L.
Ing. Electricista

**Comment by lawrennd** [comment]
Thanks!

**Comment by finmod** [comment]
Solved. Thank you.
