### ISSUE TITLE
GPy-devel Py3 install and pip install --upgrade in latest commit

### ISSUE THREAD

**Issue by finmod** [SheffieldML/GPy#291]
One step forward and two steps back....
With this latest commit, GPy-devel does not install successfully with python 3 (anaconda3 2.4.1 and python 3.5 now standard). It was ok previously and it is ok in python 2.7. 

The following error arises

ImportError                               Traceback (most recent call last)
<ipython-input-2-d0b8880e43e4> in <module>()
      8 #import matplotlib;matplotlib.rcParams['font.family'] = 'serif'
      9 import numpy as np
---> 10 import GPy
     11 np.random.seed(1)

C:\Users\Denis\Anaconda3\lib\site-packages\GPy__init__.py in <module>()
      4 warnings.filterwarnings("ignore", category=DeprecationWarning)
      5 
----> 6 from . import core
      7 from . import models
      8 from . import mappings

C:\Users\Denis\Anaconda3\lib\site-packages\GPy\core__init__.py in <module>()
      2 # Licensed under the BSD 3-clause license (see LICENSE.txt)
      3 
----> 4 from GPy.core.model import Model
      5 from .parameterization import Param, Parameterized
      6 from . import parameterization

C:\Users\Denis\Anaconda3\lib\site-packages\GPy\core\model.py in <module>()
      1 # Copyright (c) 2012-2014, GPy authors (see AUTHORS.txt).
      2 # Licensed under the BSD 3-clause license (see LICENSE.txt)
----> 3 from .parameterization.priorizable import Priorizable
      4 from paramz import Model as ParamzModel
      5 

C:\Users\Denis\Anaconda3\lib\site-packages\GPy\core\parameterization__init__.py in <module>()
      2 # Licensed under the BSD 3-clause license (see LICENSE.txt)
      3 
----> 4 from .param import Param
      5 from .parameterized import Parameterized
      6 from paramz import transformations

C:\Users\Denis\Anaconda3\lib\site-packages\GPy\core\parameterization\param.py in <module>()
      2 # Licensed under the BSD 3-clause license (see LICENSE.txt)
      3 
----> 4 from paramz import Param
      5 from .priorizable import Priorizable
      6 from paramz.transformations import **fixed**

C:\Users\Denis\Anaconda3\lib\site-packages\paramz__init__.py in <module>()
     31 #===============================================================================
     32 
---> 33 from .model import Model
     34 from .parameterized import Parameterized
     35 from .param import Param

C:\Users\Denis\Anaconda3\lib\site-packages\paramz\model.py in <module>()
     36 from numpy.linalg.linalg import LinAlgError
     37 
---> 38 from . import optimization
     39 from .parameterized import Parameterized
     40 from .optimization.verbose_optimization import VerboseOptimization

C:\Users\Denis\Anaconda3\lib\site-packages\paramz\optimization__init__.py in <module>()
     31 #===============================================================================
     32 
---> 33 from .optimization import *
     34 from . import verbose_optimization, stochastics

C:\Users\Denis\Anaconda3\lib\site-packages\paramz\optimization\optimization.py in <module>()
      3 
      4 import datetime as dt
----> 5 from scipy import optimize
      6 from warnings import warn
      7 

C:\Users\Denis\Anaconda3\lib\site-packages\scipy\optimize__init__.py in <module>()
    219 from **future** import division, print_function, absolute_import
    220 
--> 221 from .optimize import *
    222 from ._minimize import *
    223 from ._root import *

C:\Users\Denis\Anaconda3\lib\site-packages\scipy\optimize\optimize.py in <module>()
     35                    vectorize, asarray, sqrt, Inf, asfarray, isinf)
     36 import numpy as np
---> 37 from .linesearch import (line_search_wolfe1, line_search_wolfe2,
     38                          line_search_wolfe2 as line_search,
     39                          LineSearchWarning)

C:\Users\Denis\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py in <module>()
     16 from warnings import warn
     17 
---> 18 from scipy.optimize import minpack2
     19 import numpy as np
     20 from scipy._lib.six import xrange

ImportError: DLL load failed: The specified module could not be found.

Also in Anaconda, the pip install --upgrade https.... has disastrous effects where the scipy --upgrade conflict with native scipy installed even though it is the latest version. The only way to install properly is by doing pip uninstall GPy followed by pip install GPy-devel and forget any --upgrade which destroys everything in both python 2 and 3.

**Comment by Dapid** [comment]
The problem is in your Anaconda + Scipy, not GPy. Somewhere, your packages
got messed up and a DLL can't be found. You would get the same if you try
to run `from scipy import optimize`

Are you using the latest conda version, or have you upgraded it outside of
the official channels?

**Comment by finmod** [comment]
Anaconda already has Scipy to the latest version (scipi 0.16.0 np110py35_0). When GPy-devel (0.9.5) was installed with pip install –upgrade …, the set up fouled the native scipy by uninstalling and re-installing a scipy which it did not have to touch since it is already > than 0.15

In python 2.7, scipy is 0.16.0 np110py27_0 and doing fine.

**Comment by Dapid** [comment]
I see. `pip - -upgrade` by default upgrades all the dependencies, there is
nothing GPy can do.

The easiest way is to `pip uninstall GPy` and `pip install ...` from
source.

**Comment by finmod** [comment]
Let me say first that GPy-devel 0.9.4 was installing well on both python 2 and python 3 (Anaconda3) until yesterday when I tried to install GPy-devel 0.9.5. This should be obvious enough that the problem is with GPY-devel 0.9.5.

With the pip install, uninstall, --upgrade the command is:

!pip install  https://github.com/SheffieldML/GPy/archive/devel.zip https://github.com/SheffieldML/GPy/archive/devel.zip

The answer is:

Collecting  https://github.com/SheffieldML/GPy/archive/devel.zip https://github.com/SheffieldML/GPy/archive/devel.zip

  Downloading  https://github.com/SheffieldML/GPy/archive/devel.zip https://github.com/SheffieldML/GPy/archive/devel.zip

Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in c:\users\denis\anaconda3\envs\py27\lib\site-packages (from GPy==0.9.5)

Requirement already satisfied (use --upgrade to upgrade): scipy>=0.16 in c:\users\denis\anaconda3\envs\py27\lib\site-packages (from GPy==0.9.5)

Requirement already satisfied (use --upgrade to upgrade): six in c:\users\denis\anaconda3\envs\py27\lib\site-packages (from GPy==0.9.5)

Requirement already satisfied (use --upgrade to upgrade): paramz in c:\users\denis\anaconda3\envs\py27\lib\site-packages (from GPy==0.9.5)

Installing collected packages: GPy

  Found existing installation: GPy 0.9.4

```
Uninstalling GPy-0.9.4:

  Successfully uninstalled GPy-0.9.4
```

  Running setup.py install for GPy

Successfully installed GPy-0.9.5

Then on running any notebook like:

#configure plotting

%matplotlib inline

%config InlineBackend.figure_format = 'svg'

import matplotlib;matplotlib.rcParams['figure.figsize'] = (8,5)

import matplotlib;matplotlib.rcParams['text.usetex'] = True

import matplotlib;matplotlib.rcParams['font.size'] = 16

import matplotlib;matplotlib.rcParams['font.family'] = 'serif'

import GPy

import numpy as np

from matplotlib import pyplot as plt

np.random.seed(1)

---

ImportError                               Traceback (most recent call last)

<ipython-input-1-95921d8afe2e> in <module>()

```
  6 import matplotlib;matplotlib.rcParams['font.size'] = 16

  7 import matplotlib;matplotlib.rcParams['font.family'] = 'serif'
```

----> 8 import GPy

```
  9 import numpy as np

 10 from matplotlib import pyplot as plt
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\GPy__init__.py in <module>()

```
  4 warnings.filterwarnings("ignore", category=DeprecationWarning)

  5 
```

----> 6 from . import core

```
  7 from . import models

  8 from . import mappings
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\GPy\core__init__.py in <module>()

```
  2 # Licensed under the BSD 3-clause license (see LICENSE.txt)

  3 
```

----> 4 from GPy.core.model import Model

```
  5 from .parameterization import Param, Parameterized

  6 from . import parameterization
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\GPy\core\model.py in <module>()

```
  1 # Copyright (c) 2012-2014, GPy authors (see AUTHORS.txt).

  2 # Licensed under the BSD 3-clause license (see LICENSE.txt)
```

----> 3 from .parameterization.priorizable import Priorizable

```
  4 from paramz import Model as ParamzModel

  5 
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\GPy\core\parameterization__init__.py in <module>()

```
  2 # Licensed under the BSD 3-clause license (see LICENSE.txt)

  3 
```

----> 4 from .param import Param

```
  5 from .parameterized import Parameterized

  6 from paramz import transformations
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\GPy\core\parameterization\param.py in <module>()

```
  2 # Licensed under the BSD 3-clause license (see LICENSE.txt)

  3 
```

----> 4 from paramz import Param

```
  5 from .priorizable import Priorizable

  6 from paramz.transformations import __fixed__
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\paramz__init__.py in <module>()

```
 31 #===============================================================================

 32 
```

---> 33 from .model import Model

```
 34 from .parameterized import Parameterized

 35 from .param import Param
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\paramz\model.py in <module>()

```
 36 from numpy.linalg.linalg import LinAlgError

 37 
```

---> 38 from . import optimization

```
 39 from .parameterized import Parameterized

 40 from .optimization.verbose_optimization import VerboseOptimization
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\paramz\optimization__init__.py in <module>()

```
 31 #===============================================================================

 32 
```

---> 33 from .optimization import *

```
 34 from . import verbose_optimization, stochastics
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\paramz\optimization\optimization.py in <module>()

```
  3 

  4 import datetime as dt
```

----> 5 from scipy import optimize

```
  6 from warnings import warn

  7 
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\scipy\optimize__init__.py in <module>()

```
219 from __future__ import division, print_function, absolute_import

220 
```

--> 221 from .optimize import *

```
222 from ._minimize import *

223 from ._root import *
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\scipy\optimize\optimize.py in <module>()

```
 35                    vectorize, asarray, sqrt, Inf, asfarray, isinf)

 36 import numpy as np
```

---> 37 from .linesearch import (line_search_wolfe1, line_search_wolfe2,

```
 38                          line_search_wolfe2 as line_search,

 39                          LineSearchWarning)
```

C:\Users\Denis\Anaconda3\envs\py27\lib\site-packages\scipy\optimize\linesearch.py in <module>()

```
 16 from warnings import warn

 17 
```

---> 18 from scipy.optimize import minpack2

```
 19 import numpy as np

 20 from scipy._lib.six import xrange
```

ImportError: DLL load failed: The specified module could not be found.

In addition when using the upgrade option, an upgrade of paramz tries to install scipy 0.16.1, fails and rollback. Now paramz (0.1.0) was perfectly ok with scipy 0.16.0 in both py2 and py3 with GPy-devel 0.9.4.

The net results is that I no longer have a running GPY-devel version in any form.
