### ISSUE TITLE
Initialisation of hyperparameters/optimization with GPyOpt

### ISSUE THREAD

**Issue by alansaul** [SheffieldML/GPy#292]
We would like to make the 'random' initialisation more intelligent, and one suggested method is to try initialising with a latin hypercube, or to use GPyOpt within GPy for initialisation. It will create a circular dependency that would need to be resolved.

Heuristics will live within the util. We would like to do m.heuristic_init() or or m.bayesian_init() or something similar rather than m.randomize(), need to be able to integrate over hyper-parameters of the surrogate model.

**Comment by mzwiessele** [comment]
yes that should be a thing. @javiergonzalezh do we have a simple runnable script for a very simple Bayesian optimization, which we can include into GPy (circular references prohibit the dependancy on GPyOpt)? This would be really nice, also some code for the grid initialization would be helpful (you said there is a way of optimally placing points on a grid to fill the space), so we can start implementing the initialization code and ship it with the next GPy.

**Comment by ekalosak** [comment]
Stale, GPyOpt is deprecated. Users should look to Emukit.
