### ISSUE TITLE
priors 

### ISSUE THREAD

**Issue by piyushpandita92** [SheffieldML/GPy#293]
I was trying to call GPy.priors.Jeffreys() in one of my own subroutines after cloning GPy from here. But it seems as if the Jeffreys prior has been removed from GPy.priors as i get an error saying 
"'module' object has no attribute 'Jeffreys'".
Is this an issue at my end , if not then how can i get the version of GPy with the Jeffreys prior ?

**Comment by alansaul** [comment]
We are looking into this, but couldn't find any reference GPy.priors.Jeffreys() in the history of GPy, can you let us know what version it existed in so we can look into this?

**Comment by piyushpandita92** [comment]
Hi 

I looked at it and I found it to be present in another branch namely the pymc branch.
So I copied it from that branch on my machine for future use.

Regards
Piyush

Sent from my Cyanogen phone

On Mar 7, 2016 11:24 AM, Alan Saul notifications@github.com wrote:

We are looking into this, but couldn't find any reference GPy.priors.Jeffreys() in the history of GPy, can you let us know what version it existed in so we can look into this?

**Comment by mzwiessele** [comment]
If you want, you could put in a pull request towards the **devel** branch with the prior added and we can pull it in. closing for now.
