### ISSUE TITLE
2D regression m.plot() - contour lines don't reproduce the model fit?

### ISSUE THREAD

**Issue by elkeschaper** [SheffieldML/GPy#295]
Dear GPiers,
first of all congrats and thanks for a great software package! 

It seems that in some very basic 2D regression cases, the contour lines shown in the m.plot() function 
are off. Attached you'll find a .ipynb, .html, and a .pdf with several examples.

Here just one example: Sinusoidal data 15:20, contour lines seem off:
![sinus_contour_lines_off](https://cloud.githubusercontent.com/assets/5979427/12482648/13624b14-c051-11e5-8e20-97eb4960a411.png)

Here just one example: Sinusoidal data 15:30, contour lines seem ok.:
![sinus_contour_lines_on](https://cloud.githubusercontent.com/assets/5979427/12482647/1093becc-c051-11e5-8bd3-0f0296a0dd20.png)

Any feedback to help me understand what's happening here / advice would be great!

Cheers,

Elke

PS:
Using Python 3.5.0; Tested both the lastest GPy Pypi release 0.9.1, and the current develop 0.9.5 on commit 1bda209.

[2d_regression_test.zip](https://github.com/SheffieldML/GPy/files/99214/2d_regression_test.zip)

**Comment by elkeschaper** [comment]
I should add that the 2D GPy regression code was inspired by: 
http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/basic_gp.ipynb

**Comment by mzwiessele** [comment]
There is clearly something wrong with the contour plot, you are right, see here in 3d:
https://plot.ly/672/~maxz/

**Comment by mzwiessele** [comment]
could you try it again, i think 7d7399f846e7982511a1dd02f8ae772ff4e880be should have fixed it?
