### ISSUE TITLE
Confidence intervals on kernel hyperparameters

### ISSUE THREAD

**Issue by doccosmos** [SheffieldML/GPy#297]
Is there a straightforward way to determine confidence intervals on the kernel hyperparameter values calculated by the optimizer?

**Comment by lawrennd** [comment]
Not currently implanted. But there a few thoughts. Including estimating the
Hessian or ideas from INLA.

@alansaul did you have any thoughts on implementation of some of Aki's
GPstuff ideas in this domain?
