### ISSUE TITLE
Hierarchical covariances notebook

### ISSUE THREAD

**Issue by tmfs10** [SheffieldML/GPy#302]
Hi,

I keep seeing references to the ipython notebook on hierarchical covariances which has sample code using the hierarchical kernel but I can't find that notebook anywhere...

Also would it be possible to get the source code for the paper "Hierarchical Bayesian modelling of gene expression time series across irregularly sampled replicates and clusters"?

Thanks

**Comment by lawrennd** [comment]
Do you mean this one?

https://github.com/jameshensman/GPclust/blob/master/notebooks/MOHGP_demo.ipynb

Neil

**Comment by tmfs10** [comment]
Hmm -- that doesn't seem to allow one to have different samples with different X which all are generated from a hierarchical model with a common mean but sample specific noise.

Is such a thing possible using GPy/GPclust?

**Comment by lawrennd** [comment]
Should be, although @jameshensman is the one with the real expertise there
though, @marahman has also done some work with this model.

Neil

**Comment by juangil** [comment]
@lawrennd  I was working with hierarchical covariances but my interest is not to make clustering but only using  one hierarchical covariance over toy data for  later making inferences about the underlying trend of a noise corrupted sinusoidal signals, there is other reference to only do that?

**Comment by lawrennd** [comment]
I don't recall if we have a specific notebook, but you don't need to use
the mixtures to do this, you should be able to construct the hierarchical
covariance directly. @marahman do you know of a good notebook that just
uses the hierarchical covariance?

**Comment by marahman** [comment]
All the problems we dealt so far were related with clustering, I can't remember any specific notebook where hierarchical covariances were used as expected by @juangil.

**Comment by juangil** [comment]
@lawrennd @marahman Ok thanks anyway, the thing it's that i needed to compare some results i had, i was trying to construct the hierarchical covariance directly with GPy.kern._src.independent_outputs.Hierarchical, and then appyling a GP regression normally as if one were making a multioutput GP regression, but when i was making inference to recover the non corrupted signal i didn't have good results.

**Comment by juangil** [comment]
@lawrennd @marahman Sorry for asking that much, the thing it's that i'm barely new to GP's. In the notebook referenced below i'm working on the simple hierarchical model(no clustering, toy data set) with some kind of detailed explanation, had no good results so far
github repo: https://github.com/juangil/machine_learning_class/blob/master/GP_tests/mocap_test_1/HGP_Tests.ipynb

nbviewer(nicer): 
http://nbviewer.jupyter.org/github/juangil/machine_learning_class/blob/master/GP_tests/mocap_test_1/HGP_Tests.ipynb

**Comment by lawrennd** [comment]
That's a cool example to try and get going. Are you only adding noise to
form the 'child processes' of the parent? Or did I misunderstand?

**Comment by juangil** [comment]
@lawrennd Yes, i'm only adding noise

**Comment by lawrennd** [comment]
I think it gets a bit more interesting if you start adding other functions,
particularly for the toy problem. I'd suggest starting by adding functions
that are smaller in variance than the original.

**Comment by juangil** [comment]
Ok, i will try that for sure, the thing is that with the simpler example i was not getting good results when i tried to predict the parent, my thougt it's that maybe i wasn't using the library properly, or maybe my inference process is bad.
