### ISSUE TITLE
Inducing variables in Stochastic Variational Inference SVGP

### ISSUE THREAD

**Issue by finmod** [SheffieldML/GPy#303]
There is only one notebook example, SVI.ipynb, of stochastic variational inference. In this example, X = input, Y = multiple outputs (2 columns Y1 and Y2) and Z = inducing variables. 

Z = np. random.rand(20,1) where 20 appears to be the batchsize x the number of outputs. Is this correct?

Further down the number of kern.RBF(1) and kern.White(1) appears to be full rank output matrix (2). Is this a necessary condition or low rank approximation can be investigated this way? e.g. an output matrix of rank 20 can be approximated with RBF(5) and White(2)? 

Better docs or tutorial notebook(like UK apartment price or airline delays) for GPy.core.SVGP would help because this is really cryptic.

**Comment by lawrennd** [comment]
Hi finmod,

Yes, we're aware this needs improvement, it's on our to do list, but not
yet in the pipeline. I don't have specific answers to your questions,
@jameshensman might be able to help and @nfusi has made the airline delay
data available in the past, but both are very busy. If you do manage to
disentangle some of it then do please feel free to do a pull requst, we'd
love any contributions!

Neil

**Comment by BrunoQin** [comment]
Hi, I have a question here, Can I use Stochastic Variational Inference with coregionazation model? Can you give me an example or tutorial?
