### ISSUE TITLE
Log-Gaussian Cox Process with fixed spatial terms

### ISSUE THREAD

**Issue by yiyang-gt** [SheffieldML/GPy#305]
Greeting!

I want to use LGCP to model my Spatio-Temporal data, which can be achieved by specifying the Poisson likelihood in GPy. The model looks like this:
y_{s,t} | λ(s, t) ∼ Poisson(exp(f(s, t)))

However, I want to include a spatial term e_s for each location, so the model changes to:
y_{s,t} | λ(s, t) ∼ Poisson(exp(f(s, t)) · e_s). 

I know that I may need to modify some code accordingly, but which files I should focus on specifically and some suggestions on how?

**Comment by mzwiessele** [comment]
@alansaul any suggestions?

**Comment by alansaul** [comment]
Hi Yiyang, I'm just having a think about this. Is e_s to be specified for each location (you know the value already) or do you want a GP to be learnt for it? If the latter, then essentially you can model exp(f(s,t) + log(e(s))), in this case you would have a kernel modelling the log of the e(s) effect. I've pulled together a small notebook for this (may contain errors but I hope you get the idea).

https://github.com/SheffieldML/notebook/blob/master/GPy/Space_time_effects.ipynb

This could contain mistakes but perhaps that is one path to follow?

If the former, then you would need to be able to specify a e_s for every space location (including when making predictions). I think the easiest way to do this would probably to be rewriting GPy.likelihoods.poisson.py to accept e_s values for every Y value. This would probably be done by passing it along within Y_metadata. I.e. Y_metadata = {'space_multiplier' = np.array([....])}. I will try and think of a more elegant solution, as I guess a spatial term is more like a 'X_metadata'.

**Comment by yiyang-gt** [comment]
Thanks @alansaul! My initial idea is to have a fixed term for each location. I tried you suggestion and it works well! 

Learning the spatial terms from data seems to be an interesting idea, and I will try to play with this idea based on your notebook :)

**Comment by sar2160** [comment]
Hi all,

I'm looking into implementing this same model in GPy and ran into this thread. Just wondering if anyone worked on the fixed e_s solution @alansaul described above and if any of it made it's way into the package?
