### ISSUE TITLE
Heteroscedastic GP model without need for Y_metadata

### ISSUE THREAD

**Issue by Imdrail** [SheffieldML/GPy#306]
Greetings!

As a part of my batchelor thesis I integrated the variational heteroscedastic GP regression model from the paper "Variational Heteroscedastic Gaussian Process Regression" into your framework.

The model itself implements the base Model and works with the same input as a standard GP regression from your framework.
It supports the functions optimize and all needed functions for optimize, and is able to predict mean and variance.

I want to ask if you can provide me support to fully integrate this, already working, model into your framework.

Due to the difference in implementations I was so far unable to use your kernels for the model and thus use a square exponential kernel of the other framework.
Furthermore I might have not fully understood the layout of your framework and therefore possibly made mistakes in the structure of my model.

**Comment by lawrennd** [comment]
Hi!

That would be great if you can integrate it!

Best way is through a pull request on the repository. Can you raise it as
an issue on the github repo? Then we can make sure that the right people
are tagged with regard to its integration.

Neil

**Comment by Imdrail** [comment]
Thanks for the quick answer

I created a branch and cleaned the code up a bit, but when I try to push the branch I get the message that permission to push is denied to me(error 403).
What shall I do? 

Felix

**Comment by lawrennd** [comment]
Hi Felix,

You submit fork the repo, edit the forked code and submit a pull request.

More details here:

https://help.github.com/articles/using-pull-requests/

The push access is restricted to members of the repository.

Neil

**Comment by Imdrail** [comment]
Thank you very much so far I was always included into projects and able to push directly.
I created a pull request and hope for answers.

Felix

**Comment by robertocalandra** [comment]
Thanks Neil, we are not exactly sure what are the guidelines for submitting the code and how to integrate it with all the kernels already available. If you somebody could give us some help it would be great!

**Comment by lawrennd** [comment]
Pull requests on the repo work best I think. And discussion of code is best
done via github issues.
