### ISSUE TITLE
Change default branch for pull requests

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#315]
Master is our current default branch. Now that we have pip in place, we could change over to a new structure of development. The default branch would be devel (so that pull requests automatically go into development) and have the master branch be called deploy, such that the deploy branch is the only one which gets deployed on pip?

**Comment by lawrennd** [comment]
Sounds reasonable. So in the end there would be no branch called master?

**Comment by mzwiessele** [comment]
Yes exactly. The idea is to get rid of master, and have devel as the default branch. Additionally there would be a new branch called deploy, which will be the branch, where pip builds will be deployed from. 

I will make this change just before deploying the next version.

**Comment by mikecroucher** [comment]
sounds good to me!

**Comment by mzwiessele** [comment]
Done! master will be deleted in due course
