### ISSUE TITLE
heteroscedastic variance for data points. 

### ISSUE THREAD

**Issue by animesh-garg** [SheffieldML/GPy#329]
Is there a way to train with Heteroscedastic variance for data points?

**Comment by mzwiessele** [comment]
Yes, but only variance for each datapoint. You can use the HeteroscedasticWhite kernel. This is only available from the devel branch, and will be in the next release. You can also to Heteroscedastic regression, shown in the notebook on the notebook GitHub page. 

https://github.com/SheffieldML/notebook

You should have a look for those, there is many answers in there, it is our way of documenting GPy

**Comment by animesh-garg** [comment]
Thanks @mzwiessele 

I also wanted to check that in previous posts on Heteroscedastic noise models, it has been suggested, 
to use the Y_metadata. 

```
Y_meta = {'output_index':np.arange(len(Y))[:,None]}
m = GPy.models.GPHeteroscedasticRegression(X[:,None],Y[:,None],kern, Y_metadata=Y_meta)
```

And in the example notebook, they use the exact noise.

```
m['.*het_Gauss.variance'] = abs(error)[:,None] #Set the noise parameters to the error in Y
m.het_Gauss.variance.fix() #We can fix the noise term, since we already know it
m.optimize()
```

Could I pass in that the noise values are being generated from different distributions (using the Y_metadata) and also pass in the noise term. But not fix them. 
Would the model initialize the noise with the input values but optimize to get a set of variance values as set by Y_metadata?

**Comment by mzwiessele** [comment]
There is a mixed likelihood, which mixes the likelihoods for you. It takes Y metadata and distributed the terms for the datapoints to different likelihoods. As long as the noise distribution is implemented you can use it to have the parameters of it learnt. See in GPy.likelihoods, you will find it there.
