### ISSUE TITLE
parallel optimisation

### ISSUE THREAD

**Issue by sachinruk** [SheffieldML/GPy#330]
I was wondering if when I call `m.optimise` if it would be using some sort of parallel optimisation method. This is mainly in reference to if Gpy is using GPyOpt: http://sheffieldml.github.io/GPyOpt/

**Comment by Dapid** [comment]
GPy does the heavy lifting using the BLAS that scipy is linked to, and that is what may be parallel. `m.optimize_restarts` does several random attempts, and it can run in parallel.
