### ISSUE TITLE
ImportError: No module named 'base_plots'

### ISSUE THREAD

**Issue by sachinruk** [SheffieldML/GPy#331]
Hello,

Everytime I try to use a GPy plot command I get the error: `ImportError: No module named 'base_plots'`. I am using Python 3.5.1 |Anaconda 2.5.0 (x86_64) and the versions that I am using are as follows:

```
In [8]: matplotlib.__version__
Out[8]: '1.5.1'

In [9]: scipy.__version__
Out[9]: '0.17.0'

In [10]: numpy.__version__
Out[10]: '1.10.4'
```

Would downloading GPy from github help circumvent the issue?

**Comment by mzwiessele** [comment]
It will help yes. Are you on a Windows machine? 

We are working to get the new release out so you can poo install it easily.

**Comment by sachinruk** [comment]
I'm on a Mac. Apologies for the noob question but how do you compile the latest (stable GPy). When I git cloned and ran python setup.py it only compiled 0.8.8. I think 0.10 is the latest version?

**Comment by mzwiessele** [comment]
You go over to the level branch.

$ git checkout devel
$ python setup.py develop

Will do it for you.

**Comment by sachinruk** [comment]
Apologies but its saying that there is no setup.py file, am I supposed to cd into a directory before I run this command?

**Comment by sachinruk** [comment]
whoops my bad had to CD to into the root GPy folder, for some reason had CDed to the wrong place.
