### ISSUE TITLE
Sparse GP regression with periodic kernels

### ISSUE THREAD

**Issue by sachinruk** [SheffieldML/GPy#332]
I am trying to fit some time series data from which I have seen that there are some daily patterns by looking at the ACF/PACF plots. Hence, I tried to implement the following:

```
k_day = GPy.kern.PeriodicExponential(input_dim=1,period=1)
k_sum = k_day + GPy.kern.White(1)
m2 = GPy.models.SparseGPRegression(x, y, k_sum, num_inducing=10)

```

When I run the above code I get a NotImplementedError. Does this mean as of now I cannot use periodic kernels with Sparse GPs in GPy?

You may reproduce the error by using the following x,y values:

```
x = np.array([np.linspace(0,10,100)])
y = np.sin(x)+np.random.randn(np.size(x))*0.1
```

**Comment by mzwiessele** [comment]
Yes it is not implemented.

You can implement it by implementing the gradients of the periodic kernel wrt X and the diagonal form of it and putting a pull request in. We always like to see people participating in the development of GPy. Make sure you are using the devel branch to put your pull request in.

**Comment by sachinruk** [comment]
If you show me an example of say how it was implemented in the RBF kernel (or where in the code) I would gladly implement it.

**Comment by mzwiessele** [comment]
Have a look at the developers documentation:

https://gpy.readthedocs.org/en/latest/ https://gpy.readthedocs.org/en/latest/

There are examples of how to implement kernels and models. The periodic kernel can be found in 

https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/standard_periodic.py https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/standard_periodic.py
https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/periodic.py https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/periodic.py

I think the std periodic one is the one you want.

**Comment by sachinruk** [comment]
I created a pull request. Could you let me know if it is correct. Can do more kernels if needed.

**Comment by jluttine** [comment]
This is great, thanks! (Not a comment on correctness, just general enthusiasm.) I need to use sparse approximation on some periodic kernels. Does the pull request now support only StdPeriodic? I'd be interested to use at least PeriodicMatern52, maybe other periodic kernels as well.

**Comment by sachinruk** [comment]
That's the thing. I didn't actually test it. I know the maths part is correct (at least 90% confident) just not entirely sure about the code. Especially why there is a sum component. If I get the green light to it being correct I'll implement this for most if not all kernels by this weekend.
