### ISSUE TITLE
Feature request: compactly supported covariance functions

### ISSUE THREAD

**Issue by jluttine** [SheffieldML/GPy#333]
I suppose there are no compactly supported covariance functions implemented yet? As they result in sparse covariance matrices, computations can scale perhaps to one or two orders of magnitude larger datasets. Of course, sparse matrices would need to be treated properly in order to gain this benefit. Would it require a huge change to the GPy core or would it be sufficient to just implement the relevant kernel classes, do you have any insight? Scikit.sparse offers a thin wrapper for SuiteSparse/CHOLMOD to access sparse Cholesky decompositions etc. I've also implemented some additional needed functions years ago but they haven't (yet) been merged into scikit.sparse. Do you think it would be useful and worth the effort, or would it just be too much work to integrate it? I might be able to implement this at some point (to some extent at least), but no promises at the moment. Anyway, I wanted to create this issue to hear your comments.

Another question: Does GPy include some tricks for modelling large datasets with short length-scale?

**Comment by mzwiessele** [comment]
There is already an issue in GPy for sparse matrix support. No one had the time to do it yet, it would have to be crc matrices, as the slicing is being done along the columns.

**Comment by jluttine** [comment]
Ok, thanks! I put it here for reference: https://github.com/SheffieldML/GPy/issues/128. You can close this as duplicate if you want.

**Comment by jluttine** [comment]
I actually didn't quite understand the other issue, so I'm just making sure: it is about sparse covariance matrices, not sparse data matrices, right? This wasn't quite clear to me from that issue report, so just checking that this really is a duplicate.

**Comment by mzwiessele** [comment]
Well, if the data matrix (X) is sparse, then the covariance matrix will be sparse as well : )

**Comment by jluttine** [comment]
Hmm, I think they are separate things: The covariance matrix can be sparse even if the data matrix is dense (with compactly supported covariance functions). And on the other hand, if data sparsity means that there are lots of zeros in the matrix, I don't see how this would necessarily result in sparse covariance matrices - depends on your covariance function, I'd say.

I also think they serve slightly different purposes. You can use sparse data matrix to reduce the size of the data matrix, and then use dense covariance matrix with inducing inputs without any sparsity in the covariance matrix. Useful perhaps if you have very high dimensional input space? Sparse covariance matrices are useful for local (i.e., short lengthscale) functions in datasets with a large number of samples.

(Edit: By data matrix I mean the input data matrix.)

**Comment by Dapid** [comment]
I think what Jaakko is after banded covariance matrix, which makes sense if your range of x values expands more than several times the length scale of the kernel. This way you can tackle large datasets, without giving the trade offs of the sparse approximation (or rather, different ones).

When studying GP I have also thought about it, but I haven't seen any papers on that (which means little, I am not the expert here).

**Comment by jluttine** [comment]
Yes, banded covariance matrices are one special case of sparse covariance matrices. There are more discussion about compactly supported covariance funtions in the GP book by Rasmussen and Williams, and, for instance, in the paper "Modelling local and global phenomena with sparse Gaussian processes" by Vanhatalo and Vehtari (2008) (http://arxiv.org/ftp/arxiv/papers/1206/1206.3290.pdf).

The benefit of sparse covariance matrices (note: different from the "sparse" approximation) is that the Cholesky decomposition can be done by using special sparse matrix algorithms which can give significant speedups.

But as I said, I didn't understand the other issue almost at all, so I can't say whether this is a duplicate. To me it sounded like that issue was about sparse data which is a different matter.

**Comment by sachinruk** [comment]
Just wondering if there has been any update on this? On Matlab atleast taking the Cholesky decomposition of a sparse matrix was a lot faster than a non-sparse matrix. In that particular case I had multiplied with a compact support covariance function.

Would help immensely with large datasets as @jluttine mentioned.
