### ISSUE TITLE
Rational quadratic broken for large powers

### ISSUE THREAD

**Issue by jluttine** [SheffieldML/GPy#336]
The rational quadratic kernel is broken for large values of `power`:

``` python
kern = GPy.kern.RatQuad(input_dim=1, power=1e4)
m = GPy.models.GPRegression(np.random.randn(100,1), np.random.randn(100,1), kern)
m.checkgrad(verbose=True)
m.optimize()
```

In the gradient check, you can see NaNs, and the optimizer crashes because of `LinAlgError`. This may happen if the user sets a large value for `power` or the optimizer just happens to try such a value (as happened to me). Perhaps RatQuad should use RBF (i.e., exponentiated square or squared exponential) kernel definition for large powers if the computation can't otherwise be fixed? That should be practically equivalent if `power` is very large.

**Comment by mzwiessele** [comment]
This must be numerical issues and why would you use high powers for the RationalQuadratic kernel, instead of using the RBF, or Matern?

**Comment by jluttine** [comment]
If the optimizer happens to hit such a value.

**Comment by zhenwendai** [comment]
I have done a quick re-implementation of rational quadratic kernel. Please check its correctness.
