### ISSUE TITLE
GPy stop making progress after UserWarning

### ISSUE THREAD

**Issue by yiyang-gt** [SheffieldML/GPy#338]
Greeting!

I met the warning when I play with Poisson likelihood: /usr/local/lib/python2.7/site-packages/GPy/inference/latent_function_inference/laplace.py:222: UserWarning:Not perfect mode found (f_hat). difference: 1.78940106929e-05, iteration: 60 out of max 60

The problem is that after the warning, it seems that all my GPy programs stop making any progress. Is this an issue with GPy?

**Comment by mzwiessele** [comment]
@alansaul This is expected right? I think the warning is just a printout and the model still optimizes?

**Comment by alansaul** [comment]
That is saying that the mode found for the Laplace approximation isn't perfect (although to be honest, 1e-5 is probably too strict). It shouldn't stop anything running in GPy though, it should continue to optimize (hopefully on the next step it will say "f_hat now fine again"). What do you mean by stopping all your GPy programs stop making any progress?

At the moment we don't inform the user of how bad the mode mismatch gets (as we didn't want to have 100 print outs for an optimization), so it might be worse than 1e-5 if it doesn't later print "f_hat now fine again". I'm not sure how best to handle this, we either need to inform the user every step or have some other solution.

In answer to your question, it's an issue with the Laplace approximation, and perhaps it's stability of its newton updates. You should be cautious when using models that have said "Not perfect mode found", being followed later by "f_hat now fine again", as it indicates that the newton steps used in the approximation are not finding the mode quickly enough (in this case within 60 iterations). 

You could try the following (to give it more steps in the newton optimization).

```
inference = GPy.latent_function_inference.Laplace()
inference._mode_finding_iter = 200
m = GPy.core.GP(X=X, Y=Y, inference_method=inference, etc...)
```

This will instead allow it to use 200 iterations in its newtons steps to try and find the mode, but could make each optimization step slower as a result.

**Comment by yiyang-gt** [comment]
Thanks for the quick reply! 

I think maybe it's just because the optimization is very slow now, or there are other issues with my machine. I will double check about these. Thanks again!
