### ISSUE TITLE
Questions on FITC 

### ISSUE THREAD

**Issue by Homesh01** [SheffieldML/GPy#340]
I'm trying to apply the FITC approximation to binary data with around 100 features and 6000 observations and 100 inducing points. I'm using the following code:

```
m = GPy.models.FITCClassification(X_train_svd, y_train, num_inducing = 100)
for _ in range(10):
    m.update_likelihood_approximation()
    m.optimize()
```

My understanding is that m.update_likelihood_approximation() function will update the likelihood for current hyperparamaters and the m.optimize() will optimise these hyperparameters. I'm also assuming it randomly selects the inducing points. Is my understanding correct? I'm also assuming the optimisation method is based on EP; is this correct as well?

For this current dataset it is classifying the test set with probability 0.5 for all observations and so can't distinguish between the different classes. Is my code above correct? If not, what modifications should I make. I've used logistic regresssion and it can distinguish between the classes quite well, so not a problem with the data.

I'd appreciate any help.

**Comment by mzwiessele** [comment]
What is the range of your input data x? This will affect the choice of for the initialization. You might want to also normalize your data before optimizing and adjust the likelihood variance. 

On the devel branch it changed so you do not have to call update anymore but just call optimize several times as at the beginning of the optimization the ep approximation will bee updated automatically.

**Comment by Homesh01** [comment]
I haven't normalised my data; I will do this. How do I adjust the
likelihood variance?

**Comment by mzwiessele** [comment]
m.likelihood.variance = m.Y.var()/100 

assuming m is your model. This sets your likelihood varaince to 100th of the empirical variance of the data. Also you want to set your lengthscales to something reasonable, maybe m.X.ptp()/2, but all of these are suggestions, which might not work for your data. have a play with it and youll get an intuition for it.
