### ISSUE TITLE
Noiseless predictions

### ISSUE THREAD

**Issue by jluttine** [SheffieldML/GPy#342]
I must have missed something and most probably this isn't a bug. But in any case I'll ask this here if it happens to be a bug or a missing feature.

So, how to make noiseless predictions? I don't want the observation noise variance to be added to the prediction variance. (Yeah, I could subtract it manually afterwards, but I suppose there is a better way.)

Consider this example:

``` python
import GPy
k = GPy.kern.RBF(input_dim=1, variance=1.0, lengthscale=10)
mod = GPy.models.GPRegression(np.random.randn(600, 1), np.random.randn(600,1), kernel=k)
mod['Gaussian_noise.variance'] = 10**2
print(mod.predict(np.array([[0]]), kern=k))
```

I'd expect this code snippet to make the predictions using only the kernel `k` without the noise kernel. But as the printed predictive variance is around 100, it obviously adds the observation noise. I tried googling and reading docs and notebooks, but couldn't find any help. But I still believe I have just missed something really obvious, so sorry already beforehand. And thanks! :smile:

**Comment by alansaul** [comment]
Hi Jaakko, I believe you are just looking for the _raw_predict function, which doesn't add the likelihood noise. Sorry it is a slightly hidden name, we should really make a more accessible alias!

```
import GPy
import numpy as np
k = GPy.kern.RBF(input_dim=1, variance=1.0, lengthscale=10)
mod = GPy.models.GPRegression(np.random.randn(600, 1), np.random.randn(600,1), kernel=k)
mod['Gaussian_noise.variance'] = 10**2
print(mod._raw_predict(np.array([[0]]), kern=k))
# or since you wish to predict with the entire kernel of the model (the default)
#print(mod._raw_predict(np.array([[0]])))
```

Alan

**Comment by jluttine** [comment]
Ok, thanks a lot! I didn't know about that function. Perhaps adding a keyword argument like `noise=False` (or something similar) to `predict` function would be super cool, or a separate visible function, for instance, `predict_noiseless`.  So, I could change this issue into a feature request. :wink: But thanks a ton for the quick response!

**Comment by mzwiessele** [comment]
fixed for the new release
