### ISSUE TITLE
Feature request: support lists as data

### ISSUE THREAD

**Issue by jluttine** [SheffieldML/GPy#343]
Very minor feature request: would it be possible to support lists as data? So that they are wrapped to NumPy arrays in the methods if necessary. For instance, I'd like this to work:

``` python
import GPy
k = GPy.kern.RBF(input_dim=1)
mod = GPy.models.GPRegression(np.random.randn(10, 1), np.random.randn(10,1), kernel=k)
mod.predict([[0], [1], [2]])
```

But it raises `AttributeError`.

**Comment by alansaul** [comment]
Hi Jaakko, in general we try to keep just one way of doing things so there aren't as many edge cases to catch when testing. We have been talking (for a while) about allowing pandas Dataframes instead of just numpy arrays for data. However I'm not sure if lists are worth supporting since they are so similar to numpy arrays in their use. Is there a particular reason why you need this capability that might justify us supporting it throughout GPy?
Thanks,
Alan

**Comment by jluttine** [comment]
No significant reasons, just convenient in some cases when writing small data arrays manually. I suppose that it'd be relatively simple to support by adding `np.asanyarray(data)` to the beginning of those functions that take data arrays from the user. But yes, I understand that it's not particularly useful nor significant, just a thought if it was easy and quick to add. Anyway, thanks!

**Comment by mzwiessele** [comment]
This has to be tagged as won't fix. We want to make sure users understand dimensionality of data and therefore it will always be at least necessary too give a one dimensional vector, and with that a numpy array.

**Comment by mzwiessele** [comment]
But thanks for the thought :) I hope I explained why this won't be implemented enough :)

**Comment by jluttine** [comment]
@mzwiessele Sorry, I didn't quite understand your explanation. NumPy itself supports arrays/matrices as lists in all its functions. For instance, you can do `np.linalg.svd([[1, 2, 3], [4, 5, 6]])`. It means simply a call `data = np.asanyarray(data)` at the beginning of the functions that are facing the user directly. It is simple as that, nothing else needs to change, nothing new needs to be supported. It doesn't mean that data is given as one dimensional vectors or that dimensionalities are somehow lost. I just think that it is consistent in the NumPy/SciPy world to support arrays as lists without forcing the user to write explicitly `np.array(...)` around the data array he/she has written as a (nested) list.

The point of this feature request is to make the user interface just a little bit more polished and consistent with other NumPy/SciPy world user interfaces. It is a very minor matter but also extremely simple and straightforward to implement. But yes, I do understand if you feel that it still isn't worth any efforts. But I'd consider this as a low priority small task that could be implemented if someone just has a little bit of extra time. I might have some myself at some point for that matter.

But thanks for the feedback!

**Comment by mzwiessele** [comment]
I see your point. In order to fully support this it would require some big changes in the data handling, as it would require some sort of data object for all the GP models. This world also allow for normalization and preprocessing of data in a centralized place.

**Comment by jluttine** [comment]
Ok. I just don't quite understand why it would require big changes or new data objects if you already support NumPy arrays. If you currently assume at some lines that an argument `x` given by a user is a NumPy array, you can add list support by wrapping `x` as `np.asanyarray(x)`, and then `x` can be a NumPy array or a nested list without needing to change anything elsewhere. But perhaps I'm missing something because I haven't looked into the GPy code that much?

**Comment by mzwiessele** [comment]
No you are right, but the number of points where we assume exactly that is just too high in order to support it in the future, if we do not centralize it : )

**Comment by jluttine** [comment]
Ok! :+1:
