### ISSUE TITLE
Pickle error on optimizer

### ISSUE THREAD

**Issue by sachinruk** [SheffieldML/GPy#344]
I am trying to do some random restarts on the optimiser by using:
`m.optimize_restarts(parallel=True)`
and I am getting the error `Can't pickle local object 'Model.optimize_restarts.<locals>.opt_wrapper'`. I am using the development version 0.9.7.

Any thoughts?

**Comment by mzwiessele** [comment]
Thus is expected and has to do with the profiling of lambda functions in python... If you find a solution pls let us know :)

**Comment by sachinruk** [comment]
I think this might be a quick fix by writing a wrapper function: 
http://stackoverflow.com/questions/8804830/python-multiprocessing-pickling-error

Again if you show me where the source code is I can write those wrappers over the weekend.

**Comment by mzwiessele** [comment]
Its in the paramz package under 

`params.model.Model.optimize_restarts`

https://github.com/sods/paramz/blob/master/paramz/model.py#L111

Just put in a pull request into paramz, when finished : )
