### ISSUE TITLE
Sparse DTC & FITC Classification

### ISSUE THREAD

**Issue by ghost** [SheffieldML/GPy#348]
I'm trying to implement sparse GP classification via FITC. This script `https://github.com/SheffieldML/GPy/blob/master/GPy/models/sparse_gp_classification.py` outlines how to implement GP classification when inference is implemented by EP DTC. However when I attempt to change the inference method to EP FITC by using the function in the script `https://github.com/SheffieldML/GPy/blob/master/GPy/inference/latent_function_inference/fitc.py` I get an error since the likelihood is not Gaussian.

Is my understanding correct that GPy only facilitates sparse EP DTC classification and not EP FITC classification?

**Comment by ekalosak** [comment]
Stale.
