### ISSUE TITLE
Scalable Variational Gaussian Process Classification

### ISSUE THREAD

**Issue by ghost** [SheffieldML/GPy#349]
This paper discusses how to implement a scalable GP model for classification `http://arxiv.org/pdf/1411.2005.pdf`. This script `https://github.com/SheffieldML/GPy/blob/master/GPy/core/svgp.py` references this paper. 

I fit as model as follows:
`m = GPy.core.svgp.SVGP(X = X_train_svd, Y = y_train, Z = X_induce, kernel = k, likelihood = GPy.likelihoods.Bernoulli())`

When I want to optimize I can use the following:
`optimizeWithFreezingZ`
However this has the problem that the inducing points will be fixed. From my understanding of the paper, they are able to optimize over the inducing points, so this seems a sub-optimal optimization approach.

The paper mentions that stochastic gradient descent can facilitate dealing with millions of data points. I try to optimize via SGD as follows:
`m.optimize_SGD()`,
but get the error `NameError: global name 'SGD' is not defined`. The function optimize_SGD() can be found in lines 268 - 272 of the script `https://github.com/SheffieldML/GPy/blob/master/GPy/core/model.py`.

Can someone please explain why this error is occurring and how to optimize via SGD?

**Comment by mzwiessele** [comment]
This is why we need to put the new release out! These things are fixed in the devel branch as far as I know and there exists an optimizer which is called adadelta. The method you mentioned does not exist anymore....

**Comment by ghost** [comment]
Thanks for your reply.

Yes, so I started using adadelta, which to my understanding is a variant of SGD. However when I optimize using it, computationally it takes longer than the default optimization method. I'm assuming this isn't supposed to happen or will it only be faster if I parallelize the optimization procedure?

**Comment by ghost** [comment]
So its seems that m.optimize_restarts(parallel = True) facilitates such a parallel optimization approach. When I run this command I get the error:
`m.optimize_restarts(parallel = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/GPy-0.8.8-py2.7-linux-x86_64.egg/GPy/core/model.py", line 104, in optimize_restarts
    raise e
cPickle.PicklingError: Can't pickle <type 'GPy.util.choleskies_cython._memoryviewslice'>: attribute lookup GPy.util.choleskies_cython._memoryviewslice failed
`
Is my understanding correct that this parallellizes the optimisation and why do I get an error if so (as in why is there a pickling error)?

**Comment by mzwiessele** [comment]
Optimize restarts is currently not supported due to how multiprocessing handles functions...
