### ISSUE TITLE
Simple GP regression produces odd behavior

### ISSUE THREAD

**Issue by geodu** [SheffieldML/GPy#351]
Hi,

I've got some simple (nondeterministic) code that tries to fit a GP to the noiseless relationship y = x:

```
import numpy as np
from matplotlib import pyplot as plt
import GPy

x = np.random.rand(10, 1)
y = x.copy()

kernel = GPy.kern.RBF(1)
model = GPy.models.GPRegression(x, y, kernel)
model.optimize()

model.plot()
plt.show()
```

Unfortunately, the GP ends up malformed. See [here](http://i.imgur.com/Tg57LEy.png) for an example of the plot produced. I've found that the variance outputted by model.predict has a "spiky" relationship and even goes negative at points. Any ideas on why this is happening? Thanks!

**Comment by mzwiessele** [comment]
Yes great spotting. This has to do how we compute the covariance in a separable way for the code to work in general. We have fixed this in the devel branch, which will be the next release of GPy soon.
