### ISSUE TITLE
kernel parameters change when used inside model

### ISSUE THREAD

**Issue by sachinruk** [SheffieldML/GPy#353]
This might be related to this bug[https://github.com/SheffieldML/GPy/issues/334], so just letting you know. When I try the following

```

import GPy
import numpy as np

x = np.linspace(0,1)
y = x + 1
k3 = GPy.kern.Bias(1) + GPy.kern.Linear(1) + GPy.kern.RBF(1) + GPy.kern.White(1)
k3_param = k3[:]
m1 = GPy.models.GPHeteroscedasticRegression(x[:,None],y[:,None],k3)
```

the parameter vector `k3_param` changes quite randomly. (i.e. isn't a whole bunch of ones as I expected). I am running version 0.9.7

**Comment by mzwiessele** [comment]
Yes it is expected. Different issues with the in memory handling of parameters make the param_array of k3 is not consistent when adding it to a model. If you want to save parameters of any parameterized object you just take k3[:].copy().
