### ISSUE TITLE
cannot find AUTHORS.txt??

### ISSUE THREAD

**Issue by CarlCui-AI** [SheffieldML/GPy#357]
Hi,

I'm trying to install the latest 1.0.0 GPy through pip, but it fails on setup.py because of "no such file AUTHORS.txt". I'm trying to install it on Amazon EC2 ubuntu.

Can you investigate?

**Comment by mzwiessele** [comment]
What is your system spec?

**Comment by mzwiessele** [comment]
nvm, ill investigate!

**Comment by mzwiessele** [comment]
Its running and being uploaded, expect it to work in a few hours

**Comment by CarlCui-AI** [comment]
@mzwiessele Great! Thanks for the effort. :+1:

**Comment by mzwiessele** [comment]
Is it fixed for you?

**Comment by CarlCui-AI** [comment]
@mzwiessele Oh, yeah. I'm at PST, just upgraded to 1.0.1 at work. Sorry about that. :+1:
