### ISSUE TITLE
Missing directory

### ISSUE THREAD

**Issue by befelix** [SheffieldML/GPy#360]
When moving the old config file to the new location in `~/.config/GPy` you don't check whether that folder exists, causing to an error.

```
GPy: Found old config file, moving to new location /home/felix/.config/GPy/user.cfg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/felix/pip-build-fS8UIS/GPy/setup.py", line 185, in <module>
        os.rename(old_user_file, user_file)
    OSError: [Errno 2] No such file or directory
```

**Comment by mzwiessele** [comment]
good spotting updating

Max Zwiessele
Sheffield Institute of Translational Neuroscience
University of Sheffield
385a Glossop Road,
S10 2HQ, Sheffield,
United Kingdom

eMail: ibinbei@gmail.com
Website: http://staffwww.dcs.sheffield.ac.uk/people/M.Zwiessele/
