### ISSUE TITLE
Saving a GPy plot as an image file

### ISSUE THREAD

**Issue by timothy-shields** [SheffieldML/GPy#363]
How can I save a GPy plot/visualization to an image file?  I am on a Linux system with no attached display, so this is my only option for viewing visualizations.

This is my current attempt:

```
import GPy
import numpy as np

# sample inputs and outputs
X = np.random.uniform(-3.,3.,(50,2))
Y = np.sin(X[:,0:1]) * np.sin(X[:,1:2])+np.random.randn(50,1)*0.05

# define kernel
ker = GPy.kern.Matern52(2,ARD=True) + GPy.kern.White(2)

# create simple GP model
m = GPy.models.GPRegression(X,Y,ker)

# optimize and plot
m.optimize(messages=True,max_f_eval = 1000)

GPy.plotting.change_plotting_library("matplotlib")
fig = m.plot()
fig.savefig("model.png")
```

I get an error on the `fig = m.plot()` line:

> Unable to access the X Display, is $DISPLAY set properly?

It seems like `m.plot()` is trying to show the figure immediately.  How can I avoid this and only write to an image file?

**Comment by mzwiessele** [comment]
ahh you get back the axis not the figure. so you can get to the figure by calling ax = m.plot() and then ax.figure.savefig("test.pdf"). btw, you always want to save as pdf, so you have a full res vector graphic of you plot, in which you can zoom in.

**Comment by timothy-shields** [comment]
@mzwiessele Thanks, that's half the answer. :) What about `m.plot()` raising that error about $DISPLAY?  How can I plot such that it doesn't try to immediately display it?

**Comment by mzwiessele** [comment]
That is a matplotlib issue. Are you running in a jupyter notebook? What happens if you run 

from matplotlib import pyplot as plt
fig, ax = plt.subplots(1,1)

**Comment by timothy-shields** [comment]
I have resolved the issue.  Here is the code in case anyone else encounters the same problem:

```
import matplotlib
import GPy
import numpy as np

# Configure GPy -> matplotlib -> Agg
matplotlib.use("Agg")
GPy.plotting.change_plotting_library("matplotlib")

X = np.random.uniform(-3., 3., (50, 2))
Y = np.sin(X[:, 0:1]) * np.sin(X[:, 1:2]) + np.random.randn(50, 1) * 0.05
kernel = GPy.kern.Matern52(2, ARD=True) + GPy.kern.White(2)
model = GPy.models.GPRegression(X, Y, kernel)
model.optimize(messages=True, max_f_eval = 1000)

ax = model.plot()
ax.figure.savefig("model.pdf")
```

where the key lines are

```
# Configure GPy -> matplotlib -> Agg
matplotlib.use("Agg")
GPy.plotting.change_plotting_library("matplotlib")
```

**Comment by JeanKaddour** [comment]
This doesn't work for me:

```
GPy.plotting.change_plotting_library("matplotlib")

X = np.array([[-4], [5],[-3],[-2.5], [-2], [1]])
Y = np.sin(X) + np.random.randn(len(X),1)*0.1
kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)

m = GPy.models.GPRegression(X,Y,kernel)
m.optimize(messages=False)

ax = m.plot(plot_limits=[-15, 15], samples=5)
ax.figure.savefig("gp.pdf", dpi=300)
```

gives me

```
AttributeError:` 'dict' object has no attribute 'figure'
```

**Comment by blankjul** [comment]
I have the same issue. 
Did the API for plotting change?

**Comment by wangqiuoe** [comment]
> This doesn't work for me:
> 
> ```
> GPy.plotting.change_plotting_library("matplotlib")
> 
> X = np.array([[-4], [5],[-3],[-2.5], [-2], [1]])
> Y = np.sin(X) + np.random.randn(len(X),1)*0.1
> kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)
> 
> m = GPy.models.GPRegression(X,Y,kernel)
> m.optimize(messages=False)
> 
> ax = m.plot(plot_limits=[-15, 15], samples=5)
> ax.figure.savefig("gp.pdf", dpi=300)
> ```
> 
> gives me
> 
> ```
> AttributeError:` 'dict' object has no attribute 'figure'
> ```

I have same issure

**Comment by sgugler** [comment]
+1

**Comment by sgugler** [comment]
I found a workaround:
If you print out the dictionary from `ax = m.plot(plot_limits=[-15, 15], samples=5)`, so `print(ax)`, we see that it contains a dictionary,
```python
{'dataplot': [<matplotlib.collections.PathCollection object at 0x7f3d9f6f2f60>], 'gpmean': [[<matplotlib.lines.Line2D object at 0x7f3d9f6f2eb8>]], 'gpconfidence': [<matplotlib.collections.PolyCollection object at 0x7f3d9f6f27b8>]}
```
the first entry of which is the matplotlib plot we want. So the following worked for me:
```python
dataplot = ax['dataplot'][0] 
dataplot.figure.savefig("gp-test.pdf")
```
