### ISSUE TITLE
How to install GPy in Windows 7?

### ISSUE THREAD

**Issue by Irene-GM** [SheffieldML/GPy#369]
I guess it is not the best place to post this problem, but I didn't know where to address this question, apologies for that.

Basically, is there any way of installing this package in Windows 7? Tried the `.whl` file and it is not working (Error `GPy-1.0.6-cp34-cp34m-macosx_10_5_x86_64.whl is not a supported wheel on this platform`), neither the `pip` installation (I guess it may be due to a lack of compiler in Windows) and finally I could not find any precompiled package in Gohlke's website.

Can you kindly provide a small hint to do this installation? Are the installation instructions correct? Perhaps I overlooked something, but been struggling for a while.

Thanks a lot!

**Comment by mzwiessele** [comment]
We will supply the binaries over the course of the week. We are still doing this manually, please apologize the delay that is causing...

**Comment by AliBaheri** [comment]
Hi,
I am trying to install GPy on Windows 7 (I have already installed and used GPy on Mac), but I am facing with problem and following error:

  FAILED < error =1>

after trying this instruction:
git clone https://github.com/SheffieldML/GPy.git
cd GPy
git checkout devel
python setup.py build_ext --inplace
nosetests GPy/testin

even the following instruction does not work:
pip install --upgrade https://github.com/SheffieldML/GPy/tarball/devel
Could you please give some help in this regard?

**Comment by mzwiessele** [comment]
Did you try pip install?

**Comment by ghost** [comment]
Actually, with Python 3.4, running "pip install gpy" still returns an error to me: 

`numpy.distutils.system_info.NotFoundError: no lapack/blas resources found`

I guess I need to install a compiler for Windows, but is there any way of bridging this problem? A precompiled package maybe? Thanks!

**Comment by mzwiessele** [comment]
Working on it, the win binaries seem to be missing.

**Comment by mikecroucher** [comment]
The Windows binaries are missing because I base the builds on the 'deploy' branch since I thought this was current practice.

I see that there is a PR for an update to deploy - #402 but that it failed various tests.

@mzwiessele How would you like me to proceed?

**Comment by mzwiessele** [comment]
fixed by #413, try to update your packages (paramz, GPy)

**Comment by Irene-GM** [comment]
Works!

Just for the record: On a fresh Python 3.5.2 installation on Windows 7, first I updated `numpy` (v 1.11.1) and `scipy` (v 0.18) from Gohlke's website (Win7 users need the pre-compiled packages), then I installed `paramz`, then `matplotlib`, then `GPy` (v 1.2.1). Tried [this tutorial](http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/basic_gp.ipynb) and works.

Thanks for the fix! :+1:

**Comment by debipe20** [comment]
Hello, I was trying to install GPy using pip command in Command Prompt. But it doesn't work. It is showing the following messages. I also try to install paramz but it also dosen't happen.
 
 Using cached decorator-4.1.2-py2.py3-none-any.whl
Installing collected packages: decorator, paramz, GPy
Exception:
Traceback (most recent call last):
  File "c:\program files\python 3.6\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python 3.6\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python 3.6\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python 3.6\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files\python 3.6\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files\python 3.6\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\program files\python 3.6\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "c:\program files\python 3.6\lib\shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'c:\\program files\\python 3.6\\Lib\\site-packages\\decorator.py'

**Comment by AliBaheri** [comment]
Did you try this?
`conda install -c omnia gpy`
or installing from the sourse via `setup.py`

**Comment by debipe20** [comment]
Hello,
I don't actually. Can you help me?
