### ISSUE TITLE
kernel parameters in GPLVM 

### ISSUE THREAD

**Issue by kabdelfatah-zz** [SheffieldML/GPy#371]
By using GPLVM, each dimension in Y is manipulated as a separate GP. Is there a way to get the kernel parameters for each GP?

Thanks

**Comment by lawrennd** [comment]
For computational convenience the kernel parameters are normally set to the
same for each kernel.

**Comment by kabdelfatah-zz** [comment]
First of all thanks for your quick reply. 

Actually, this raise another question for me. Let us assume that we have dimensions of Y is equal to 3. So, this means that we should have different 3 GPs (each GP should model one column of Y). If all of these 3 GPs have **the same kernel parameters** and we infer the **same latent variables** X for all of them. Then, how these 3 GPs should give different outputs? 

What I was understanding about the GPLVM is that if we have for example 3 dimensions in Y, this means that we have 3 GPs with different kernel parameters? is this right?

Thanks for your time

**Comment by lawrennd** [comment]
Because the GP is a nonparametric model, the different output for each
dimension (inside the data Y) forces each function to be different.

Neil

**Comment by kabdelfatah-zz** [comment]
Many thanks for the clarifications and for your time.
