### ISSUE TITLE
nonstandard definition of stationary?

### ISSUE THREAD

**Issue by strongh** [SheffieldML/GPy#372]
In `Stationary`, a covariance function is defined in GPy as [stationary](https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/stationary.py#L29) when it depends only on the l2-norm |x_1 - x_2 |. However this is the typical definition of isotropy, while stationarity is usually a bit more relaxed. The more common version of stationarity is that the covariance is a function of x_1 - x_2 (See e.g. [R&W](http://www.gaussianprocess.org/gpml/chapters/RW4.pdf) first paragraph of section 4.1).

Although this is only a minor distinction, I think that the subtlety only increases the chance of confusion. My suggestion is to rename `Stationary` to `Isotropic`, but there are other options. If GPy is going to stick with its definition of stationarity I think there should be a note about the minor departure from other definitions.

**Comment by lawrennd** [comment]
You are quite right Homer.

We should look at how much effort it would be to change those names.

Neil

**Comment by mzwiessele** [comment]
added comment in #dd22687b5eb34d57a150f9e630f34fd0a4938131

thanks!
