### ISSUE TITLE
Memory issue when adding multiple kernels

### ISSUE THREAD

**Issue by yiyang-gt** [SheffieldML/GPy#377]
Greeting!

I found the memory usage of GPy is extraordinary high when I added multiple kernels (10-20). The memory usage seems to have a linear relationship with the number of combined kernels. Is there anyway to reduce the usage of memory in this case?

Thanks!

**Comment by lawrennd** [comment]
I think that's because each kernel caches its computations separately. It's
true that there are applications where you want many kernels. @mzwiessele
is there an option for turning the caching off and would it help in
yiyang's case?

**Comment by mzwiessele** [comment]
Yes there is! @alansaul can explain it better, as he is working with it.

**Comment by mzwiessele** [comment]
Ok the gist is as follows. You create your model by handing in `initialize=False` as argument. Then you create your model as you would normaly. When the model is created as say `m` you disable the caching on the model: `m.disable_caching()`. Be aware, that the model is not initialized yet and you have to initialize it by calling `initialize_parameter()` on it before optimizing.

Here a working example:

``` python
k = GPy.kern.Matern32(1)
k += GPy.kern.Linear(1)

X = np.random.normal(0, 1, (100,1))
Y = np.random.multivariate_normal(np.zeros(X.shape[0]), k.K(X), 1).T

m = GPy.models.GPRegression(X, Y, kernel=k, initialize=False)
m.disable_caching()
m.initialize_parameter()
m.cache.caching_enabled #>> False
m.kern.cache.caching_enabled #>> False

print(m)

m.optimize()

m.plot()
```

**Comment by yiyang-gt** [comment]
Thanks for the reply! But I got the following errors ...

TypeError: **init**() got an unexpected keyword argument 'initialize'
AttributeError: 'GPRegression' object has no attribute 'disable_caching'

**Comment by mzwiessele** [comment]
Which version of GPy are you running?

**Comment by yiyang-gt** [comment]
0.8.8
I think the code on github does not support the operations as well... I just upgraded to the new version, and the code works now!

Thanks!

**Comment by mzwiessele** [comment]
that is the problem. just upgrade to 1.0. and it'll work.
