### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'shared_xaxes'

### ISSUE THREAD

**Issue by tjhgit** [SheffieldML/GPy#379]
Hello Max,

For the current GPy implementation this no more works:

figure = GPy.plotting.plotting_library().figure(3, 1, 
                        shared_xaxes=True,
                        subplot_titles=('slice at -1', 
                                        'slice at 0', 
                                        'slice at 1.5', 
                                        )
                            )

shared_xaxes is not recognized as an option of matplotlib.figure. Here the full stack trace:

TypeError                                 Traceback (most recent call last)

/opt/home/t13147/programming/scripts/python-scripts/bigData/fouling/forecast_xtemperature.py in <module>()

```
109 slices = [-1, 0, 1.5]

110 ax=plt.subplot(111)
```

--> 111 figure = GPy.plotting.plotting_library().figure(3, 1, shared_xaxes=True, subplot_titles=('slice at -1', 'slice at 0', 'slice at 1.5',))

```
112 for i, y in zip(range(3), slices):

113         canvas = m.plot(figure=figure, fixed_inputs=[(1,y)], row=(i+1), plot_data=False)
```

/opt/home/t13147/programming/python2.7-venv/local/lib/python2.7/site-packages/GPy/plotting/matplot_dep/plot_definitions.pyc in figure(self, rows, cols, gridspec_kwargs, tight_layout, **kwargs)

```
 44 

 45     def figure(self, rows=1, cols=1, gridspec_kwargs={}, tight_layout=True, **kwargs):
```

---> 46         fig = plt.figure(tight_layout=tight_layout, **kwargs)

```
 47         fig.rows = rows

 48         fig.cols = cols
```

/opt/home/t13147/programming/python2.7-venv/local/lib/python2.7/site-packages/matplotlib/pyplot.pyc in figure(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, **kwargs)

```
525                                         frameon=frameon,

526                                         FigureClass=FigureClass,
```

--> 527                                         **kwargs)

```
528 

529         if figLabel:
```

/opt/home/t13147/programming/python2.7-venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in new_figure_manager(num, _args, *_kwargs)

```
430 

431     FigureClass = kwargs.pop('FigureClass', Figure)
```

--> 432     thisFig = FigureClass(_args, *_kwargs)

```
433     return new_figure_manager_given_figure(num, thisFig)

434 
```

**Comment by mzwiessele** [comment]
Thanks for letting me know, removed the arguments for ease of use.
