### ISSUE TITLE
Compatible with pyspark 

### ISSUE THREAD

**Issue by Homesh01** [SheffieldML/GPy#382]
Is there any plans to create a version for pyspark?

If I remember correctly I think one of the papers on scalable GPs showed results on millions of data points. How was this done in a distributed manner?

**Comment by mzwiessele** [comment]
I am not aware of any, you are welcomed to look into it, I assume you are an expert with pyspark?

**Comment by Homesh01** [comment]
Hi Max,

Unfortunately I'm not a pyspark expert. The reason I ask such a question is because I often deal with large datasets which can't be called into memory. The step:

```
GPy.core.svgp.SVGP(X = X_train, Y = y_train, Z = X_induce, kernel = k,\
                       likelihood = GPy.likelihoods.Bernoulli(), batchsize = batchsize_number)
```

requires the dataset `X_train` to be called into memory. 

Have a form of GPs which could be done in a distributed fashion would be potentially useful. 

Thanks,

Homesh

**Comment by mzwiessele** [comment]
You should correspond with @zhenwendai and @alansaul they are the experts on multicore computations.
