### ISSUE TITLE
Is GPy returning a Prediction Interval or a Confidence Interval?

### ISSUE THREAD

**Issue by mmkhajah** [SheffieldML/GPy#385]
I have been playing around with GPy and it appears to me that its plotting function plots a **prediction interval** rather than a **confidence interval**. The prediction interval represents the uncertainty in new observations whilst the confidence interval represents the uncertainty in the mean (aka the prediction itself). If this is true, is there a way to get the actual confidence interval?

I may be wrong but after reading mainstream GP literature and other docs on other GP libraries, people do not seem to distinguish between the two.
![example](https://cloud.githubusercontent.com/assets/485791/15000392/b9e0037c-114c-11e6-83b3-1330f1a70445.png)

**Comment by mmkhajah** [comment]
Never mind. I was using the plot() function when I really should have been using the plot_f() function to plot latent function values and their associated confidence intervals. (I am using a GP with noisy observation model). Apologies.

**Comment by lawrennd** [comment]
Good spot! That's the correct solution!

Do we need to change the terminology in the plots? We may have got that
wrong (not quite sure whether the legend is yours or ours). If so would you
be happy to do a pull request?

Neil
