### ISSUE TITLE
GP model predict and its variances

### ISSUE THREAD

**Issue by kabdelfatah-zz** [SheffieldML/GPy#386]
Hi all,

I have a question about the returning variance from the prediction function.

Let us assume that we have an output Y with NxD (N is number of data points and D is the dimension of the output Y). When I tried to use model.predict(X_new, full_cov=False), It gives me variance Nx1 while I was expecting NxD (one variance for each output dimension in case these dimensions are independent).

Do you assume that for one output point, the **dimensions are independent and have the same variance**?
Or there is something that I am missing?

Thanks so much in advance

**Comment by mzwiessele** [comment]
Yes exactly, dimensions are assumes to be independent snd therefore we only return one for each dimension.

**Comment by kabdelfatah-zz** [comment]
Thanks for your quick reply.

**Comment by DragonCircle** [comment]
> Yes exactly, dimensions are assumes to be independent snd therefore we only return one for each dimension.
> 
> >

If Y_d are independent, why they have the same variance? I thought they should have independent variance? For each input x, how to get (1xD) variance output?

**Comment by ethanluoyc** [comment]
I am confused about this as well. I thought for each datapoint you should have variance for each dimension but currently one 1D is returned.

**Comment by afonari** [comment]
Old thread, but maybe someone can explain on a simple example:
```
import GPy
import numpy

rng = numpy.random.default_rng(123)

x_train, y_train = rng.uniform(size=(10, 5)), rng.uniform(size=(10, 3))
# print(x_train, y_train)
gpym = GPy.models.GPRegression(x_train, y_train)
gpym.optimize(messages=True)

x_pred = rng.uniform(size=(1, 5))
ret = gpym.predict(x_pred, full_cov=True)
print(ret)
```
Output:
```
(array([[0.43575577, 0.44205986, 0.47233959]]), array([[0.06096347]]))
```

The question is, how to get three values for the variance, currently it is only one value: `array([[0.06096347]])`.

Thanks!
