### ISSUE TITLE
Sensitivity calculation with input_sensitivity()

### ISSUE THREAD

**Issue by charles92** [SheffieldML/GPy#388]
Hi,

I believe there is a bug in the `input_sensitivity()` method of kernel classes. To reproduce, run:

```
import numpy as np
import GPy

k1 = GPy.kern.RBF(1, variance=1, lengthscale=2, active_dims=np.array([0]))
k2 = GPy.kern.RBF(1, variance=3, lengthscale=4, active_dims=np.array([2]))
ks = GPy.kern.Add([k1, k2])
kp = GPy.kern.Prod([k1, k2])

print k1.input_sensitivity() # [0.25], OK
print k2.input_sensitivity() # [0.1875], OK
print ks.input_sensitivity() # [0, 0], but should be [0.25, 0.1875]
print kp.input_sensitivity() # IndexError on i_s, but should be [0.25, 0.1875]
```

I guess the problem is related to `i_s = np.zeros((self.input_dim))` in the implementation of `input_sensitivity()`. Here we should really use the total dimensionality of the input space, rather than that of the sliced input space. But to solve this, one has to add a field in the `Kern` (or a reference to the full input `X`) so that `Kern` knows the total dimensionality.

Another related issue is in `input_sensitivity()` of `Prod` kernel. Please see comments below:

```
def input_sensitivity(self, summarize=True):
    if summarize:
        i_s = np.zeros((self.input_dim))
        # should be ones instead of zeros!
        for k in self.parts:
            i_s[k._all_dims_active] *= k.input_sensitivity(summarize)
            # otherwise this will always be zero!
        return i_s
    else:
        return super(Prod, self).input_sensitivity(summarize)
```

I'm a new user of GPy so let me know if I'm wrong.

Thanks for the great work!

Charles

**Comment by mzwiessele** [comment]
That is unfortunately expected... When you use the Add kernel, the added kernels become part of this add kernel. When you use those two kernels for the Prod kernel after, they become a part of the prod kernel and disconnect from the Add kernel. This means the former Add kernel is dysfunctional now... It has to do with the in memory work of the Parameterized class for speed. The tradeoff for the increase in speed is cases like this.

Try your example with copies of the kernels:

k1 = GPy.kern.RBF(1, variance=1, lengthscale=2, active_dims=np.array([0])) 
k2 = GPy.kern.RBF(1, variance=3, lengthscale=4, active_dims=np.array([2])) 
ks = GPy.kern.Add([k1, k2]) 
kp = GPy.kern.Prod([k1.copy(), k2.copy()]) 

Does that solve the problem?

**Comment by charles92** [comment]
Thanks for the explanation. Somehow `input_sensitivity()` is still not happy. I managed to produce a smaller test case:

```
import numpy as np
import GPy

k1 = GPy.kern.RBF(1, variance=1, lengthscale=2, active_dims=np.array([0]))
k2 = GPy.kern.RBF(1, variance=3, lengthscale=4, active_dims=np.array([2]))
ks = GPy.kern.Add([k1, k2])

print k1.input_sensitivity() # [0.25], OK
print k2.input_sensitivity() # [0.1875], OK
print ks.input_sensitivity() # Error, see below
```

And the last line produces the following error:

```
Traceback (most recent call last):
  File "sensitivity_bug.py", line 11, in <module>
    print ks.input_sensitivity()
  File "/Users/qiurui/anaconda/lib/python2.7/site-packages/GPy/kern/src/add.py", line 263, in input_sensitivity
    i_s[k._all_dims_active] += k.input_sensitivity(summarize)
IndexError: index 2 is out of bounds for axis 1 with size 2
```

**Comment by mzwiessele** [comment]
Nice, this looks to be a bug. I'll give it a go. If you use active_dims=[1], does it work then?

**Comment by charles92** [comment]
Yes, it does work if `active_dims=[1]`, for `GPy.kern.Add` kernel.

However, for `GPy.kern.Prod`, the same code will return `[0, 0]`, which I don't think is correct. Code:

```
import numpy as np
import GPy

k1 = GPy.kern.RBF(1, variance=1, lengthscale=2, active_dims=np.array([0]))
k2 = GPy.kern.RBF(1, variance=3, lengthscale=4, active_dims=np.array([1]))
kp = GPy.kern.Prod([k1, k2])

print k1.input_sensitivity() # [0.25], OK
print k2.input_sensitivity() # [0.1875], OK
print kp.input_sensitivity() # [0, 0], probably not right
```
