### ISSUE TITLE
Heavy Memory Usage when importing GPy

### ISSUE THREAD

**Issue by tsterbak** [SheffieldML/GPy#389]
Hi,
I installed GPy under Anaconda with pip in python 3.4.3 on Windows 7.
If I want to follow the tutorial and import GPy, this line uses approximatly 4GB of RAM...
Is this as it's used to be or are there any troubles in my setup?

Regards,
Tobias

**Comment by mzwiessele** [comment]
Could you give more details to work on? I am not experiencing this problem when importing GPy...

**Comment by tsterbak** [comment]
Thank you for your reply.

There is not much more detail I can give you.
So basically I install GPy with pip under Windows 7. I didn't encounter any trouble in this process.
Then I open the Anaconda Console and type "import GPy" and see my memory consumption increase around 4GB. The import works properly besides of that.
Looking forward to your reply,
Tobias

**Comment by mzwiessele** [comment]
we updated GPy, could you give it a shot?

**Comment by tsterbak** [comment]
As far as I can see this didn't solve the problem...

**Comment by mzwiessele** [comment]
I was afraid it wouldn't.... We still have not found the reason for any of this. The main problem is, that we do not use Windows ourselves so no one feels stressed to look too deep into it. 

Have you found some more details on what exactly is causing the memory to rise? Maybe it is the plotting library being loaded? You can switch it off in the gpy config file ~.config/gpy/user.cfg (or similar).

**Comment by mzwiessele** [comment]
Have you tried importing matplotlib on its own? Does it increase the memory usage?
