### ISSUE TITLE
LinAlgError (coregionalized GP regression with max-EP alternation)

### ISSUE THREAD

**Issue by elBrutale** [SheffieldML/GPy#390]
I am trying to forecast multiple time series with coregionalized GP regression, using GPy. Model set up in the following way:
1) Bias kernel for different means
2) RBF kernel for non-periodic fluctuations
3) StdPeriod or PeriodicExponential for seasonalities

I want to alternate between optimization and expectation propagation for a few iterations to get a better estimate of mu and var for underlying processes, however I always get the same error after the first optimization:

> EM step: 1
> EM step: 2
>  C:\Users\zvizdic\AppData\Local\Continuum\Anaconda\lib\site-packages\GPy\kern\src\standard_periodic.py:113: RuntimeWarning:overflow encountered in divide
>  C:\Users\zvizdic\AppData\Local\Continuum\Anaconda\lib\site-packages\GPy\kern\src\standard_periodic.py:114: RuntimeWarning:invalid value encountered in sin
> Traceback (most recent call last):
>   File "GPy_issue.py", line 80, in <module>
>     model = GPy.models.GPRegression(X, Y, kern, noise_var = noiseVar)
>   File "C:\Users\zvizdic\AppData\Local\Continuum\Anaconda\lib\site-packages\paramz\parameterized.py", line 54, in **call**
>     self.initialize_parameter()
>   File "C:\Users\zvizdic\AppData\Local\Continuum\Anaconda\lib\site-packages\paramz\core\parameter_core.py", line 330, in initialize_parameter
>     self.parameters_changed()
>   File "C:\Users\zvizdic\AppData\Local\Continuum\Anaconda\lib\site-packages\GPy\core\gp.py", line 192, in parameters_changed
>     self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.likelihood, self.Y_normalized, self.mean_function, self.Y_metadata)
>   File "C:\Users\zvizdic\AppData\Local\Continuum\Anaconda\lib\site-packages\GPy\inference\latent_function_inference\exact_gaussian_inference.py", line 45, in inference
>     Wi, LW, LWi, W_logdet = pdinv(Ky)
>   File "C:\Users\zvizdic\AppData\Local\Continuum\Anaconda\lib\site-packages\GPy\util\linalg.py", line 210, in pdinv
>     L = jitchol(A, *args)
>   File "C:\Users\zvizdic\AppData\Local\Continuum\Anaconda\lib\site-packages\GPy\util\linalg.py", line 78, in jitchol
>     raise linalg.LinAlgError("not positive definite, even with jitter.")
> numpy.linalg.linalg.LinAlgError: not positive definite, even with jitter.

My code attached (GPy issue.zip)
[GPy_issue.zip](https://github.com/SheffieldML/GPy/files/272833/GPy_issue.zip)

This only happens when I try to include periodic kernels in the model, RBF + Bias works fine. Plus, my GPy is up to date with the latest version of GPy on GitHub.

Thanks a lot for any insights on how to avoid invalid values/overflows/nonPSD covariance matrices when using Periodic kernels in such a setup.

Regards,

Ermin

**Comment by adrian-golian** [comment]
RBF + Bias fails in my case. On clearly non-singular X, y.

> Traceback (most recent call last):
>   File "model.py", line 80, in <module>
>     gp.optimize()
>   File "/usr/local/lib/python2.7/dist-packages/GPy/core/gp.py", line 551, in optimize
>     super(GP, self).optimize(optimizer, start, messages, max_iters, ipython_notebook, clear_after_finish, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/paramz/model.py", line 108, in optimize
>     self.optimizer_array = opt.x_opt
>   File "/usr/local/lib/python2.7/dist-packages/paramz/parameterized.py", line 325, in **setattr**
>     return object.**setattr**(self, name, val);
>   File "/usr/local/lib/python2.7/dist-packages/paramz/core/parameter_core.py", line 118, in optimizer_array
>     self.trigger_update()
>   File "/usr/local/lib/python2.7/dist-packages/paramz/core/updateable.py", line 79, in trigger_update
>     self._trigger_params_changed(trigger_parent)
>   File "/usr/local/lib/python2.7/dist-packages/paramz/core/parameter_core.py", line 128, in _trigger_params_changed
>     self.notify_observers(None, None if trigger_parent else -np.inf)
>   File "/usr/local/lib/python2.7/dist-packages/paramz/core/observable.py", line 91, in notify_observers
>     [callble(self, which=which) for _, _, callble in self.observers]
>   File "/usr/local/lib/python2.7/dist-packages/paramz/core/parameter_core.py", line 497, in _parameters_changed_notification
>     self.parameters_changed()
>   File "/usr/local/lib/python2.7/dist-packages/GPy/core/gp.py", line 190, in parameters_changed
>     self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.likelihood, self.Y_normalized, self.mean_function, self.Y_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/GPy/inference/latent_function_inference/exact_gaussian_inference.py", line 45, in inference
>     Wi, LW, LWi, W_logdet = pdinv(Ky)
>   File "/usr/local/lib/python2.7/dist-packages/GPy/util/linalg.py", line 208, in pdinv
>     L = jitchol(A, *args)
>   File "/usr/local/lib/python2.7/dist-packages/GPy/util/linalg.py", line 76, in jitchol
>     raise linalg.LinAlgError("not positive definite, even with jitter.")
> numpy.linalg.linalg.LinAlgError: not positive definite, even with jitter.

**Comment by mzwiessele** [comment]
I think this is one for the mailing list: gpy-users@lists.shef.ac.uk
