### ISSUE TITLE
Derivative of function as a constraint

### ISSUE THREAD

**Issue by lkoppens** [SheffieldML/GPy#394]
Not an issue as much as a question:
Is it possible to use the derivative of the resulting function as a constraint when fitting data? For example, if I want to ensure that the resulting y of a GP always decreases for an increase in x.

**Comment by mzwiessele** [comment]
You could give it a shot, creating a new inference method, which takes gradients into account. I guess you would need a new kernel, too, which can compute the gradient covariance.

**Comment by avehtari** [comment]
This will be available in GPy later this year.

**Comment by tinutjoy** [comment]
@avehtari, is this available in the current version? Or any hints on using monotonicity information? 
Thank you,

**Comment by esiivola** [comment]
@tinutjoy I will make a pull request in December, but you can use my branch until then: https://github.com/esiivola/GPYgradients/tree/grad_obs

There is a tutorial notebook here: https://github.com/esiivola/GPYgradients/blob/grad_obs/GPy/examples/derivatives_demo.ipynb

For using monotonicity, you should add virtual derivative observations as in Riihimäki and Vehtari (2010) proceedings.mlr.press/v9/riihimaki10a/riihimaki10a.pdf

**Comment by tinutjoy** [comment]
@esilviola Thank you! I will try your branch.

**Comment by nxtruong** [comment]
Has this feature been implemented in GPy? @avehtari said it would be available in late 2017.

**Comment by ekalosak** [comment]
Stale.
