### ISSUE TITLE
GP-LVM

### ISSUE THREAD

**Issue by Homesh01** [SheffieldML/GPy#395]
I've started reading on how to use GPs for dimensionality reduction. In the example notebook:

```
http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/MagnificationFactor.ipynb
```

the variables represented on the lower dimensional space are `m_gplvm.X`

I'm wondering when new data becomes available, say `Y_new`, how would I find it's representation using the same transformation that produced `m_gplvm.X`. (for normal PCA, one use model.fit, followed by model.transform).

**Comment by zhenwendai** [comment]
You can use the function: m_gplvm.infer_newX(Y_new). It is a 
gradient-based optimization. The return values are a tuple: the first 
entry is the inferred X_new and the second entry is the model created 
for this inference.

Zhenwen
