### ISSUE TITLE
Running GPy on databricks

### ISSUE THREAD

**Issue by avloss** [SheffieldML/GPy#400]
```
RuntimeError: (RuntimeError('could not create GdkCursor object',), <function subimport at 0x7f9099b85848>, ('GPy',))
```

job fails when trying to execute GPy on databricks platform.

```
import GPy
GPy.plotting.change_plotting_library('none')
```

 doing this doesn't help

**Comment by mzwiessele** [comment]
I am not familiar with databricks, but if it is the plotting you can change the plotting library in the .config file. It is located in ~/.config/GPy/user.cfg.

**Comment by mzwiessele** [comment]
any luck?
