### ISSUE TITLE
Plotly offline plotting option

### ISSUE THREAD

**Issue by mikeschaekermann** [SheffieldML/GPy#404]
I would love to have an option for using Plotly in offline mode so that I don't have to create a user account on Plotly and graphs do not automatically get uploaded to the Plotly cloud. On the one hand, I love Plotly and all its beautifully designed plotting functions, but on the other hand I cannot use it for some of the sensitive data that I am working with because this data may not be transferred to external servers.

Offline plotting in Plotly: https://plot.ly/python/getting-started/#initialization-for-offline-plotting

**Comment by mzwiessele** [comment]
We are very happy to see people engaged in this. If you want to give it 
a shot, put up a pull request with the option, see

https://help.github.com/articles/fork-a-repo/
and
https://help.github.com/articles/creating-a-pull-request/

**Comment by mzwiessele** [comment]
Any progress updates?

**Comment by mikeschaekermann** [comment]
Sorry, I haven't found the time to do this yet. Currently quite busy with a work project.

**Comment by alexfeld** [comment]
I've just added a pull request that I believe addresses this issue. The offline plots mostly work for me albeit with a few issues. I think these issues are `plotly.py`'s though.
