### ISSUE TITLE
Potential typo in GPCoregionalizedRegression func

### ISSUE THREAD

**Issue by NMRobert** [SheffieldML/GPy#405]
https://github.com/SheffieldML/GPy/blob/309dd77ee5dbe232682d125bdf9eee106859c633/GPy/models/gp_coregionalized_regression.py#L41

I suspect that the line
`kernel = util.multioutput.ICM(input_dim=X.shape[1]-1, num_outputs=Ny, kernel=kernel, W_rank=1,name=kernel_name)
`
may have an unintentional indent, causing unintended behaviour when a kernel is passed in to GPCoregionalizedRegression. If you provide a kernel to the call to GPCoregionalizedRegression(GP), this results in the provided kernel being used for the regression, instead of util.multioutput.ICM (with the provided kernel being used for the coregionalization), as the util.multioutput.ICM call only occurs when Kernel = None.

It seems likely that this is simply a typo, as my guess at the intended behaviour is simply to set the kernel to a RBF default when none is provided.

**Comment by ric70x7** [comment]
Thanks Robert,
It's not a typo. Without the indent, you can only have ICM models. With the
indent you can build a more elaborate kernel, already coregionalized, and
pass it as a parameter to have an LCM.
I've changed the description of the kernel parameters to express that the
kernel passed should be already Coregionalized.
Best,
Ricardo

2016-06-24 10:05 GMT-07:00 NMRobert notifications@github.com:

**Comment by NMRobert** [comment]
Ah, thank you for the clarification.

Cheers,
Nicholas
