### ISSUE TITLE
couldn't import GPy (Python 2.7 ,Enthought Canopy IDE , windows 10)

### ISSUE THREAD

**Issue by kalyanbhetwal** [SheffieldML/GPy#407]
from . import core
from GPy.core.model import Model
from .parameterization.priorizable import Priorizable
from .param import Param
from paramz import Param
from . import optimization
from .optimization import *
from scipy import optimize
from ._minimize import *
from ._trustregion_dogleg import _minimize_dogleg
import scipy.linalg
from .misc import *
from scipy.linalg import _fblas

ImportError: DLL load failed: The specified procedure could not be found. 

After updating scipy in canopy i installed GPy  successfully  using PIP. But when I try to import above error occuired

**Comment by mzwiessele** [comment]
Hi sry for the delay.
We are trying to upload the newest versions right now to pip (including the windows binaries).

@mikecroucher do you have news on this?

**Comment by kalyanbhetwal** [comment]
Thanks Mike for replying.

I solved the import error problem. All I did is to remove official package of numpy and scipy and install unofficial library. 

But the thing is that although I   successfully  imported it, new set of error arise as i test run it.

I hope your binary comes very soon .I need it for my university project  and the dead line is approaching nearer.

Thanks again

**Comment by mikecroucher** [comment]
The binary is now available for Python 2.7 on 64bit windows. 
Hopefully this is your use case?

We are starting to use Appveyor to do these builds for us so things should steadily improve on Windows.

**Comment by kalyanbhetwal** [comment]
Thanks alot.

**Comment by mzwiessele** [comment]
fixed by #413
