### ISSUE TITLE
ImportError: No module named plotly

### ISSUE THREAD

**Issue by gunasekarvit** [SheffieldML/GPy#409]
Hi, gpy users,

I'm new to the gpy library.
My python version 2.7.11
Anaconda (4.0.0) 64-bit
Ipython 4.1.2
I have installed GPy using "pip install https://github.com/SheffieldML/GPy/archive/devel.zip"

When I'm trying to run the ipython notebook 'basic_gp', I got the following error.

Issue 1:
GPy.plotting.change_plotting_library('plotly')

---

ImportError                               Traceback (most recent call last)
<ipython-input-14-ac4ab676071a> in <module>()
----> 1 GPy.plotting.change_plotting_library('plotly')

C:\Anaconda2\lib\site-packages\GPy\plotting__init__.pyc in change_plotting_library(lib)
     21             current_lib[0] = MatplotlibPlots()
     22         if lib == 'plotly':
---> 23             import plotly
     24             from .plotly_dep.plot_definitions import PlotlyPlots
     25             current_lib[0] = PlotlyPlots()

ImportError: No module named plotly

Issue 2:

fig = m.plot()
GPy.plotting.show(fig, filename='basic_gp_regression_notebook')

---

TypeError                                 Traceback (most recent call last)
<ipython-input-11-c03c34ae6d1f> in <module>()
      2 
      3 fig = m.plot()
----> 4 GPy.plotting.show(fig, filename='basic_gp_regression_notebook')
      5 

C:\Anaconda2\lib\site-packages\GPy\plotting__init__.pyc in show(figure, *_kwargs)
    115     for showing/drawing a figure.
    116     """
--> 117     return plotting_library().show_canvas(figure, *_kwargs)
    118 
    119 

TypeError: show_canvas() got an unexpected keyword argument 'filename'

---

Please advice in this regard..

**Comment by mzwiessele** [comment]
The demo is to show you can switch the library. You do not have to do so. Just switch or delete the the library change and it should work. If you want to use plotly, you can install it and it will plot with plotly.

**Comment by gunasekarvit** [comment]
Thanks for the solution i solved that error. 

Now i have given this command to view the mean and confidence.I got below error :

fig = m.plot()
GPy.plotting.show(fig, filename='basic_gp_regression_notebook')

This is the format of your plot grid:
[ (1,1) x1,y1 ]

---

PlotlyLocalCredentialsError               Traceback (most recent call last)
<ipython-input-10-51e857559857> in <module>()
      1 fig = m.plot()
----> 2 GPy.plotting.show(fig, filename='basic_gp_regression_notebook')

C:\Anaconda2\lib\site-packages\GPy\plotting__init__.pyc in show(figure, *_kwargs)
    115     for showing/drawing a figure.
    116     """
--> 117     return plotting_library().show_canvas(figure, *_kwargs)
    118 
    119 

C:\Anaconda2\lib\site-packages\GPy\plotting\plotly_dep\plot_definitions.pyc in show_canvas(self, canvas, filename, **kwargs)
    121         from ..gpy_plot.plot_util import in_ipynb
    122         if in_ipynb():
--> 123             return py.iplot(figure, filename=filename)#self.current_states[hex(id(figure))]['filename'])
    124         else:
    125             return py.plot(figure, filename=filename)#self.current_states[hex(id(figure))]['filename'])

C:\Anaconda2\lib\site-packages\plotly\plotly\plotly.pyc in iplot(figure_or_data, *_plot_options)
    149     if 'auto_open' not in plot_options:
    150         plot_options['auto_open'] = False
--> 151     url = plot(figure_or_data, *_plot_options)
    152 
    153     if isinstance(figure_or_data, dict):

C:\Anaconda2\lib\site-packages\plotly\plotly\plotly.pyc in plot(figure_or_data, validate, *_plot_options)
    239 
    240     plot_options = _plot_option_logic(plot_options)
--> 241     res = _send_to_plotly(figure, *_plot_options)
    242     if res['error'] == '':
    243         if plot_options['auto_open']:

C:\Anaconda2\lib\site-packages\plotly\plotly\plotly.pyc in _send_to_plotly(figure, **plot_options)
   1401                       cls=utils.PlotlyJSONEncoder)
   1402     credentials = get_credentials()
-> 1403     validate_credentials(credentials)
   1404     username = credentials['username']
   1405     api_key = credentials['api_key']

C:\Anaconda2\lib\site-packages\plotly\plotly\plotly.pyc in validate_credentials(credentials)
   1350     api_key = credentials.get('api_key')
   1351     if not username or not api_key:
-> 1352         raise exceptions.PlotlyLocalCredentialsError()
   1353 
   1354 

PlotlyLocalCredentialsError: 
Couldn't find a 'username', 'api-key' pair for you on your local machine. To sign in temporarily (until you stop running Python), run:

> > > import plotly.plotly as py
> > > py.sign_in('username', 'api_key')

Even better, save your credentials permanently using the 'tools' module:

> > > import plotly.tools as tls
> > > tls.set_credentials_file(username='username', api_key='api-key')

For more help, see https://plot.ly/python
