### ISSUE TITLE
Square link function in Cox process

### ISSUE THREAD

**Issue by sethnabarro** [SheffieldML/GPy#410]
Hi all,

I'm interested in implementing a Poisson process driven by a latent f~GP, where lambda=f^2 as in Lloyd et al 2015 (http://www.robots.ox.ac.uk/~sjrob/Pubs/lloyd15vbgpmpp.pdf). Is this possible in the GPy framework, and if so please could you suggest a method? 

Many thanks,
Seth

**Comment by sethnabarro** [comment]
Hi guys, I actually mean a square root link function. Apologies if this was confusing. Any help much appreciated. Thanks

**Comment by mzwiessele** [comment]
Have a look at the link function implementations:
https://github.com/SheffieldML/GPy/blob/devel/GPy/likelihoods/link_functions.py

this should help you to implement the necessary functions for it to work. You have to implement the transformation `transf` and its gradients (see GPTransformation and others).

Looking forward to a pull request : )

**Comment by sethnabarro** [comment]
Good stuff, will look into it. Thanks Max

**Comment by mathDR** [comment]
Hey @sethnabarro did you make any progress on this?  I was looking to implement the same thing.

**Comment by sethnabarro** [comment]
Hi @mathDR, I had a go at implementing but couldn't seem to get meaningful results. I couldn't deduce whether this was a result of poor implementation or the square link function was not suited to the dataset I was considering (so didn't submit for a pull request). Can send you the link function and gradients if you're interested.

**Comment by mathDR** [comment]
Sure!  It would still be of use to do a PR for what you have implemented.  A Square link function would be a nice add (IMHO)

**Comment by RuiZhang2016** [comment]
I implemented one with EP and it works on Poisson regression. I don't how to share it. BTW, using a non-zero mean function may give a more meaningful result.
