### ISSUE TITLE
m.optimize_restarts(num_restarts=10) picking wrong model?

### ISSUE THREAD

**Issue by ahmasoh1992** [SheffieldML/GPy#411]
Hi everyone, 

I have come across an issue which is apparent when I run the following:

kern = GPy.kern.Exponential(1) + GPy.kern.White(1) +  GPy.kern.Exponential(1)
m = GPy.models.GPRegression(x,y,kern)  #(x and y are just the standard airline datasets)
m.optimize_restarts(num_restarts=10)
loglikelihood = m.objective_function()

I get the following results:
Optimization restart 1/10, f = -92.8587214095
Optimization restart 2/10, f = -92.8587212115
Optimization restart 3/10, f = -92.8587214287
Optimization restart 4/10, f = -92.8587214269
Optimization restart 5/10, f = -92.8587214288 ***************
Optimization restart 6/10, f = -92.8587149035
Optimization restart 7/10, f = -92.858721386
Optimization restart 8/10, f = -92.8587214287
Optimization restart 9/10, f = -92.8587214259
Optimization restart 10/10, f = -92.858721418

LL: -92.8587214288

However, this doesn't make sense because the model chosen has the most negative value. One would assume that we are attempting to maximise the likelihood of the timeseries (hence get the likelihood closer to 1), and therefore, attempt to maximise the log-likelihood (hence get the log likelihood closer to 0 as maximise chance of event = log(1)=0 ). Log of number between 0 and 1 is negative, so we would hope to choose the model with the log likelihood closest to 0, which is not happening in the above case. 

Any help would be appreciated! Thanks!

**Comment by Dapid** [comment]
The objective function is the _negative_ log likelihood.

For historical reasons, numerical optimisation is usually approached as a minimisation rather than maximisation of the function.

You can see the value of the objective function before and after the optimisation, and see how well it fits your data.

**Comment by ahmasoh1992** [comment]
Hi Dapid, thanks for the swift response!

I believe that the value of the _negative_ log likelihood should be positive (which is then minimised) because of the following intuition:

1 - The likelihood of an event has a probability between 0 and 1
2 - The log likelihood of an event has a probability between -inf and 0
3 - As such, the negative of the log likelihood has a range between 0 and infinity. 

Therefore, I do not see why the above values are negative. I agree that we should minimise the negative log likelihood, but if the value of the negative log likelihood is negative, the log likelihood is positive, so the probability of an event will be much greater than 1, which is impossible, right?

**Comment by lawrennd** [comment]
You are thinking of discrete probabilities, continuous probabilities go negative very often, because they are not real probabilities, but probability density functions being evaluated at a point (rather than across a range).

**Comment by ahmasoh1992** [comment]
Hi Neil, 

Thanks for that explanation.

I'm still questioning this because in the equation for the calculation of the log marginal likelihood (Rasmussen and Williams, page 9 equation 2.30):

Let K_adj= K + sigma_Identity
log p(y|x) = -0.5_y(K_adj^-1)y - 0.5log|K_adj| - const 

In the case of GP's, K_adj has to be a positive definite, therefore the equation is strictly negative (bounded at the upper limit by 0). Given this, I'm struggling to see how the log marginal likelihood can be positive.

Thanks

**Comment by lawrennd** [comment]
As the determinant approaches zero, the logarithm can be severely negative,
dominating the equation.

**Comment by ahmasoh1992** [comment]
Ah I completely missed that, thanks so much!
