### ISSUE TITLE
Kernel plotting raising an AttributeError

### ISSUE THREAD

**Issue by vvanirudh** [SheffieldML/GPy#424]
When I define a RBF kernel using
`K = GPy.kern.RBF(input_dim=1, variance=1, lengthscale=1)`
and try to plot the kernel using
`K.plot()`
it raises an AttributeError as follows:
`AttributeError: 'numpy.ndarray' object has no attribute 'cache'`

The entire traceback is as follows : 

AttributeError                            Traceback (most recent call last)
<ipython-input-13-9ea7238778c9> in <module>()
----> 1 K.plot()

/home/anirudh/.virtualenvs/dev/local/lib/python2.7/site-packages/GPy/plotting/**init**.pyc in deprecate_plot(self, _args, *_kwargs)
     94             import warnings
     95             warnings.warn(DeprecationWarning('Kern.plot is being deprecated and will not be available in the 1.0 release. Use Kern.plot_covariance instead'))
---> 96             return self.plot_covariance(_args, *_kwargs)
     97         Kern.plot = deprecate_plot
     98         Kern.plot_ARD = gpy_plot.kernel_plots.plot_ARD

/home/anirudh/.virtualenvs/dev/local/lib/python2.7/site-packages/GPy/plotting/gpy_plot/kernel_plots.pyc in plot_covariance(kernel, x, label, plot_limits, visible_dims, resolution, projection, levels, *_kwargs)
    108     elif isinstance(x, Number):
    109         x = np.ones((1, kernel._effective_input_dim))_x
--> 110     K = kernel.K(Xgrid, x)
    111 
    112     if projection == '3d':

/home/anirudh/.virtualenvs/dev/local/lib/python2.7/site-packages/GPy/kern/src/kernel_slice_operations.pyc in wrap(self, X, X2, _a, *_kw)
     82     @wraps(f)
     83     def wrap(self, X, X2 = None, _a, *_kw):
---> 84         with _Slice_wrap(self, X, X2) as s:
     85             ret = f(self, s.X, s.X2, _a, *_kw)
     86         return ret

/home/anirudh/.virtualenvs/dev/local/lib/python2.7/site-packages/GPy/kern/src/kernel_slice_operations.pyc in **init**(self, k, X, X2, diag, ret_shape)
     51         if (self.k._all_dims_active is not None) and (self.k._sliced_X == 0):
     52             self.k._check_active_dims(X)
---> 53             self.X = self.k._slice_X(X)
     54             self.X2 = self.k._slice_X(X2) if X2 is not None else X2
     55             self.ret = True

/home/anirudh/.virtualenvs/dev/local/lib/python2.7/site-packages/paramz-0.5.6-py2.7.egg/paramz/caching.pyc in g(obj, _args, *_kw)
    274             obj = args[0]
    275             if not hasattr(obj, 'cache'):
--> 276                 obj.cache = FunctionCache()
    277             cache = obj.cache
    278             if self.f in cache:

AttributeError: 'numpy.ndarray' object has no attribute 'cache'

**Comment by vvanirudh** [comment]
I am using numpy version 1.12.0

**Comment by mzwiessele** [comment]
Could you try updated paramz? The underlying parameterized package for GPy? It seems to be somehow connected with this. If this does not work, we will ahve to figure out what is going on. Habe you recently updated GPy? There is a new version out :)

**Comment by vvanirudh** [comment]
I am using the most recent version of paramz (0.5.6) and the most recent version of GPy (the development version - 1.2.1). 

I still get the same error when I try to plot the kernel.

**Comment by vvanirudh** [comment]
I tried building both GPy and paramz from the source (from respective github repositories), essentially ensuring that they are both in their most recent versions. But I still get the same error.

**Comment by mzwiessele** [comment]
The automatic builds are in place, so you do not need to build things yourself anymore, no hassle there ;) I will have a thorogh look, maybe there is some other thing going on there. Thanks for the update!

**Comment by vvanirudh** [comment]
Thanks. Let me know if you figure something out.

**Comment by mzwiessele** [comment]
I cannot reproduce the error.

I am running numpy 1.11, though maybe that is the problem?

**Comment by vvanirudh** [comment]
I tried reinstalling everything again.

Numpy = 1.11.0
Scipy = 0.18.0
Paramz = 0.6.6
GPy = 1.4.0
(Python = 2.7.6)

I still get the same error. 

/home/anirudh/.virtualenvs/dev/local/lib/python2.7/site-packages/paramz/caching.pyc in g(obj, _args, *_kw)
    274             obj = args[0]
    275             if not hasattr(obj, 'cache'):
--> 276                 obj.cache = FunctionCache()
    277             cache = obj.cache
    278             if self.f in cache:

AttributeError: 'numpy.ndarray' object has no attribute 'cache'

**Comment by vvanirudh** [comment]
On a side note, GPy version 0.8.8 works perfectly (but doesn't have the plotting functionality of GPy 1.4.0 and other new functionalities, which I need)

**Comment by vvanirudh** [comment]
Okay final update: I resolved the error by creating a new virtualenv (clean without any site packages) and reinstalled everything from numpy to GPy. It's working now.

Thanks for the response and I hope I knew what caused the error before, but unfortunately I don't.
