### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by MinskAndBoo** [SheffieldML/GPy#427]
Hi, having had some success in Linux Mint (until it ground to an inexplicable multi-threaded halt), I am trying to install under Windows and receiving this error:

"
C:\Anaconda3>pip install GPy
Collecting GPy
  Using cached GPy-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DOUG_H~1\AppData\Local\Temp\pip-build-zw17cdfx\GPy\setup.py
", line 41, in <module>
        import numpy as np
      File "C:\Anaconda3\lib\site-packages\numpy__init__.py", line 180, in <mod
ule>
        from . import add_newdocs
      File "C:\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <m
odule>
        from numpy.lib import add_newdoc
      File "C:\Anaconda3\lib\site-packages\numpy\lib__init__.py", line 8, in <m
odule>
        from .type_check import *
      File "C:\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in
 <module>
        import numpy.core.numeric as _nx
      File "C:\Anaconda3\lib\site-packages\numpy\core__init__.py", line 14, in
<module>
        from . import multiarray
    ImportError: DLL load failed: The specified module could not be found.

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\DOUG_H~1
\AppData\Local\Temp\pip-build-zw17cdfx\GPy\
"

I then tried to run "GPy-1.4.0.win-amd64-py3.5.exe" from:
https://pypi.python.org/pypi/GPy

This gave the message "Python 3.5-32 required, which was not found in the registry. I had Anaconda x64 installed. I re-ran with Anaconda x86 installed and got the same error message.

Maybe I was missing a shell restart after the x64 install? Is the error message out of date?

I also found this post:
https://github.com/SheffieldML/GPy/issues/369
Is this the recommended method?

**Comment by mzwiessele** [comment]
This seems to be a numpy error. I'd suggest you remove all of python and make a new install. That seems to have helped others, when encountering those kind of problems.

Sry for not having an immediate answer :/

**Comment by MinskAndBoo** [comment]
You're correct, this was an installation issue. I suspect this was caused by a legacy Enthought Canopy install which was pathologically difficult to remove. Thanks, resolved.
