### ISSUE TITLE
Persisting bgplvm

### ISSUE THREAD

**Issue by MinskAndBoo** [SheffieldML/GPy#428]
Hi, when saving and loading a bayesian_gplvm_minibatch per the instructions on the main page, the model is not fully rehydrated. Specifics that I noticed are that the m.rbf.variance and m.Gaussian_noise.variance defaulted to 1.0.

These variables don't appear to exist before m.initialize_parameter(), but modifying them after initialize does not rectify the issue.

Doug

**Comment by mzwiessele** [comment]
Could you send over a minimalistic example so I can have a look? There is always something slipping the cracks of the tests, I'm afraid.

**Comment by MinskAndBoo** [comment]
The culprit is Initialize = False. When set to true (default) it works.

``` python
import numpy as np
import GPy

X = np.asarray([[0, 1], [1, 2], [1, 3]])

kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)

m = GPy.models.bayesian_gplvm_minibatch.BayesianGPLVMMiniBatch(X, 2, num_inducing = 5, 
                                                                    missing_data = True, 
                                                                    batchsize = 10, 
                                                                    stochastic = False, 
                                                                    initialize = True, 
                                                                    init = "PCA")
m.Gaussian_noise.variance = 5.55555
m.rbf.variance = 1.11111

print(m)
print("")
print("Initial model")

np.save('test.npy', m.param_array)
m_test = GPy.models.bayesian_gplvm_minibatch.BayesianGPLVMMiniBatch(X, 2, num_inducing = 5, 
                                                                    missing_data = True, 
                                                                    batchsize = 10, 
                                                                    stochastic = False, 
                                                                    initialize = False, 
                                                                    init = "PCA")
m_test[:] = np.load('test.npy')
m_test.initialize_parameter()

print(m_test)
print("")
print("Test failed")

m_test2 = GPy.models.bayesian_gplvm_minibatch.BayesianGPLVMMiniBatch(X, 2, num_inducing = 5, 
                                                                    missing_data = True, 
                                                                    batchsize = 10, 
                                                                    stochastic = False, 
                                                                    initialize = True, 
                                                                    init = "PCA")
m_test2[:] = np.load('test.npy')
m_test2.initialize_parameter()

print(m_test2)
print("")
print("Test passed")
```

Output:

Name : bayesian gplvm
Objective : 22.652933673391544
Number of Parameters : 22
Number of Optimization Parameters : 22
Updates : True
Parameters:
  bayesian_gplvm.          |    value  |  constraints  |  priors
  latent_space.mean        |   (3, 2)  |               |  
  latent_space.variance    |   (3, 2)  |      +ve      |  
  inducing_inputs          |   (3, 2)  |               |  
  rbf.variance             |  1.11111  |      +ve      |  
  rbf.lengthscale          |     (2,)  |      +ve      |  
  Gaussian_noise.variance  |  5.55555  |      +ve      |        

Initial model

Name : bayesian gplvm
Objective : 18.91244818035483
Number of Parameters : 22
Number of Optimization Parameters : 22
Updates : True
Parameters:
  bayesian_gplvm.          |   value  |  constraints  |  priors
  latent_space.mean        |  (3, 2)  |               |  
  latent_space.variance    |  (3, 2)  |      +ve      |  
  inducing_inputs          |  (3, 2)  |               |  
  rbf.variance             |     1.0  |      +ve      |  
  rbf.lengthscale          |    (2,)  |      +ve      |  
  Gaussian_noise.variance  |     1.0  |      +ve      |        

Test failed

Name : bayesian gplvm
Objective : 22.652933673391544
Number of Parameters : 22
Number of Optimization Parameters : 22
Updates : True
Parameters:
  bayesian_gplvm.          |    value  |  constraints  |  priors
  latent_space.mean        |   (3, 2)  |               |  
  latent_space.variance    |   (3, 2)  |      +ve      |  
  inducing_inputs          |   (3, 2)  |               |  
  rbf.variance             |  1.11111  |      +ve      |  
  rbf.lengthscale          |     (2,)  |      +ve      |  
  Gaussian_noise.variance  |  5.55555  |      +ve      |        

Test passed
 C:\Anaconda3\lib\site-packages\paramz\parameterized.py:57: RuntimeWarning:Don't forget to initialize by self.initialize_parameter()!

**Comment by mzwiessele** [comment]
Is that in the docs? The intialize=false?

**Comment by MinskAndBoo** [comment]
Yes, at https://github.com/SheffieldML/GPy
"Saving models in a consistent way across versions"

``` python
# let X, Y be data loaded above
# Model creation:
m = GPy.models.GPRegression(X, Y)
m.optimize()
# 1: Saving a model:
np.save('model_save.npy', m.param_array)
# 2: loading a model
# Model creation, without initialization:
m = GPy.models(GPRegression(X,Y,initialize=False)
m[:] = np.load('model_save.npy')
m.initialize_parameter()
print m
```

Incidentally, the example code isn't valid at m = GPy.models(GPRegression(X,Y,initialize=False)

**Comment by mzwiessele** [comment]
Hmm that looks alright (except the mistake with the dot). Have you forgot to initialize the model m.initialize_parameter() after setting the parameters?
