### ISSUE TITLE
LogisticBasisFuncKernel doesn't allow negative values for slope

### ISSUE THREAD

**Issue by bwengals** [SheffieldML/GPy#430]
Hi GPy devs,

The LogisticBasisFuncKernel currently only allows positive values for the slope parameter.  This means that the function can only slope up from left to right, not also down from left to right.  Checking the source,  at /GPy/kern/src/basis_funcs.py, I think lines 145 and 147 are where the issue is. 

I'm not sure how the Param class works completely, but removing the Logsumexp() argument seemed to do the trick.

self.slope = Param('slope', slope, Logexp())  -> self.slope = Param('slope', slope)

Is this correct?  Would be happy to submit a PR --- is this the right usage of Param?

**Comment by mzwiessele** [comment]
Sounds exactly right, good spotting!
