### ISSUE TITLE
newbie to GP and GPy, need some help about the training data size

### ISSUE THREAD

**Issue by laobajiaozi** [SheffieldML/GPy#436]
hi, i am a  new guy to gp and gpy ,trying to use gpy to make a regression.  
my traing dataset is 5 dim. the sample number is as large as 10000. when optimize,  it eat up 5G of  the memory , then ,it kill the PC, no keyboard and mouse could move.
when I reduce the sample number to 5000, it works fine.

so my question is that  GP or GPy not suit for big data?  I know something about cnn lstm, they can do huge data such as 999999 data is ok ,just batch by batch training them.   Is there any thing like it  in GP?

or my PC is not suit for the work?  I have to add my memory to 100G, so that I can deal with data like 999999  ?

i may have some basic wrong about the things ,but really thanks for any help.

**Comment by mzwiessele** [comment]
This is a great discussion to take over to the mailing list:
gpy-users@lists.shef.ac.uk

In short, GPs scale in O(n^3), where n is the number of datapoints. There is implementations available to handle big data, which is best discussed through the mailing list.
