### ISSUE TITLE
Gibbs kernel

### ISSUE THREAD

**Issue by bwengals** [SheffieldML/GPy#437]
Hi GPy, I am interested in trying out the Gibbs kernel, to get the effect of increasing lengthscale with time.  I noticed an implementation in src/todo, but it is hidden and not importable.  

What's the status of this kernel?  Some other kernels in there, poly and spline, are available or have been moved into the main src section.  If currently broken, would be needed to get this kernel fixed?

**Comment by mzwiessele** [comment]
It seems this was on the agenda. If you are interested in the kernel, you can try to implement it and set up a pull request (see https://github.com/SheffieldML/GPy#contributing-to-gpy).
