### ISSUE TITLE
Problem with SVGP.predictive_gradients

### ISSUE THREAD

**Issue by ehsanabb** [SheffieldML/GPy#438]
Hi there,

I am using “predictive_gradients” function from SVGP and it encounters the following error:
From the debug mode it seems the problem is that “posterior.woodbury_inv” parameter is a three dimensional matrix rather than two. The input is a 1*2 vector with Matern32 kernel. Could you please advise.

Thanks,
Ehsan

 File ".../GPy/core/gp.py", line 343, in predictive_gradients
    dv_dX += kern.gradients_X(alpha, Xnew, self._predictive_variable)
  File ".../GPy/kern/src/kernel_slice_operations.py", line 117, in wrap
    ret = s.handle_return_array(f(self, dL_dK, s.X, s.X2))
  File ".../GPy/kern/src/stationary.py", line 226, in gradients_X
    return self._gradients_X_cython(dL_dK, X, X2)
  File ".../GPy/kern/src/stationary.py", line 313, in _gradients_X_cython
    stationary_cython.grad_X(X.shape[0], X.shape[1], X2.shape[0], X, X2, tmp, grad)
  File ".../GPy/kern/_src/stationary_cython.pyx", line 17, in GPy.kern._src.stationary_cython.grad_X (GPy/kern/src/stationary_cython.c:1998)
ValueError: Buffer has wrong number of dimensions (expected 2, got 3)

**Comment by mzwiessele** [comment]
Could you kindly supply a small runnable example of the problem you encountering?

**Comment by ehsanabb** [comment]
Hi Max,

Thanks for your prompt reply. The attached code produces the following error (I have tested with both Matern32 with/without white noise):
Buffer has wrong number of dimensions (expected 2, got 3)
with following values:
('self._predictive_variable.shape', (10,2))
('self.posterior.woodbury_inv.shape', (10, 10, 1))
('alpha.shape', (1, 10, 1))

Hope the following code is fine. Thanks.

---

`
import numpy as np
import GPy
from GPy.core import SVGP
import climin

X = np.array([[ 0.05488586,  0.79172504],
       [ 0.07152178,  0.52889492],
       [ 0.06028031,  0.56804456],
       [ 0.05449287,  0.92559664],
       [ 0.04237124,  0.07103606],
       [ 0.06459295,  0.0871293 ],
       [ 0.04376435,  0.0202184 ],
       [ 0.08917838,  0.83261985],
       [ 0.09636664,  0.77815675],
       [ 0.03835032,  0.87001215]])

Y = np.array([[ 0.11910874],
       [ 0.11910874],
       [ 0.11910874],
       [-0.85541731],
       [-1.18025933],
       [-0.63885597],
       [-1.28854   ],
       [ 1.74331882],
       [ 1.63503815],
       [ 0.22738941]])

Z = np.array([[ 0.06028031,  0.56804456],
       [ 0.08917838,  0.83261985],
       [ 0.03835032,  0.87001215],
       [ 0.05449287,  0.92559664],
       [ 0.06459295,  0.0871293 ],
       [ 0.04237124,  0.07103606],
       [ 0.04376435,  0.0202184 ],
       [ 0.05488586,  0.79172504],
       [ 0.07152178,  0.52889492],
       [ 0.09636664,  0.77815675]])

batchSize = 10

kern = GPy.kern.Matern32(2) # + GPy.kern.White(2)
model = SVGP(X, Y, Z, kern, GPy.likelihoods.Gaussian(), batchsize=batchSize)

opt = climin.Adadelta(model.optimizer_array, model.stochastic_grad, step_rate=0.2, momentum=0.9)
opt.minimize_until(lambda i: True if i['n_iter'] > 100 else False)

Xnew = np.array([[ 0.04636291,  0.04517658]])

print(model.predictive_gradients(Xnew))
`
