### ISSUE TITLE
Multiple Outputs Gaussian Processes notebook fails in Python 3.5

### ISSUE THREAD

**Issue by NoahSlv** [SheffieldML/GPy#440]
Hello,

Trying to copy paste the code from the "Running Example" into Ipython running Python 3.5

The kernel definition produces a weird numpy error.

Any ideas?

Code and error below:

`
kern = ((GPy.kern.RBF(1, variance=1, lengthscale=70)+
GPy.kern.Linear(1, 1, active_dims=[0])+
GPy.kern.White(1)+
GPy.kern.Bias(1, 1))
*GPy.kern.Coregionalize(1, output_dim=2, rank=1, active_dims=1, name='gender')
 *GPy.kern.Coregionalize(1, output_dim=3, rank=1, active_dims=2, name='event')
##  )

ValueError                                Traceback (most recent call last)
<ipython-input-39-562fd42049b7> in <module>()
      4          GPy.kern.Bias(1, 1))
      5         *GPy.kern.Coregionalize(1, output_dim=2, rank=1, active_dims=1, name='gender')
----> 6         *GPy.kern.Coregionalize(1, output_dim=3, rank=1, active_dims=2, name='event')
      7        )

/usr/local/lib/python3.5/site-packages/GPy/kern/src/kern.py in **mul**(self, other)
    267     def **mul**(self, other):
    268         """ Here we overload the '*' operator. See self.prod for more information"""
--> 269         return self.prod(other)
    270 
    271     def **imul**(self, other):

/usr/local/lib/python3.5/site-packages/GPy/kern/src/kern.py in prod(self, other, name)
    298         #if isinstance(other, Prod): kernels.extend(other.parameters)
    299         #else: kernels.append(other)
--> 300         return Prod([self, other], name)
    301 
    302     def _check_input_dim(self, X):

/usr/local/lib/python3.5/site-packages/paramz/parameterized.py in **call**(self, _args, *_kw)
     47         #import ipdb;ipdb.set_trace()
     48         initialize = kw.pop('initialize', True)
---> 49         self = super(ParametersChangedMeta, self).**call**(_args, *_kw)
     50         #logger.debug("finished init")
     51         self._in_init_ = False

/usr/local/lib/python3.5/site-packages/GPy/kern/src/prod.py in **init**(self, kernels, name)
     38                     kern.unlink_parameter(part)
     39                     kernels.insert(i, part)
---> 40         super(Prod, self).**init**(kernels, name)
     41 
     42     @Cache_this(limit=3, force_kwargs=['which_parts'])

/usr/local/lib/python3.5/site-packages/GPy/kern/src/kern.py in **init**(self, kernels, name, extra_dims)
    325         extra_dims = np.asarray(extra_dims, dtype=int)
    326 
--> 327         active_dims = reduce(np.union1d, (np.r_[x.active_dims] for x in kernels), extra_dims)
    328 
    329         input_dim = active_dims.size

/usr/local/lib/python3.5/site-packages/GPy/kern/src/kern.py in <genexpr>(.0)
    325         extra_dims = np.asarray(extra_dims, dtype=int)
    326 
--> 327         active_dims = reduce(np.union1d, (np.r_[x.active_dims] for x in kernels), extra_dims)
    328 
    329         input_dim = active_dims.size

/usr/local/lib/python3.5/site-packages/numpy/lib/index_tricks.py in **getitem**(self, key)
    336                 objs[k] = objs[k].astype(final_dtype)
    337 
--> 338         res = _nx.concatenate(tuple(objs), axis=self.axis)
    339         return self._retval(res)
    340 

ValueError: zero-dimensional arrays cannot be concatenated
`

**Comment by mzwiessele** [comment]
Yes that is easy : )

You are giving the active dims as integers, but you need to give lists:

kern = ((GPy.kern.RBF(1, variance=1, lengthscale=70)+
GPy.kern.Linear(1, 1, active_dims=[0])+
GPy.kern.White(1)+
GPy.kern.Bias(1, 1))
*GPy.kern.Coregionalize(1, output_dim=2, rank=1, active_dims=[1], name='gender')
*GPy.kern.Coregionalize(1, output_dim=3, rank=1, active_dims=[2], name='event')

)

**Comment by NoahSlv** [comment]
Thanks Max,

—
Noah Silverman, PhD
Data Science Ltd
Tel: +852 5994 8511

**Comment by mzwiessele** [comment]
Fix is incoming soon, so you can just give integers. Thanks for the reminder!
