### ISSUE TITLE
GPU documentation

### ISSUE THREAD

**Issue by NoahSlv** [SheffieldML/GPy#441]
Hello,

Looking at some of the source code for GPY, I see some use of the GPU.  However, there is no documentation for this.
1.  How can we use the GPU, for GPy, to speed up some of the process?
2. Given #1 above, how can we confirm that the code is actually using the GPU

Thanks!

**Comment by mzwiessele** [comment]
As far as I know, it is as simple as telling the kernel use_gpu=True in the constructor. I think pycuda needs to be installed. I am not sure about these facts, but it might help you to start somewhere : )

**Comment by zhenwendai** [comment]
The usage of GPU in GPy is still in experimental stage. GPU is only used for RBF kernel in BayesianGPLVM (accelerating the psi-statistics).

The GPU code is implemented with pyCUDA. When initializing the RBF kernel with the argument use_gpu=True, the code will use GPU if possible.
