### ISSUE TITLE
BGPLVM clang++ 

### ISSUE THREAD

**Issue by mzwiessele** [SheffieldML/GPy#45]
BGPLVM `clang++` inline code not working/compiling on Mac OS.

Report:
- Installed newest versions of clang, gcc and scipy.
- Reinstalled GPy (``rm `find GPy/GPy -name *.pyc -type f` `` and reimport GPy)

nothing helped so far, is that a known bug for weave?

**Comment by mikecroucher** [comment]
I'm guessing that this can be closed now?

**Comment by mikecroucher** [comment]
This is no longer an issue.
