### ISSUE TITLE
Student-t processes

### ISSUE THREAD

**Issue by javdrher** [SheffieldML/GPy#453]
Hello,

Last month I implemented Student-t processes in GPy (https://arxiv.org/pdf/1402.4306v2.pdf). I encountered the student-t likelihood and there seem to be some differences with what is currently available in GPy. One of them being that Student-t processes offer direct inference, and only have a slightly different predictive variance. 

The implementation was a bit too shaky to directly make a PR: I replaced the student-t likelihood locally, implemented a direct inference method for student-t and created a subclass of GP in GPy.core. I also included optimization of the degrees of freedom. If interested I can refactor the code and contribute the model. However, I would require some input on how to make it co-exist with the current student-t likelihood.

**Comment by mzwiessele** [comment]
Thanks @javdrher that sounds great! What is the advantage over the existing inference? It seems to me, that is will be more efficient, as it is a specific implementation of the matter? 

@alansaul can you help with this?

**Comment by javdrher** [comment]
Student-t processes are derived by assuming an inverse wishart prior for the covariance matrix, and marginalizing this prior out. This results in a likelihood that corresponds to a multivariate t-distribution. 
I should mention that the noise is no longer considered to be an independent distribution because the sum with p(f|x) makes derivation of the marginal likelihood intractable again. Instead, a white noise kernel is applied to handle noise. Doing so, the likelihood is a single MVT, so direct inference becomes feasible. I think this could be one of the differences with the current implementation, but I'm not entirely sure. 

Appendix A, Lemma 3 of the paper I linked also contains the derivation of the predictive distribution, which is also an MVT as opposed to the current implementation where its assumed to be Gaussian (I think?). The degrees of freedom of this predictive distribution do not vary on x, and it has the additional term in front of the variance which doesn't seem present in the current implementation.

**Comment by sivark** [comment]
@javdrher Hello! Have you shared your implementation of Student-T processes on Github?

**Comment by mzwiessele** [comment]
We are looking forward to a PR of this matter : )

**Comment by javdrher** [comment]
My apologies for the delay in replying @sivark , the code is still somewhere on a backup disc somewhere, from what I remember it wasn't in a state I could make a PR right away. I'm a little busy right now, but I'll try to check it out this week. If I remember everything correctly I should be able to refactor it this week and create a PR.

**Comment by lawrennd** [comment]
PR would be great. @mzwiessele these processes are particularly interesting
for small n because at that point the process scale (which is treated with
an inverse gamma) is not yet determined well. After about 10 data points I
think they look very similar to GPs (which is perhaps why they are not so
commonly deployed).

**Comment by sivark** [comment]
>  these processes are particularly interesting for small n because at that point the process scale (which is treated with an inverse gamma) is not yet determined well. After about 10 data points I think they look very similar to GP

@lawrennd Could you elaborate on this, or point me to a resource which explains this?

**Comment by lawrennd** [comment]
I'll give you a hand wavy argument, I don't have a reference, don't think I
read it anywhere, just did the math once.

If you think of a univariate Gaussian where the variance is drawn from an
inverse gamma, and look at the posterior for the variance, that's also
inverse gamma. But as the number of data increases the variance of the
posterior collapses quite rapidly (from recollection as 1/n^2?). That means
after very fairly data the posterior distribution for the variance becomes
fairly confident, approaching a delta function, and therefore the marginal
likelihood will look very Gaussian.

A similar effect occurs with the *overall* scale of the GP. It becomes well
determined with relatively few data, and so the overall process begins to
look very Gaussian. But for very low data, it can be very useful as it
places back in a very important aspect of the uncertainty.

To see this, just set up the process as a Gaussian process with the
relevant prior over the scale, then compute the posterior, and check it's
dependence on the number of data. If memory serves me well it will also
collapse to delta very quickly also.
