### ISSUE TITLE
Accesing model object from inside priors

### ISSUE THREAD

**Issue by MartinHjelm** [SheffieldML/GPy#456]
I have been browsing the code a bit and the structure is kinda tricky to get. But it seems that priors you add to the GPLVM model can only access the data from what it is a prior over. For example if I did this 

    m = GPy.models.BayesianGPLVM(Y, input_dim=2, kernel=GPy.kern.RBF(1), num_inducing=10)
    m.X.set_prior(GPy.priors.MyPrior(params))

Then the MyPrior on X would only have access to X through when evaluating the prior function( when called from the log_prior in Priorizable)?? I would like to have access to the whole object and all parameters. Does that mean I have to write my own log prior to give that access? And pass the full object at evaluation. (is this the right forum for posting or should I go to the mailing list?)

**Comment by mzwiessele** [comment]
Yes you should write your own prior, specific to your model. The framework is rather general and provides easy implementation of your own stuff. So you can improvise and make specifics for your personal model. You could write your own prior and hand the  at creation time.

**Comment by MartinHjelm** [comment]
Thanks for the reply. hmm I don't understand.  Looking at the priors in priors.py and the log_prior function in priorizable.py it looks like the default is to only have access to the X values. 

```
def log_prior(self):
    """evaluate the prior"""
    if self.priors.size == 0:
        return 0.
    x = self.param_array
    #evaluate the prior log densities
    log_p = reduce(lambda a, b: a + b, (p.lnpdf(x[ind]).sum() for p, ind in self.priors.items()), 0)
```

So if I wanted my model to have access to more information I would have to overload the log_prior and log_gradient functions in my own model? And then these would get called automagically during optimization?

**Comment by mzwiessele** [comment]
No, at creation time of the prior, you pass in the parameter of interest. It is only a pointer, so it will be updated during the observer update chain.

**Comment by alansaul** [comment]
Just to clarify Martin, you wish to have access to parameters further up
the hierarchy when evaluating your prior? So you mean perhaps your
log_prior function depends on the parameters of m.kern or something?

If I'm not mistaken (which I may well be!) Max is suggesting you pass pass
m.kern to your prior when you create it, and then store it as a reference
(so it you will have access to the new values each iteration).

I've not really played with this part of the codebase, but I am
interpreting what you and Max are saying correctly, I think it would be
something along the lines of (assuming you have some function of the RBF
kernel hyper-parameters):

 class MyPrior(Prior): domain = _REAL _instances = []
def __init__(self, some_params, some_external_params): self.some_params=
float(some_params) self.other_external_params = some_external_params #
reference to other object
def **new**(cls, some_params=1, other_external_params=1): # Singleton: if
cls._instances: cls._instances[:] = [instance for instance in
cls._instances if instance()] for instance in cls._instances: # Note here
we check _is_ one parameter the same as the other, i.e. do we have a
reference to the same parameter instance when we are making our singleton
if instance().some_params == some_params and
instance().other_external_params is other_external_params: return
instance() newfunc = super(Prior, cls).__new__ if newfunc is
object.**new**: o = newfunc(cls) else: o = newfunc(cls, some_params,
other_external_params) cls._instances.append(weakref.ref(o)) return
cls._instances[-1]() def __str__(self): return "MyPrior({:.2g}, {:.2g},
{:.2g})".format(self.some_params, self.some_external_params.lengthscale[:],
self.some_external_params.variance[:]) # will need proper string formatting
def lnpdf(self, x): # Your log density which is obviously prior specfic
return x \* self.some_params \* self.some_external_params.lengthscale[:] *
self.some_external_params.variance[:] def lnpdf_grad(self, x): #
Corresponding log density gradient return self.some_params *
self.some_external_params.lengthscale[:] *
self.some_external_params.variance[:] def rvs(self, n): # Some way of
sampling from your prior return np.random.randn(n)

m = GPy.models.BayesianGPLVM(Y, input_dim=2, kernel=GPy.kern.RBF(1),
num_inducing=10)

m.X.set_prior(GPy.priors.MyPrior(some_params = params
some_external_params = m.kern)

This is very much pseudo code (I haven't run it or even looked at this
part of the codebase), and could be incorrect generally (Max please
correct me!), but maybe it gives you somewhere to start.

Cheers,

Alan
