### ISSUE TITLE
Using Bayesian optimization to fit the parameters of a GP

### ISSUE THREAD

**Issue by achapchap** [SheffieldML/GPy#457]
Hi,
 
I wonder whether it would be possible to use a GPy in order  to fit a GP (quad GP  ?) to the negative log likehood of another GP (x = hyper parameters and y =nlml) and then try to find the hyper parameters by doing BO. 

The closest approach I have found was Bayesian quadrature, but if I understood it correctly it tries to model the whole posterior rather than nlml . In addition in this case, should one try to minimize the more conventional acquistions (say EI and UCB) or perhaps try to minimize uncertainty instead  (say the variance of the quad GP)  ? 

Thanks very much,

**Comment by mzwiessele** [comment]
Thanks for your interest! I think you gonna reach more people if you write to the email list, and have a look at GPyOpt Also located in the SheffieldML organisation on github. The email is in the readme on GPy's github.

**Comment by alansaul** [comment]
From what I understand, you essentially want to attempt global optimisation
of the hyper-parameters using bayesian optimisation (BO).

This would certainly be possible, I had considered doing it before. There
is a really great BO package that is built on top of GPy called GPyOpt.
Essentially you want to just use a GPy model (the nll) as your function.

There is an example notebook here:

https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_GPy.ipynb

Cheers,

Alan

**Comment by javiergonzalezh** [comment]
HI!

Thanks for the interest! Yes, the notebook that Alan mentioned is an
example of how you can do that. Is not quite documented but you can have an
idea of how to do it having a look to the code. Just let us know if you
have any questions. Perhaps the best is if you open an issue in GPyOpt (
https://github.com/SheffieldML/GPyOpt/issues) if you want to discuss this
point further.

Cheers!

Javier

**Comment by achapchap** [comment]
Thanks very much, very helpful comments. 
The main reason I am considering doing this is to try to address the variance of negative log likehood as well and hopefully try to avoid regions with high variance. Intuitively I am temped to think that regions where log likehood has a large variance are prone to overfitting. Do you think this could make sense ? 

Still regarding the GPy, I noticed that the Gabor kernel does not seem to be implemented. However, it seems to be possible to construct it by taking the product of the periodic kernel (cos(r) ) and the exponential kernel. Is that the case or should I try to construct the Gabor kernel following the GPy documentation ?

**Comment by mzwiessele** [comment]
You should give it a go and see if you get problems by doing the combination. If you run into stability problems you might consider implementing a more stable version directly yourself.
