### ISSUE TITLE
How to implement RBF Kernel in 3 dimension (x,y,time)?

### ISSUE THREAD

**Issue by ktiwari9** [SheffieldML/GPy#459]
How can I extend the dimensions of RBF from 1-D to 2-D (x,y) dimensions and print out both the learned length scales ? Currently, the output shows (2,) as below so I don't know what are the hyper-params for 2-dimensions since I already set d=2 for this case. I was expecting to see something like rbf.lengthscale_0 and rbf.lengthscale_1 or something similar ?

GP_regression.             |      value                            |  constraints  |  priors
  sum.rbf.variance         | 0.32260157071                 |      +ve      |        
  sum.rbf.lengthscale    |               (2,)                       |      +ve      |        
  sum.white.variance     |   0.00132288200112         |      +ve      |        
  Gaussian_noise.variance  |  0.000379817546841  |      +ve      |  

Similarly, for 3-Dimensions in case of learning inference over multiple time steps ?

Please advise.

**Comment by mzwiessele** [comment]
you can print the parameter itself by print(m.kern.rbf.lengthscale)

**Comment by ktiwari9** [comment]
Thanks for that answer. It does help but I am still struggling to figure out how to infer the temporal dynamics. For instance if I have length scale for X-dim, Y-dim and Time dimensions then just replacing input_dim =2 to input_dim=3 doesnt work. I can infer the X,Y dim length scales but how can I infer the time dimension length scale ?

**Comment by mzwiessele** [comment]
This is a great question for the mailing list :)

One hint is to treat time as input.

**Comment by ktiwari9** [comment]
Ooh nice hint. 
Quick question: Does the current framework handle a 2-D input (X) and a 2-D target (Y) ?

**Comment by mzwiessele** [comment]
Yes :) you just give both in two d and it will handle the computations for you. The assumption is, that the y dimensions are independent.
