### ISSUE TITLE
GPRN as a part of GPy

### ISSUE THREAD

**Issue by avonmoll** [SheffieldML/GPy#460]
I am considering implementing Gaussian Process Regression Networks [[1]] in Python based off of the approach and code from a paper called Efficient Variational Inference for GPRN [[2]]. The author of [[2]] used the [MATLAB toolbox by Rasmussen](http://www.gaussianprocess.org/gpml/code/matlab/doc/) so I was looking for something similar in Python, which is how I came across GPy. After seeing how active GPy development is, I'm now wondering if the maintainers would be interested in having such a GPRN implementation incorporated within GPy.

[[1]] : Gaussian Process Regression Networks paper
[[2]] : Efficient Variational Inference for GPRN

[1]: http://icml.cc/2012/papers/329.pdf
[2]: http://jmlr.csail.mit.edu/proceedings/papers/v31/nguyen13b.pdf

**Comment by mzwiessele** [comment]
Yes that would be great!
You should start with the tutorial notebooks, to get a feeling for GPy and how the main focus is on usability by the user. 
The developer doc has some advices on how to implement new models and kernels.

The links to both are in the readme on the front page.

 Let us know if you have any particular problems :)
