### ISSUE TITLE
tie_params doesnt work ?

### ISSUE THREAD

**Issue by ktiwari9** [SheffieldML/GPy#462]
I am trying to tie my length scales together using `m.kern.rbf.tie_params('.*len')` but I get the error: `AttributeError: 'Add' object has no attribute 'tie_params'`.

So, has the syntax changed or we cannot tie params anymore ?

**Comment by mzwiessele** [comment]
No it is not implemented unfortunately. The easiest is to write a wrapper kernel, that does the tie itself.

**Comment by ktiwari9** [comment]
I am quite new to all this so would you mind suggesting how can I write a wrapper kernel ?

**Comment by mzwiessele** [comment]
Here is how to write a kernel:
http://pythonhosted.org/GPy/tuto_creating_new_kernels.html

By wrapper kernel we mean a new kernel around the kernel you want to have, binding the lengthscales together (setting them to be equal to its lengthscale). Make sure you fix the lengthscales of the tied kernels and unlink their parameters (e.g. kern.unlink_parameter(kern.lengthscale)).

Sry for the inconvenience, but noone got around to actually getting the automatic tieing to work.
