### ISSUE TITLE
Binomial EP

### ISSUE THREAD

**Issue by webdrone** [SheffieldML/GPy#463]
Hello,

Thank you for your package. I am trying to use it to do GP regression for binomial observation targets, but errors crop up, resulting in nan values, divisions by zero, etc.

At first I thought it was because the inv_link_f was not being clipped in binomial.py, but after fixing that, similar errors appeared further on.

I now think that the integration attempted to estimate z (in the function moments_match_ep in likelihood.py) comes out to zero, or very close to it, causing all sorts of issues.

Any advice on how to deal with this would be very welcome.

**Comment by ric70x7** [comment]
Hi webdrone,
The integration to compute z has some numerical difficulties (see issue #414). Unfortunately we haven't been able to solve it. Anyway, could you send an example that reproduces the error please? With any luck it is something different and I can think of a solution.
Cheers

**Comment by webdrone** [comment]
Hi,

Thanks for the swift response. I am attaching the code that produces the error, along with the data I'm trying to do regression over. Simply try to execute it with the python3 command with both the script and the numpy array file in the same directory, and it should err / result in nan values.

The first 2 columns of the numpy array are the 2D inputs, X, and the last column are the observations y/N, N=5000, of the variable y ~ B(N, f(x)).

In this setting, $Pr(y_i = k|X_i) = {N}\choose{k} (f(X))^k (1 - f(X))^{N - k}$, where $f(X)$ is some probability dependent on $X$. I am trying to estimate this probability $f$ for unobserved values of the domain $X$ lives in.

I appreciate any help you can provide.

[Binomial_GPEP.zip](https://github.com/SheffieldML/GPy/files/635448/Binomial_GPEP.zip)

**Comment by ric70x7** [comment]
Hi,
Try these changes in your code:

    bi_lklhd = GPy.likelihoods.Binomial()
    infer = GPy.inference.latent_function_inference.Laplace() #Laplace is
better than EP in this case
    kernel = GPy.kern.RBF(X_points.shape[1], ARD = True, lengthscale=100) #
I think your inputs are quite far apart
    gp = GPy.core.GP(X_points, y,
                     kernel=kernel,
                     likelihood=bi_lklhd,
                     inference_method=infer, # Here you pass the inference
method
                     Y_metadata=y_meta)
    # gp.optimize(messages=True)
    y_pred_mean, y_pred_var = gp.predict(extra_points,
Y_metadata={'trials':50}) # You need to pass the number of trials for the
predictions

You will still face some problems with a very high number of trials. If
possible, I would recommend to use a smaller one.

Ricardo

**Comment by webdrone** [comment]
Hello,

Thanks for getting back. I actually managed to get it to work yesterday, by:
1. Decreasing the number of trials as you suggest here as well.
2. Adding ARD since my input is 2D -- I missed that flag. Optimisation works, removing the need to predefine lengthscales.
3. Changing predict() to _raw_predict, then inverse probit transforming the mean and variance back to the [0, 1] domain. I had to do this since predict() raised a "not implemented" error.

I am attaching the updated code which should now run without problems. NB: I am still clipping the inv_link_f in binomial.py for this.
[Binomial_GPEP.zip](https://github.com/SheffieldML/GPy/files/642251/Binomial_GPEP.zip)

Could I ask you, why do you think Laplace is a better approximation than EP for this case?
Thanks for all the support, much appreciated.

**Comment by ric70x7** [comment]
It was just trial and error. I managed to get it running when I switched to
the Laplace approximation. But if EP is working for you, that's great.
