### ISSUE TITLE
Non-stationary models

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [SheffieldML/GPy#465]
I'm working on a regression problem that is non-stationary. One way to do so is to weight down points as time elapses (older data points should contribute with a lower weight to the fitting).

Does GPy have support for this use case? 

One way I thought of accommodating this is by adding a time dimension, e.g. with a kernel that assumes weaker covariance between older and the current "time frame". Is this doable within GPy? Any examples I can use as a start?

To simplify the above, let's assume that for a stationary regression problem where Y and X are 1D, we are now interested in solving this problem where Y(t) and X(t), so older (X,Y) observations should have a lower influence than newer ones.

**Comment by mzwiessele** [comment]
You could add the time dimension as you said manually as an additional input in x. By setting the active dimensions in the kernel you can limit the influence of dimensions to specific kernels by adding them together (active_dims).

**Comment by amelio-vazquez-reina** [comment]
Thanks @mzwiessele Do we have any examples in GPy that I can use here as a starting point?

**Comment by amelio-vazquez-reina** [comment]
For example, I am hoping to extend the original [`simple_mean_function`](https://github.com/SheffieldML/GPy/blob/devel/GPy/examples/regression.py#L509-L528) that is part of the file [`examples/regression.py`](https://github.com/SheffieldML/GPy/blob/devel/GPy/examples/regression.py) below to add a time dimension:

``` python
################################################################
## SIMPLE EXAMPLE KNOWN TO WORK
################################################################
# Create  simple mean function
mf = GPy.core.Mapping(1,1)
mf.f = np.sin
mf.update_gradients = lambda a,b: None

X = np.linspace(0,10,50).reshape(-1,1)
Y = np.sin(X) + 0.5*np.cos(3*X) + 0.1*np.random.randn(*X.shape)

k   = GPy.kern.RBF(1)
lik = GPy.likelihoods.Gaussian()
m   = GPy.core.GP(X, Y, kernel=k, likelihood=lik, mean_function=mf)

# optimize and plot
m.optimize(messages=True,max_f_eval = 1000)
fig = m.plot()
display(GPy.plotting.show(fig))
##
```

to add a time dimension (e.g. time moves in `[0, ... 25]`). 

I tried the following with no luck:

``` python
X = np.linspace(0,10,50).reshape(-1,1)
X = np.tile(X,(1,2))
X[:,1] = 0
X[1::3,1] = 5


mf = GPy.core.Mapping(1,1)
mf.f = np.sin
mf.update_gradients = lambda a,b: None


Y = np.sin(X[:,0])
Y = np.expand_dims(Y, axis=1)


ker1 = GPy.kern.RBF(input_dim=1,active_dims=[0])
ker2 = GPy.kern.RBF(input_dim=1,active_dims=[1])

ker = ker1 + ker2

lik = GPy.likelihoods.Gaussian()
# , mean_function=mf
m   = GPy.core.GP(X, Y, kernel=ker, likelihood=lik)


# optimize and plot
m.optimize(messages=True,max_f_eval = 1000)
```

Which seems to work well. I am now trying to plot it:

```
Xnew = np.linspace(-20,20,200).reshape(-1,1)
Xgrid = Xnew
Xgrid = np.tile(Xgrid,(1,2))
Xgrid[:,1] = 0

mu, _ = m.predict(Xgrid)
```

Am I approaching this right?

**Comment by amelio-vazquez-reina** [comment]
In either case, thanks again @mzwiessele I'd be happy to contribute with these examples myself as well :) (e.g. a variation of the above). I may just need a bit more help getting started with the library..

**Comment by mzwiessele** [comment]
You can use the internal plotting function:
m.plot(fixed_inputs=[[1,0]]) # fix the second (1) dimension to be zero (0)
m.plot(fixed_inputs=[[1,.5]]) # fix the second (1) dimension to be one half (0.5)
