### ISSUE TITLE
Help understanding mean functions

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [SheffieldML/GPy#466]
The function `GPy.core.GP` accepts a mean function and I am trying to understand how to use it exactly.

My understanding is that in noisy problems one usually has the following model (taken from [here](https://www.cs.ox.ac.uk/people/nando.defreitas/publications/BayesOptLoop.pdf)):

<img width="238" alt="screen shot 2016-12-30 at 6 44 15 pm" src="https://cloud.githubusercontent.com/assets/1993919/21574392/0ec4e3ea-cec0-11e6-8563-4b3c54d6058c.png">

What exactly is the *mean function* (example code below) in the equation above? 

``` python
mf = GPy.core.Mapping(1,1)
mf.f = np.sin
mf.update_gradients = lambda a,b: None
```

What exactly does it do? What's `Mapping` and why is `f` set to `np.sin`?

`mf` is used in `GP` as follows:
```
m   = GPy.core.GP(X, Y, kernel=k, likelihood=lik, mean_function=mf)
```

I am trying to put this in context with what I read in [Shahriari's paper](https://www.cs.ox.ac.uk/people/nando.defreitas/publications/BayesOptLoop.pdf):

------

**Prior Mean Functions**
While the kernel function controls the smoothness and amplitude of samples from the GP, the prior mean provides a possible offset. In practice, this function is set to a constant  mu_0(x) = mu_0(x) and inferred from data using techniques covered in Section V-A. Unless otherwise specified, in what follows we assume a constant prior mean function for convenience. However, the prior mean function is a principled way of incorporating expert knowledge of the objective function, if it is available, and the following analysis can be readily applied to non-constant functions  0.

------

Any help understanding the code snippet above and how it relates to the equations in Shariari's paper would be very helpful.

**Comment by lawrennd** [comment]
The mean function is m(x), just as kernel functions are K(x, x') and Mapping is the class in which mean functions fall in within the GPy object hierarchy (they are functions, so they are also mappings). 

It's not as well featured for mean functions as we'd currently like my recollection (@alansaul, @mzwiessele) is that they are not yet implemented for the sparse approximations.

Another source for reading about mean functions is the GPML book (section 2.7) PDF here: http://www.gaussianprocess.org/gpml/chapters/RW2.pdf

**Comment by amelio-vazquez-reina** [comment]
Thanks @alansaul
