### ISSUE TITLE
Plot definition

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [SheffieldML/GPy#468]
I am reading through the code trying to understand how everything is organized and I have a question regarding plotting.

In the example [`simple_mean_function`](https://github.com/SheffieldML/GPy/blob/devel/GPy/examples/regression.py#L509-L528) I see [this line](https://github.com/SheffieldML/GPy/blob/devel/GPy/examples/regression.py#L527) does:

``` python
m   = GPy.core.GP(X, Y, kernel=k, likelihood=lik, mean_function=mf)
...
m.plot(plot_limits=(-10,15))
```

`m` is of class `GP`, which is a child of `Model`, which itself is a child of `ParamzModel` and `Priorizable`, etc. but **none** of these classes (at least the corresponding files) define a `plot` method. 

I see however, a `gp_plots.py` file within the folder `gpy_plot` where `plot` and `_plot` are defined.  What am I missing?

**Comment by mzwiessele** [comment]
It is all defined in the paramz package over in sods:

https://github.com/sods/paramz

**Comment by mzwiessele** [comment]
Oh sry, I missed the point totally. The plotting is injected in 
https://github.com/SheffieldML/GPy/blob/devel/GPy/plotting/__init__.py
The injection is used to make sure the plotting library can be changed (also on the fly). It is a bit hidden, but it is described in the documentation:
http://pythonhosted.org/GPy/
