### ISSUE TITLE
Strange results when plotting simple regression example

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [SheffieldML/GPy#469]
Let's assume we have a regression problem from R^2 -> R. One of the dimensions is supposed to capture some notion of "distance" (relevance). I am not getting the results I would expect from my kernel (visualization at the bottom).

``` python

## Data
X = np.linspace(0,10,50).reshape(-1,1)
X = np.tile(X,(1,2))

# We have data points at two distances (darker and lighter points), 0 and 2:
X[:,1] = 0
X[1::3,1] = 2

# Drop every 4 samples
X = X[::4,:]

# Y values
Y = np.sin(X[:,0]) + 0.5*np.cos(3*X[:,0]) + 0.1*np.random.randn(X.shape[0])
Y = np.expand_dims(Y, axis=1)
Y[1::3] += 2

ker = GPy.kern.RBF(input_dim=2,active_dims=[0,1])

lik = GPy.likelihoods.Gaussian()
m   = GPy.core.GP(X, Y, kernel=ker, likelihood=lik)

m.optimize(messages=True,max_f_eval = 1000)

################
# Predict data on the slice X[:,1] = 0

Xgrid = np.linspace(-20,20,200).reshape(-1,1)
Xgrid = np.tile(Xgrid,(1,2))
Xgrid[:,1] = 0

mu, var = m.predict(Xgrid)

# Plotting:
f,ax = plt.subplots(1, 1, figsize=(10, 6), sharex=False)

low  = (mu-np.sqrt(var)).flatten()
high = (mu+np.sqrt(var)).flatten()
ax.fill_between(Xgrid[:,0], low, high, label='mu ± sigma.', alpha=0.2)

ax.plot(Xgrid[:,0], mu, label='Mu')

# Two colors ("closer" points are darker)
cmap = sns.color_palette("Greys",4)[::-1]
color = np.array(cmap)[X[:,1].astype(int),:]

ax.scatter(X[:,0], Y, color=color, label='Data points', s=100)

ax.set_xlim((-10,10))
```

but I am not getting the results I would expect (see my questions below):

<img width="651" alt="screen shot 2017-01-05 at 12 39 22 am" src="https://cloud.githubusercontent.com/assets/1993919/21670108/7f19dae2-d2df-11e6-87bd-3c9f64891848.png">

I would expect the *light* data points to have a stronger influence in the prediction than they actually have. The light points seem to *not* be influencing the prediction at all. Note that we are visualizing `Xgrid[:,1] = 0`. 

Why is that?  

In case it's not clear, I am hoping to model the problem so that points that are "farther away" from the `Xgrid[:,1] = 0` plane have a gradually weaker influence in the prediction.

**Comment by mzwiessele** [comment]
It looks like you are plotting the 2.5th to next percentile. Try plotting from the first to last percentile.

**Comment by amelio-vazquez-reina** [comment]
Thank you @mzwiessele you were totally right. Sorry that was a silly mistake. I fixed the problem shortly after posting. I am now seeing a much more interesting problem, and updated the post and the plot accordingly. Hopefully the updated question is clear enough! Thanks again for your help.

**Comment by mzwiessele** [comment]
There is a strong effect in the second input dimension. This plot should show the influence of the second dimension:

<a href="https://plot.ly/~maxz/726/" target="_blank" title="2d-input-explanation" style="display: block; text-align: center;"><img src="https://plot.ly/~maxz/726.png" alt="2d-input-explanation" style="max-width: 100%;width: 600px;"  width="600" onerror="this.onerror=null;this.src='https://plot.ly/404.png';" /></a>
