### ISSUE TITLE
hitting ipdb breakpoint in laplace.py

### ISSUE THREAD

**Issue by ltalluto** [SheffieldML/GPy#473]
I've been frequently running into a problem where I hit a debugger breakpoint while optimizing a model using Laplace inference. For some reason, the model is ending up with infinite likelihoods, which triggers the breakpoint on line 175 in latent_function_inference/laplace.py.

Why the likelihood is infinite is a mystery to me; the response variable is using a probit link, a gaussian likelihood, and all output data values are between 0 and 1. There should be no values of the latent function that don't map back to a valid y-value (except inf, I suppose). Secondarily, is it intentional to force the user into a debugger here, rather than raising an exception or simply handling the infinite likelihood? After all, line 176 returns an infinite value, suggesting to me that this value can be handled later on.

**Comment by gdmcdonald** [comment]
I have this problem as well

**Comment by mzwiessele** [comment]
@alansaul any comments?

**Comment by alansaul** [comment]
Can you give some code that reproduces so this so I can take a look? 

This error can sometimes happen when the optimisation drops into a bad region (for example the lengthscale goes to infinity) - this is where I have encountered it anyway, if you have an example where this isn't the case that would be great. Before starting your optimisation, try and ensure that all parameters are sensible and that you have some structure in the covariance matrix. I usually do this by plotting m.kern.K(m.X, m.X) before optimising, typically this should show structure and not just a strong diagonal with no non-zero off-diagonals.

Perhaps we shouldn't drop into a debugger here, but ultimately we will need to crash out - as we can't optimise when our log-likelihood is evaluating as nan. I think when I encountered this error I found it useful to drop into a debugger but I can see how that could be annoying for a user - I am happy to take it out and raise an exception instead.

@mtalluto Is there a specific reason why you are using a probit link function and a Gaussian likelihood? Typically we would use a probit link function along side a Bernoulli likelihood when we are doing classification, though of course this shouldn't be a restriction and I can't think of a reason why it shouldn't work with a Gaussian likelihood and probit link function like you state.

Cheers

Alan

**Comment by ltalluto** [comment]
I actually haven't seen it in a while, so it's likely I changed something in my own code that resolved the situation. But it was always random; I could get the optimiser to complete successfully by uninstalling ipdb, catching the ImportError, and restarting the optimisation. If I encounter it again I will try to get some reproducible code.

For me, an exception would be much more useful, because I am often not running this interactively, and often multiple models are being run in sequence. It's a bit frustrating to come back in a few hours to find out I got hung up on the first model because the debugger was waiting for me to do something.

I do have a reason for the probit/Gaussian combination. In ecology, we often have real-valued response data that are constrained between 0 and 1 and cannot (easily) be resolved to binomial data. One example is the proportion of some area covered by a particular plant or land cover. You could approximate a binomial by assuming the sample size is the resolution (i.e., if you estimate cover from an image, it's the number of pixel "successes" given the number of pixels), but often this makes unreasonable assumptions about how the data were collected. Sometimes we use a beta distribution for these data as well, but the Gaussian/probit is a nice quick and dirty solution that usually works.

**Comment by KaGrosse** [comment]
Hi everyone, 
I have the same issue, using binary data, and only training a model using the polynomial kernel (linear and rbf) work fine. The dataset is available here https://drive.google.com/file/d/0ByiDcbjWwz4tcDVaMFNCaThDSXM/edit.
Reading the previous discussion, I had a look at the kernels before optimizing. I plot them in the following order (pplynomial, linear, rbf). All of them seem to show structure for learning, however I had to cut away larger values to make this structure visible. In particular for the poly kernel, I had to cut values down from e^14 - maybe this is the reason for the failure in optimization? For the linear kernel, values went only up to e^5.
Funny enough, when going with the debugger through the code, everything converges fine and I get a good classifier....

[poly.pdf](https://github.com/SheffieldML/GPy/files/1726982/poly.pdf)
[linear.pdf](https://github.com/SheffieldML/GPy/files/1726983/linear.pdf)
[rbf.pdf](https://github.com/SheffieldML/GPy/files/1726984/rbf.pdf)

**Comment by mzwiessele** [comment]
Are you using the normalizer to normalize your outputs? What range are your inputs in? Maybe you should think about standardizing your inputs, too, if you see huge variances in your kernel matrix.

**Comment by KaGrosse** [comment]
Hi, thanks for your help!
I am a little confused though. What do mean exactly by normalizing the 
outputs? Is there an option in GPy to do this?
Concerning the data i use, inputs are normalized, labels are binary anyway.

Also I do not think normalizing (the kernel, if i get this right?) alone 
will help as the structure will then almost disappear, I guess cutting 
of large values are the better option here.
Maybe the kernel choice is simply inappropriate? I used this particular 
kernel for a study where I compared different kernels. When pinging our 
collaborator from the chair, he said it might be good if you have a 
reproducible setting (what this seems to be).

Cheers,
Kathrin

**Comment by mzwiessele** [comment]
Good point, wasn’t fully thinking the output normalization through ;) 

As for the input normalization: do you have outliers in the data? How do you do normalization? Standardization or Normalization? 

No don’t normalize the kernel, that is being done by the optimization and variance parameter. Just a normalization of the input data should suffice, to make sure the initialization of parameters is ok. You want the noise variance parameters to be small, as to start from a point where the GP has to fit the data first and then explain away noise by increasing the likelihood variance.

Your kernel values seem unusually large for my liking and can as far as I can tell only stem from either outliers or non normalized inputs.

**Comment by KaGrosse** [comment]
No problem ^^

So the data are sparse binary indicator vectors (malware data), where 
each feature is zero or one. In that sense I'd say it is normalized; 
without outliers, however 955 features.

I am not quite sure why the kernel values are that large actually - 
maybe because the number of dimensions is that large??

**Comment by mzwiessele** [comment]
If you have 955 dimensional inputs and only use 500 datapoints for training, it could be just nor enough data.

Have you tried using ARD on the features? 

Could you think of another way of representing the malware entries (dimensionality reduction or simple pre-clustering)? 

Did other classifiers work (SVC, naiive Bayes, GLMM, etc)?

Otherwise it just seems too sparse data to fit with a GP classifier, I assume the sparseness of the feature vectors is one entry per sample? 

You should try to initialize the likelihood variance low, to make the GP see the data at training start.

Good luck with your research, I hope you find a way to succeed :)

**Comment by ekalosak** [comment]
Stale.
