### ISSUE TITLE
Papers Regarding differentiation in GPy

### ISSUE THREAD

**Issue by nrontsis** [SheffieldML/GPy#475]
Hi,

Dunno if opening an issue is the right way to ask, but:

Is there any paper that I can cite for the formulas used in `GPy.kern.stationary.gradients_X`

Thanks,

Nikitas

**Comment by mzwiessele** [comment]
Not directly, I'm afraid. @jameshensman are you aware of any publications for the gradients_X setup?

**Comment by blaahhrrgg** [comment]
Hi, 

I have not looked into `GPy.kern.stationary.gradients_X` but have found this document useful in the past...

http://mlg.eng.cam.ac.uk/mchutchon/DifferentiatingGPs.pdf
