### ISSUE TITLE
How to create a model with existing parameters?

### ISSUE THREAD

**Issue by zy79** [SheffieldML/GPy#476]
Hi,

If I have a set of hyperparameters from a trained model written in another platform(such as Matlab), how can I use the hyperparameters to directly create a model in Python with GPy without any training? 

Thanks,

Zhao

**Comment by mzwiessele** [comment]
You can get and set parameters directly on the model.

See https://github.com/SheffieldML/notebook/blob/master/GPy/index.ipynb for some tutorials.
