### ISSUE TITLE
Windows manual install fails

### ISSUE THREAD

**Issue by alexfeld** [SheffieldML/GPy#477]
First of all, thanks for the great package! I am now trying to install it on my Windows 64-bit machine. Unfortunately, I do not have access to `pip` so I have to compile it manually. I have mingw compilers and the Anaconda installation of Python 2.7. When I try `python setup.py build_ext --inplace` as suggested in the README, I get the following print out and error message.

[build_err.txt](https://github.com/SheffieldML/GPy/files/787863/build_err.txt)
[build_out.txt](https://github.com/SheffieldML/GPy/files/787864/build_out.txt)

I don't really know anything about C so I'm not really sure how to parse this error or where to begin to fix it. Any help is appreciated!

**Comment by mzwiessele** [comment]
Unfortunately I do not know what is gound on, either. It seems like a problem with your laplace library? Again, don't cite me on that. I am not well versed with the windows side of things.

You can always download the installer directly from here:

https://pypi.python.org/packages/a2/0d/5274bd4c09164560de3bf9426701c23a033d3934e0f86602cc4214757dba/GPy-1.5.6.win-amd64-py2.7.exe#md5=bc975702a48a6cfdae8703db325afad4

That will give you the ability to directly install GPy without pip.

**Comment by alexfeld** [comment]
I don't know if this was intentional, but I tried the latest version of the code from Github on my Windows machine and was able to build it using `python setup.py develop` with no special arguments. It appears to be working properly.
