### ISSUE TITLE
new constraint: `constrain_choice` 

### ISSUE THREAD

**Issue by majidaldo** [SheffieldML/GPy#479]
I have an application where I'd like for the model to be more restricted than `constrain_bounded`. I want to  optimize for only certain values. Is there any prior art within GPy for this?

**Comment by mzwiessele** [comment]
I am not sure what you are referring to, but the best way of going about this is to do a regular grid search about your parameters. Gradient based optimization requires smooth functions with gradients everywhere to optimize over. If you’d like to do global optimization you can use for example GPyOpt over at https://github.com/SheffieldML/GPyOpt <https://github.com/SheffieldML/GPyOpt>

Hope that helps

**Comment by majidaldo** [comment]
ah ya i see your point. that's what i'm doing now actually. right i guess what i want is global optimization.
however, my function is smooth i just want to impose that it visit certain values. there is meaning to the gradient at certain values.

generally closed issue.
