### ISSUE TITLE
Loading saved models with ARD=True

### ISSUE THREAD

**Issue by zy79** [SheffieldML/GPy#481]
Hi expert,

I created several models with RBF kernel and ARD=True. When I try to load the models with similar code in the tutorial like:
`m_load = GPy.models.GPRegression(X, Y, initialize=False)`
`m_load.update_model(False)`
`m_load.initialize_parameter() `
`m_load[:] = np.load('model_save.npy') `
`m_load.update_model(True) `
I always get error message: ValueError: Setting by slice or index only allowed with array-like. When I turn off ARD everything works. Can I know if there is a way to load the models created with ARD=True? 

Regards,
Zhao

**Comment by mzwiessele** [comment]
The model you create is not the same as the model you are trying to load. You need to create an exact recreation of the model you are trying to load, including the kernel. Try creating the new model with the right ARD kernel 
```python
GPy.kern.RBF(X.shape[1],ARD=True,initialize=False)
```

**Comment by mzwiessele** [comment]
Did it work? Is this closed?

**Comment by zy79** [comment]
It works. Thanks a lot!

**Comment by Amir-Arsalan** [comment]
@zy79 Do you remember how you saved your model? I need it to potentially resolve the issue that I'm encountering [here](https://github.com/SheffieldML/GPy/issues/807).
