### ISSUE TITLE
Gabor kernel

### ISSUE THREAD

**Issue by changlan** [SheffieldML/GPy#484]
Gabor kernel is not implemented and it would be great to have it. The covariance function is parameterized as: `k(x, x') = exp(-||x - x'||^2 / (2*l^2)) cos(2*pi*||x - x'|| / p)` in which the hyperparameters are:

- `l`: length scale
- `p`: period

**Comment by mzwiessele** [comment]
We are always happy to see people engage with the framework and look forward to any contribution.

If you would like to implement it, here's the link to how to implement a new kernel:
http://pythonhosted.org/GPy/tuto_creating_new_kernels.html

and the contribution guidlines:
https://github.com/SheffieldML/GPy#contributing-to-gpy

Thanks for using the framework!

**Comment by Bonnevie** [comment]
For the record, there is already a cosine kernel so this is just a product of existing kernels.

**Comment by mzwiessele** [comment]
Is there a reason to implement a new kernel? Or could you just use the product of the RBF and Cosine kernel as the Gabor kernel?
