### ISSUE TITLE
Y_metadata for Heteroscedantic Regression plots

### ISSUE THREAD

**Issue by mbochk** [SheffieldML/GPy#488]
I would like to submit a bug about Y_metadata behaviour for GPHeteroscedasticRegression plotting routings.

As i understood, in GPy.plotting.gpy_plot.helper_predict_with_model it is expected to set missing `Y_metadata` from the last column of `Xgrid`:
```
    if 'Y_metadata' not in predict_kw:
        predict_kw['Y_metadata'] = {}
    if 'output_index' not in predict_kw['Y_metadata']:
        predict_kw['Y_metadata']['output_index'] = Xgrid[:,-1:].astype(np.int)
```

It causes problems, when the last column is fixed one, especially with value out of index range.
(Moreover it silently "works" if value is in range, giving the same predictive variance, what is not good either)

---

I have considered heteroscedantic tutorial at
http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/heteroscedastic_regression.ipynb

I found that tutorial actually works only because int-rounding of initial `X` falls in index range of `len(X)`.
It fails on plotting with `IndexError: index 999983 is out of bounds for axis 0 with size 43` if one adds 1e6 to all `X`-like values.

**Comment by kerzmaximilian** [comment]
Hi @mbochk ,

I just ran into the same problem that you described above. Have you been able to fix / circumvent it?

**Comment by lawrennd** [comment]
@alansaul is this something you can take a look at?

**Comment by mbochk** [comment]
Hi @kerzmaximilian ,

I don't have access to code, where i tried to apply GPy anymore.
Only thing i remember: i came to conclusion that math behind GPHeteroscedasticRegression  forces you to have that heteroscedastic variance in every new point you want to predict in. 
So when i wanted to predict at points that were not in train, technically i could hack gpy and set that variance to any value/array, but it was neither mathly legit or profitable.

I'm not 100% sure it was correct conclusion, though, it's all only my memories now.

**Comment by ekalosak** [comment]
Stale.
