### ISSUE TITLE
Numpy 1.12 is not supported

### ISSUE THREAD

**Issue by zhenwendai** [SheffieldML/GPy#490]
Don't upgrade Numpy to 1.12. The behavior of indexing is changed in 1.12. Unittests failed. I am working on fixing the issue. More details will be added regarding the issue.

**Comment by mzwiessele** [comment]
Wait I did do the upgrade already, what do you mean exactly?

**Comment by mzwiessele** [comment]
I think you should pull before trying to edit stuff

**Comment by zhenwendai** [comment]
Thanks for fixes.

Our internal repo was not very up-to-date. We are working on some improvement like for EP code and push to github after some internal approval. I will improve on synchronization.
