### ISSUE TITLE
GPy.models.SparseGPRegression gives less predictive variance than GPRegression with full data

### ISSUE THREAD

**Issue by abhilashchowdhary** [SheffieldML/GPy#493]
Hi,

Can anyone provide pointers to how the inducing inputs are chosen/tuned in the GPy implementation of Sparse Gaussian Process (GPy.models.SparseGPRegression). 

Also, it is interesting to see that when I train my model using all the data points (using GPy.models.GPRegression), I have higher predictive variance but when I train my model using the Sparse regression module, the predictive variance is low. Anybody has any insight into why this is the case (it's 2d data)? I would assume, more the data, model learning should be better and hence the predictive variance should be lower.

Thanks,
Abhilash

**Comment by ekalosak** [comment]
Stale. Please re-open if you're still interested. Sorry for the tremendous delay.
