### ISSUE TITLE
plotly persistent error

### ISSUE THREAD

**Issue by aminzia** [SheffieldML/GPy#496]
Hi Everyone, 

I am running the example provided in tutorial In which by setting the graphics to (GPy.plotting.change_plotting_library('plotly')), the plotting functions try to general graphs (e.g. display(GPy.plotting.show(fig, filename='basic_gp_regression_notebook_2d'))).

But I get a persistent error related to registration in plotly as follows:

Aw, snap! We don't have an account for ''. Want to try again? You can authenticate with your email address or username. Sign in is not case sensitive.

Don't have an account? plot.ly

Questions? support@plot.ly

I suppose there must be a way to use off-line methods in plot.ly but not sure how this is implemented in Gpy. 

Any clue to resolve this issue is much appreciated.

Thank you
Amin

**Comment by alexfeld** [comment]
Hi Amin, see #480. Try using `plotly_offline` instead of `plotly` in the argument.

**Comment by aminzia** [comment]
Thank you. It worked perfectly. 

Amin
