### ISSUE TITLE
Gaussian Noise Variance V/S Likelihood Noise Variance

### ISSUE THREAD

**Issue by ktiwari9** [SheffieldML/GPy#506]
I am just a little bit puzzled about the two kinds of noise variances that exist in GPy:
If my kernel is a rbf kernel with added white noise like:

# Create an RBF Kernel and add White Noise Kernel
`k = GPy.kern.RBF(input_dim=2, ARD = True)+GPy.kern.White(input_dim=2, ARD = True)`

# Build a GP model
`m = GPy.models.GPRegression(X,Y,k)`

# White Noise Variance
`m.kern.white.variance`

# Kernel noise variance
`m.likelihood.variance`

I want to understand why is there already a noise term in rbf kernel ? Normally when doing inference for noisy measurements we need to add a Gaussian White noise kernel but here some sort of noise is already present which I dont seem to understand. If I want to know the signal variance and noise variance of the model, I guess the signal variance is the rbf variance but which one of these two refer to the noise variance ?

Please advise.

**Comment by mzwiessele** [comment]
In the simple GPRegression the Gaussian_noise and a White kernel are equivalent. The likelihood variance is there for when other likelihoods are in place (such that they can approximate the Gaussian variance internally and do not have to know about specific kernels).

**Comment by lawrennd** [comment]
Yes, Max is right. There are two ways of putting Gaussian noise in because
it's a special case where it can be seen as a kernel (the white kernel). I
believe recommended practice in GPy at the moment is to not use the white
kernel for Gaussian noise, but to include it via the likelihood.

Normally you should do one or the other. Not both. Then the RBF is the
'signal variance' and the Gaussian variance is the 'noise variance'.

**Comment by AndrewILWilliams** [comment]
I know this has been closed for a while now, but does the same advice still apply in GPflow? I'm also a bit confused about whether adding a White noise kernel adds anything in the case of simple GP Regression?  Thanks!

Edit: More specifically, when I include a white noise variance, the optimized variance is almost exactly equal to the (Gaussian) likelihood variance, I take it this isn't a coincidence?
