### ISSUE TITLE
Accessing parameters from SVGP model fit

### ISSUE THREAD

**Issue by lukerogerson** [SheffieldML/GPy#507]
Perhaps this is answered elsewhere, but I could only find answers for Bayesian optimization.

After fitting an SVGP model, how do you access the parameter values which were evaluated during the optimization? I'd like to plot parameter vs iteration and likelihood vs iteration to check how the convergence performs.

**Comment by mzwiessele** [comment]
I think you have to manually safe it. 

There is a callback routine implemented during optimization, which I cannot recall of the top of my head right now.
