### ISSUE TITLE
colour ploints by intensities in plot_latent 

### ISSUE THREAD

**Issue by mkrzak** [SheffieldML/GPy#516]
Hello to all,
I'm writing to ask if there is any possibility to colour my points in latent plot by vector of intensities (numbers) corresponding to each point and add intensity scale. 
I just found below options:
plot_latent(model, labels=None, which_indices=None,resolution=50, ax=None, marker='o', s=40, fignum=None, plot_inducing=False, legend=True, aspect='auto', updates=False)
Please let me know if you have any idea.
Best !

**Comment by mzwiessele** [comment]
You can plot the points directly using the plot_scatter function. I believe by supplying an array to colour there and set the labels to false, it will plot the colours given by the array.

**Comment by mkrzak** [comment]
Dear @mzwiessele thank you for your response, indeed that's what I am doing now. I thought however plot_latent can have some additional option. Thanks !
