### ISSUE TITLE
model.plot_f() : I can not change the color of the plot

### ISSUE THREAD

**Issue by pjpessi** [SheffieldML/GPy#517]
Hi everyone.
I have to plot different models in one plot, but all of them appear blue.
I tried several things, including a variable color inside model.plot_f(...color=...). 
I found that plot contains several inputs: plot(self, plot_limits=None, fixed_inputs=None, resolution=None, plot_raw=False, apply_link=False, which_data_ycols='all', which_data_rows='all', visible_dims=None, levels=20, samples=0, samples_likelihood=0, lower=2.5, upper=97.5, plot_data=True, plot_inducing=True, plot_density=False, predict_kw=None, projection='2d', legend=True, **kwargs) , but none of them regarding color.
Does anyone know if there is a way to change the color of the plot?
Thank you

**Comment by mzwiessele** [comment]
Yes, just use the actual plotting functions for the pieces, plot_f() is only a convenience function for a quick look. 

M.plot_<tab> will show you the different options.

E.g. To plot the mean you write m.plot_mean(color='g') and for the confidence interval m.plot_confidence(color='y').

**Comment by pjpessi** [comment]
Thank you very much **mzwiessele**. 
Problem solved!!

**Comment by pjpessi** [comment]
Thank you very much!!.
Problem solved!
