### ISSUE TITLE
Data with noise: which is the difference between summing or multiplying the noise?

### ISSUE THREAD

**Issue by pjpessi** [SheffieldML/GPy#519]
Hi everyone.
I have a data set (x,y), the y values have associated noise e1. 
I read that to include the noise you should use the .White and .Bias kernels.
So I have:
```
k = GPy.kern.RBF(input_dim=1,lengthscale=ls)
noise=GPy.kern.White(1,GPy.util.linalg.tdot(e1))+GPy.kern.Bias(1,GPy.util.linalg.tdot(e1))
kernel=k*noise
```
I also tried:
`kernel=k+noise`
 
The results seem to be "better" when I do the multiplication between the kernel and the noise than when I do the sum. But I don't understand the difference between these two ways of considering the noise.

Besides, when I consider the noise, sometimes I get Gaussian_noise.variance << 1e-100, what does that mean?

**Comment by mzwiessele** [comment]
The Gaussian_noise is equivalent to adding a White kernel (in simple GP regression!). That means depending on starting conditions and optimization you can get either of the two switched off. The multiplication is hard to explain. It means the variance of your RBF kernel gets modelled by the White variance and all entries of the RBF kernels are multiplied by a constant from your Bias. It is not clear what it actually means to multiply kernels in an intuitive manner, but you could think of creating dependencies between the noise and the RBF (although these dependencies are not in the probabilistic model, but in the way latent functions f behave..).

**Comment by pjpessi** [comment]
Thank you very much!
