### ISSUE TITLE
climin dependency?

### ISSUE THREAD

**Issue by mikecroucher** [SheffieldML/GPy#520]
This file https://github.com/SheffieldML/GPy/blob/devel/GPy/core/svgp.py has an import of a module called `climin.util` that fails on a vanilla build of GPy.

I imported this https://github.com/BRML/climin and the script I was playing with (A slightly modified version of this: https://github.com/alexggmatthews/GPflow_profiling) started working.

Questions: 

* Is https://github.com/BRML/climin the correct dependency?
* If so, how best to proceed?
    * We could add climin as a dependency (It's only available in the GutHub repo as far as I can tell).
    * We come up with a different way of implementing this part of the code.

**Comment by zhenwendai** [comment]
https://github.com/BRML/climin is the correct dependency. It is also available on pip.

Climin provides the stochastic gradient optimization algorithm which is optional all the rest of GP models apart from SVGP. It would be good to minimize the dependency of GPy for easy deployment.

Currently, we treat it as an optional dependency, but Python does not have a proper way to handle optional dependency.

**Comment by mikecroucher** [comment]
Thanks Zhenwen.  It's not on pip for Python 3.6 it seems

```
 pip install clmin
Collecting clmin
  Could not find a version that satisfies the requirement clmin (from versions: )
No matching distribution found for clmin


 python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by mzwiessele** [comment]
Is the solution as easy as writing 

# pip install climin?

**Comment by lionfish0** [comment]
Just to clarify - the typo in Mike's attempt (clmin vs climin). I found
climin on python 3.6.

Mike
