### ISSUE TITLE
Troubles with mean

### ISSUE THREAD

**Issue by pjpessi** [SheffieldML/GPy#522]
Hi everyone, I am quite new to GPy and I need some help, I don't know if this is the best place to ask this, if not please refer me to the correct place.

I have my model and I plot the mean of the model with m.plot_mean() ,  let's say it looks like a gaussian for simplicity

Now I need to know the maximum of the gaussian, so I need to know the maximum point of the model mean.
I tried using model.predict(x_new, full_cov=False) (and a few more things that didn't work) but when I plot the Y array it doesn't match the mean plot of the model.

Do you know how can I get what I need?

Thank you very much

**Comment by nbeuchat** [comment]
I have the same issue when trying to predict new data from my model. Setting `full_cove = True` did not help either. 

In issue https://github.com/SheffieldML/GPy/issues/414, someone suggested to generate samples from the model and take the mean of all samples (it was for a different issue with predict though). I suppose this would work but I do not understand either the behavior of predict.

**EDIT:** Ok, my bad, I was actually trying to predict before optimizing... @pjpessi : can you share your code? You might have done the same thing as I did.

**Comment by mzwiessele** [comment]
Which x_new are you predicting at? 
The return of 

	Mu, var = model.predict(x) 

are two things:
The mean preadiction mu at positions x and the variance at position x.

**Comment by pjpessi** [comment]
This is a piece of my code:

k = GPy.kern.RBF(input_dim=1,lengthscale=ls,variance=v)
noise=GPy.kern.White(1,GPy.util.linalg.tdot(e1))+GPy.kern.
Bias(1,GPy.util.linalg.tdot(e1))
kernel=k+noise
m = GPy.models.GPRegression(phase2,y2,kernel)
m.optimize()
x_new= np.asarray(np.hstack(np.ndarray.tolist(m.infer_newX(y2)[0])))
xn=x_new[:,None]
y_new=np.asarray((np.hstack(np.ndarray.tolist(m.predict(xn,
full_cov=False)[0]))))

The result is not as bizarre as issue #414 but it is not as exact as i wish.
Here is a picture of the problem:

![image](https://user-images.githubusercontent.com/23323038/28088157-2d437010-665b-11e7-80eb-00b7bc5677ab.png)


Here you can see how the red line (prediction) doesn't match the blue line
(mean)

**Comment by pjpessi** [comment]
I use:

y_new=np.asarray((np.hstack(np.ndarray.tolist(*m.predict(xn,
full_cov=False)[0]*))))

where

x_new= np.asarray(np.hstack(np.ndarray.tolist(m.infer_newX(y2)[0])))
xn=x_new[:,None]

As you see I am using the first array of model.predict (I think, because I
am using model.predict[0]) so I am using what you call mu, that should be
the mean of the model, right?

**Comment by frb-yousefi** [comment]
Yes you are getting mean of the prediction. 
Can you try it with a simpler case like remove the noise part and just try simple RBF kernel and see how your results are changing!
Also, another question is that does the optimisation converge at all? Because default optimisation goes 1000 iterations...

**Comment by pjpessi** [comment]
So I optimized the code:

m.optimize_restarts(num_restarts = 250)

-- 1000 and 250 where giving the same -- and the result was this (note that
I am using a different data set now but the issue is the same:

![image](https://user-images.githubusercontent.com/23323038/28132348-f55bfa1a-6712-11e7-98d4-97b0c0b26295.png)

Then I removed the noise part, keeping the optimization, and the result was
this:

![image](https://user-images.githubusercontent.com/23323038/28132331-e607daf2-6712-11e7-8537-0ff51d05b96e.png)


The mean in both cases look the same to me, the predictions are different
but still not matching the mean. Do you have any idea why?

**Comment by pjpessi** [comment]
Solved this.

What I did was:

```
x4mu=np.linspace(x1[0],x1[len(x1)-1],750)
mu, var = m.predict(x4mu[:,None], full_cov=True)
plt.plot(x4mu,mu,'r+',label='prediction')
```

And now I get the exact plot of the mean.
Thank you very much
