### ISSUE TITLE
Can't set uniform prior with positive constraint

### ISSUE THREAD

**Issue by flomertens** [SheffieldML/GPy#528]
If I have a positive constraint on a hyper-parameter, I can not set a uniform prior on it, even if the min value is positive. It gives me the error:

"Domain of prior and constraint have to match, please unconstrain if you REALLY wish to use this prior"

**Comment by mzwiessele** [comment]
You can just unconstrain the hyper-parameter and use the prior afterwards. That will keep the parameter positive, if the min value is positive.

**Comment by avehtari** [comment]
> You can just unconstrain the hyper-parameter and use the prior afterwards. That will keep the parameter positive, if the min value is positive.

But does it then use the log transformation? HMC does not work well in constrained space, and transformation to unconstrained space (e.g. using log-transformation) is recommended.
