### ISSUE TITLE
Different constraints for different dimensions?

### ISSUE THREAD

**Issue by lionfish0** [SheffieldML/GPy#529]
Hi,
Is there a way of setting different constraints for different lengthscale?

Below I can constrain all the dimensions to the same bounds, but what if I want to have different constraints for different dimensions?
```
import GPy
X = np.array([[1,2],[2,3]])
y = X[:,0][:,None]
k = GPy.kern.RBF(2,ARD=True)
m = GPy.models.GPRegression(X,y,k)
m['.*lengthscale'].constrain_bounded(1,2)
#m['.*lengthscale'][0].constrain_bounded(1,2) ##this doesn't work
m.rbf.lengthscale
```

**Comment by mzwiessele** [comment]
You just subindex whichever entry you want. Keep in mind, that we are doing numpy indexing and numpy swallows dimensions, so you need to keep the dimensions up to receive a slice of the array back and not just a float. You can trigger advanced slicing using additional brackets, e.g.:

m.rbf.lengthscale[:, [0]].constrain_positive()

See https://github.com/sods/paramz/blob/master/tutorial/ParamzSimpleRosen.ipynb <https://github.com/sods/paramz/blob/master/tutorial/ParamzSimpleRosen.ipynb>, or https://stackoverflow.com/questions/2640147/preserving-the-dimensions-of-a-slice-from-a-numpy-3d-array <https://stackoverflow.com/questions/2640147/preserving-the-dimensions-of-a-slice-from-a-numpy-3d-array> for an explanation.

**Comment by lionfish0** [comment]
Thanks! I remember you telling me about this ages ago! Ty!
