### ISSUE TITLE
overflow encountered in expm1

### ISSUE THREAD

**Issue by vhpietil** [SheffieldML/GPy#531]
When I try to optimize with a simple data I get error "overflow encountered in expm1". I get the same error when I run GPy.tests(). Any idea what should I do to get rid of the error? I am runnin Python 3.6.0, Anaconda 4.3.0 (64-bit) on Win8 PC.

**Comment by mzwiessele** [comment]
Is it an error, or just a warning?

**Comment by vhpietil** [comment]
Thanks for your reply. It is just a warning and the results seem to be
good. Sorry that I missed that.

**Comment by Crook-cyber** [comment]
why the predict var is negative number
