### ISSUE TITLE
Underestimate value when dealing with multi-dimension input

### ISSUE THREAD

**Issue by zym604** [SheffieldML/GPy#536]
Hi all,

I have found GPy show wired performance when dealing with multi-dimension input.
My data and script are attached:[model.zip](https://github.com/SheffieldML/GPy/files/1210393/model.zip)

I'm using the same data to test the performance of **GPRegression** model. So it can be seen as a **self-test**, which means the predicted value and true value **should be the same**.

While what I get are:
![figure_1](https://user-images.githubusercontent.com/9557009/29106127-b904fe54-7c98-11e7-8cf6-9c5bff759d75.png)
As you can see, the blue line is the predicted value. It underestimates the true value. Looks like the predicted value is only half of the true value. 
In order to validate this guess, I multiple the predicted value by 2, then I get:
![figure_1-3](https://user-images.githubusercontent.com/9557009/29106169-0be904b2-7c99-11e7-9449-2fc5472da1a4.png)
As can be seen, the (*2) predicted value is exactly same as true value.

I don't know how could this happen, I guess the dimension of model input maybe a potential problem.
So I remove the (*2) operation and then reduce the length of my input in line 9:
From:
`Dnumbers = np.concatenate((data[0][:,1:4],data[1][:,1:4], data[2][:,1:4], data[3][:,1:4]), axis=1)`
To:
`Dnumbers = np.concatenate((data[0][:,1:4],data[1][:,1:4]), axis=1)`
Here **Dnumbers** is part of the input of my model. As you can see, what I do is just reduce the dimension of input.

And this time prediction result becomes much better!
![figure_1-4](https://user-images.githubusercontent.com/9557009/29106413-9211b146-7c9a-11e7-9b19-bcb0e9f3c427.png)

Is this an error of code? Or an error of Gaussian process itself?

Thanks,
Yangmo

**Comment by lionfish0** [comment]
Hi,
I'm not sure if this is the right path, but I imagine it's explaining half
the variance with Gaussian noise and half with the kernel, or something
like that? Either way, I imagine it's a failure of convergence when fitting
the hyperparameters. I ran your code and tried some things.

Try setting:

model[id].rbf.lengthscale = 100.0

before optimisation, to give it a more likely start location? (I find GPy
often needs you to put the hyperparameters in roughly the right ball-park
if it's to optimise them successfully).

You might want to set ARD to true (in the kernel) if the dimensions of x
differ substantially (sorry I didn't pay attention to what the application
or data is).

Hope that helps.

Mike

**Comment by lionfish0** [comment]
I'm not sure if this is the right path, but I imagine it's explaining half
the variance with Gaussian noise and half with the kernel, or something
like that? Either way, I imagine it's a failure of convergence when fitting
the hyperparameters. I ran your code and tried some things.

Try setting:

`model[id].rbf.lengthscale = 100.0`

before optimisation, to give it a more likely start location? (I find GPy
often needs you to put the hyperparameters in roughly the right ball-park
if it's to optimise them successfully).

You might want to set ARD to true (in the kernel) if the dimensions of x
differ substantially (sorry I didn't pay attention to what the application
or data is).

Hope that helps.

**Comment by zym604** [comment]
@lionfish0 Thank you very much! It works! This problem tortures me for a whole night. Thanks for saving me a lot of time : )

**Comment by lionfish0** [comment]
Glad that got sorted.
A brief update: A possibly better way to alter the model is to add a prior on the lengthscale (rather than just rely on the start values). So if you think it's roughly around 100 you could add a lognormal prior on the lengthscale, e.g:

`model[id].rbf.lengthscale.set_prior(GPy.priors.LogGaussian(np.log(100),0.9))`

I'm not sure what sigma (the second parameter to LogGaussian) you'd want...
