### ISSUE TITLE
Constraining Heteroscedastic Noise

### ISSUE THREAD

**Issue by ktiwari9** [SheffieldML/GPy#538]
I have a data that has heteroscedastic noise. While doing Heteroscedastic inference with GPy, I found out that the noise variance is significantly high for some input points while it is acceptable for the others. Is it just because of improper initialization of Heteroscedastic variance or is it because I am not using any constraints ?

The fact is that I dont know the noise variance apriori so I cannot fix the variance using `m.het_Gauss.variance.fix()`. What can I possibly do here to constrain the noise for each input ?

**Comment by mzwiessele** [comment]
You can try to bound the variance by using variance.constrain_bounded(lower, upper), where lower and upper are the bounds, respectively.

**Comment by ktiwari9** [comment]
Hi @mzwiessele ,
Thanks for the hint. 

However, there is one thing that still confuses me. What is the point of fixing the heteroscedastic variance using `m.het_Gauss.variance.fix()` and still calling the model heteroscedastic ? Isn't this contradictory to the definition of a heteroscedastic model ? As far as I can tell, it seems logical to bound the variance like you mentioned above but fixing the variance brings us back to a homoscedastic case.

Please correct me if I am wrong.

**Comment by mzwiessele** [comment]
The name only suggests the capability of the model. You can, however, decide as the modeler and designer to constrain a model by hand.

**Comment by ktiwari9** [comment]
Thank you for the clarification.
