### ISSUE TITLE
Issues with the tutorial to create new kernels

### ISSUE THREAD

**Issue by DiegoRomeres** [SheffieldML/GPy#540]
I am trying to implement my own kernel following the instruction in
http://pythonhosted.org/GPy/tuto_creating_new_kernels.html
but I am encountering several issues.

For this reason, I tried to reproduce the example of the Rational Quadratic Kernel given in the tutorial and it is also not working. Here is what I did.
In GPy/kern/src/ I created a file called rat_quad.py. This is the file

```
from .kern import Kern
import numpy as np


class RationalQuadratic(Kern):

    def __init__(self,input_dim,variance=1.,lengthscale=1.,power=1.):
        super(RationalQuadratic, self).__init__(input_dim, 'rat_quad')
        assert input_dim == 1, "For this kernel we assume input_dim=1"
        self.variance = Param('variance', variance)
        self.lengthscale = Param('lengtscale', lengthscale)
        self.power = Param('power', power)
        self.add_parameters(self.variance, self.lengthscale, self.power)
    
    def parameters_changed(self):
        # nothing todo here
        pass
    
    def K(self,X,X2):
        if X2 is None: X2 = X
        dist2 = np.square((X-X2.T)/self.lengthscale)
        return self.variance*(1 + dist2/2.)**(-self.power)
    
    def Kdiag(self,X):
        return self.variance*np.ones(X.shape[0])
    
    def update_gradients_full(self, dL_dK, X, X2):
        if X2 is None: X2 = X
        dist2 = np.square((X-X2.T)/self.lengthscale)
    
        dvar = (1 + dist2/2.)**(-self.power)
        dl = self.power * self.variance * dist2 * self.lengthscale**(-3) * (1 + dist2/2./self.power)**(-self.power-1)
        dp = - self.variance * np.log(1 + dist2/2.) * (1 + dist2/2.)**(-self.power)
    
        self.variance.gradient = np.sum(dvar*dL_dK)
        self.lengthscale.gradient = np.sum(dl*dL_dK)
        self.power.gradient = np.sum(dp*dL_dK)
    
    def update_gradients_diag(self, dL_dKdiag, X):
        self.variance.gradient = np.sum(dL_dKdiag)
        # here self.lengthscale and self.power have no influence on Kdiag so target[1:] are unchanged
    
    def gradients_X(self,dL_dK,X,X2):
        """derivative of the covariance matrix with respect to X."""
        if X2 is None: X2 = X
        dist2 = np.square((X-X2.T)/self.lengthscale)
    
        dX = -self.variance*self.power * (X-X2.T)/self.lengthscale**2 *  (1 + dist2/2./self.lengthscale)**(-self.power-1)
        return np.sum(dL_dK*dX,1)[:,None]
    
    def gradients_X_diag(self,dL_dKdiag,X):
        # no diagonal gradients
        pass
```

It is exactly the copy and paste of the pieces of code in the tutorial. But when I call the kernel

```
import GPy
k = GPy.kern.RationalQuadratic(input_dim=1, variance=.75, lengthscale=2., power =1.)
```

I am having this error:
`AttributeError: 'module' object has no attribute 'RationalQuadratic'`
I am wondering if something is missing in the tutorial because in this section
http://pythonhosted.org/GPy/tuto_creating_new_kernels.html#structure-of-a-kernel-in-gpy
there are two points listed but immediately after the instructions talk about three steps. Or am I missing something obvious?

**Comment by DiegoRomeres** [comment]
What it was not clear for me from the tutorial is that we need to add in the file `GPy/kern/__init__.py` the line

`from .src.rat_quad import RationalQuadratic`

However, when I call the kernel 
`GPy.kern.RationalQuadratic(input_dim=1, variance=.75, lengthscale=2., power =1.)`
I still have one error:
`{TypeError}_init__() takes at least 4 arguments (3 given)`

**Comment by mzwiessele** [comment]
Good point! We forgot to update the tutorial with the active dimensions (which select which dimenions of the input this kernel works on). Thus, you need to add the active dimensions to the init call:

```python
def __init__(self,input_dim,variance=1.,lengthscale=1.,power=1.,active_dims=None):
        super(RationalQuadratic, self).__init__(input_dim, active_dims, 'rat_quad')
```

**Comment by jorgeloaiza** [comment]
Hello.
I am trying to set Spectral Mixture Kernel in GPy, but when i call it , I get next error:
'SM' object has no attribute 'parameters'

This is code:

class SM(Kern):
    '''
    Gaussian Spectral Mixture covariance function. The
    covariance function is parameterized as:
    k(x^p,x^q) = w'*prod( exp(-2*pi^2*d^2*v)*cos(2*pi*d*m), 2), d = |x^p,x^q|
    where m(DxQ), v(DxQ) are the means and variances of the spectral mixture
    components and w are the mixture weights. The hyperparameters are:
    hyp = [ log(w), log(m(:)), log(sqrt(v(:))) ]
    Copyright (c) by Andrew Gordon Wilson and Hannes Nickisch, 2013-10-09.
    For more details, see
    1) Gaussian Process Kernels for Pattern Discovery and Extrapolation,
    ICML, 2013, by Andrew Gordon Wilson and Ryan Prescott Adams.
    2) GPatt: Fast Multidimensional Pattern Extrapolation with Gaussian
    Processes, arXiv 1310.5288, 2013, by Andrew Gordon Wilson, Elad Gilboa,
    Arye Nehorai and John P. Cunningham, and
    http://mlg.eng.cam.ac.uk/andrew/pattern
    :param log_w: weight coefficients.
    :param log_m: spectral means (frequencies).
    :param log_v: spectral variances.
    '''

    def __init__(self, input_dim,Q, hyps=[], D=None,active_dims=None):
        assert input_dim==1, "SM kernels are only defined for input_dim=1"
        super(SM, self).__init__(input_dim,Q,hyps=[],D,active_dims)
        if D:
            self.hyp = np.random.random(Q*(1+2*D))
        else:
            self.hyp = hyps
        self.para = [Q]

    def initSMhypers(self, x, y):
        """
        Initialize hyperparameters for the spectral-mixture kernel. Weights are
        all set to be uniformly distributed, means are given by a random sample
        from a uniform distribution scaled by the Nyquist frequency, and variances are given by a random sample from a uniform distribution scaled by the max distance.
        """
        x = np.atleast_2d(x)
        y = np.atleast_2d(y)
        (n, D) = x.shape
        Q = self.para[0]
        w = np.zeros(Q)
        m = np.zeros((D, Q))
        s = np.zeros((D, Q))
        w[:] = old_div(np.std(y), Q)
        hypinit = np.zeros(Q + 2 * D * Q)

        for i in range(D):
            # Calculate distances
            xslice = np.atleast_2d(x[:, i]).T
            d2 = spdist.cdist(xslice, xslice, 'sqeuclidean')
            if n > 1:
                d2[d2 == 0] = d2[0, 1]
            else:
                d2[d2 == 0] = 1
            minshift = np.min(np.min(np.sqrt(d2)))
            nyquist = old_div(0.5, minshift)
            m[i, :] = nyquist * np.random.ranf((1, Q))
            maxshift = np.max(np.max(np.sqrt(d2)))
            s[i, :] = old_div(1., np.abs(maxshift * np.random.ranf((1, Q))))
        hypinit[:Q] = np.log(w)
        hypinit[Q + np.arange(0, Q * D)] = np.log(m[:]).T
        hypinit[Q + Q * D + np.arange(0, Q * D)] = np.log(s[:]).T
        self.hyp = list(hypinit)

    def getCovMatrix(self,x=None,z=None,mode=None):
        self.checkInputGetCovMatrix(x,z,mode)
        Q = self.para[0]
        if mode == 'self_test':
            nn, D = z.shape
        else:
            nn, D = x.shape
        assert Q == old_div(len(self.hyp), (1 + 2 * D))

        w = np.exp(self.hyp[:Q])
        m = np.exp(np.reshape(self.hyp[Q:Q + Q * D], (D, Q)))
        v = np.exp(2 * np.reshape(self.hyp[Q + Q * D:], (D, Q)))

        if mode == 'self_test':               # self covariances for the test cases
            d2 = np.zeros((nn, 1, D))
        elif mode == 'train':                 # compute covariance matix for dataset x
            d2 = np.zeros((nn, nn, D))
            for j in range(D):
                xslice = np.atleast_2d(x[:, j]).T
                d2[:, :, j] = spdist.cdist(xslice, xslice, 'sqeuclidean')
        elif mode == 'cross':                 # compute covariance between data sets x and z
            d2 = np.zeros((nn, z.shape[0], D))
            for j in range(D):
                xslice = np.atleast_2d(x[:, j]).T
                zslice = np.atleast_2d(z[:, j]).T
                d2[:, :, j] = spdist.cdist(xslice, zslice, 'sqeuclidean')
        d = np.sqrt(d2)

        k = lambda d2v_dm: np.exp(-2 * np.pi ** 2 * d2v_dm[0]) * np.cos(2* np.pi * d2v_dm[1])  # evaluation of the covariance
        km = lambda dm: -2 * np.pi * np.tan(2 * np.pi * dm) * dm  # remainder when differentiating w.r.t. m
        kv = lambda d2v: -d2v * (2 * np.pi) ** 2  # remainder when differentiating w.r.t. v

        A = 0.
        c = 1.
        qq = list(range(Q))
        for q in qq:
            C = w[q] * c
            for j in range(D):
                C = C * k((d2[:, :, j] * v[j, q], d[:, :, j] * m[j, q]))
                A = A + C
        return A

    def getDerMatrix(self,x=None,z=None,mode=None,der=None):
        self.checkInputGetDerMatrix(x,z,mode,der)
        Q = self.para[0]
        if mode == 'self_test':
            nn, D = z.shape
        else:
            nn, D = x.shape
        assert Q == old_div(len(self.hyp), (1 + 2 * D))

        w = np.exp(self.hyp[:Q])
        m = np.exp(np.reshape(self.hyp[Q:Q + Q * D], (D, Q)))
        v = np.exp(2 * np.reshape(self.hyp[Q + Q * D:], (D, Q)))

        if mode == 'self_test':               # self covariances for the test cases
            d2 = np.zeros((nn, 1, D))
        elif mode == 'train':                 # compute covariance matix for dataset x
            d2 = np.zeros((nn, nn, D))
            for j in range(D):
                xslice = np.atleast_2d(x[:, j]).T
                d2[:, :, j] = spdist.cdist(xslice, xslice, 'sqeuclidean')
        elif mode == 'cross':                 # compute covariance between data sets x and z
            d2 = np.zeros((nn, z.shape[0], D))
            for j in range(D):
                xslice = np.atleast_2d(x[:, j]).T
                zslice = np.atleast_2d(z[:, j]).T
                d2[:, :, j] = spdist.cdist(xslice, zslice, 'sqeuclidean')
        d = np.sqrt(d2)

        k = lambda d2v_dm1: np.exp(-2 * np.pi ** 2 * d2v_dm1[0]) * np.cos(2* np.pi * d2v_dm1[1])  # evaluation of the covariance
        km = lambda dm: -2 * np.pi * np.tan(2 * np.pi * dm) * dm  # remainder when differentiating w.r.t. m
        kv = lambda d2v: -d2v * (2 * np.pi) ** 2  # remainder when differentiating w.r.t. v

        A = 0.
        c = 1.
        qq = list(range(Q))
        if der < Q:                         # compute derivative matrix wrt w
            c = 1
            qq = [der]
        elif der < Q + Q * D:               # compute derivative matrix wrt sig
            p = (der - Q) % D
            q = old_div((der - Q - p), D)
            c = km(d[:, :, p] * m[p, q])
            qq = [q]
        elif der < 2 * Q * D + Q:           # compute derivative matrix wrt mu
            p = (der - (D + 1) * Q) % D
            q = old_div((der - (D + 1) * Q - p), D)
            c = kv(d2[:, :, p] * v[p, q])
            qq = [q]
        else:
            raise Exception("Wrong derivative entry in SM")

        for q in qq:
            C = w[q] * c
            for j in range(D):
                C = C * k((d2[:, :, j] * v[j, q], d[:, :, j] * m[j, q]))
                A = A + C
        return A

**Comment by mzwiessele** [comment]
It seems you are not calling the super initializer in your __init__ to setup the kernel structure.

**Comment by AaronYeardley** [comment]
Hi,
I am working through the creating a new kernel tutorial and I'm struggling to get the same first derivative with respect to lengthscale (dl) as in the tutorial.
The tutorial says it is
dl = self.power * self.variance * dist2 * self.lengthscale**(-3) * (1 + dist2/2./self.power)**(-self.power-1)
this equates to this image I think hopefully you can see
![image](https://user-images.githubusercontent.com/48969215/87671619-8d0aa500-c769-11ea-8a59-36fa2f809f79.png)
Please note I have been lazy in the writing of this equation so x' = y, the variance is not squared, the lengthscale is l and the power is alpha.
So what I don't understand is where the second to last self.power, the alpha comes from in the brackets which are when raised to the power of -alpha- 1.
When I differentiate the kernel with respect to the lengthscale I get:
![image](https://user-images.githubusercontent.com/48969215/87673115-e8d62d80-c76b-11ea-9825-0c08ec50d624.png)
