### ISSUE TITLE
Updating prior's parameters after initialization causes further computation of the pdf to be wrong

### ISSUE THREAD

**Issue by acruis** [SheffieldML/GPy#541]
Let's look at the [pdf computation for the `InverseGamma` prior](https://github.com/SheffieldML/GPy/blob/devel/GPy/core/parameterization/priors.py#L361):

The computation makes use of `self.constant`, which is only computed once in the initializer. Thus, if we change, say, the shape parameter `a`, computations of `lnpdf` and `lnpdf_grad` will then be wrong because they rely on the value of `constant`.

```python
prior =  GPy.priors.InverseGamma(1.5, 1.5)
print prior.constant # 0.728979899797
prior.a = 2.0 
print prior.constant # 0.728979899797

# The following 2 should agree, but don't.
print prior.pdf(3.0) # 0.0465672876457
print -gammaln(prior.a) + prior.a * np.log(prior.b) - (prior.a + 1.) * np.log(3.0) - prior.b / 3.0 # -2.98490664979
```

When `a` or `b` are modified, `constant` should also be modified - probably through some sort of observer?

**Comment by mzwiessele** [comment]
Has been fixed in the newest GPy. Updating the priors constants is now not possible anymore. Just create and set a new prior to update the constants.

**Comment by acruis** [comment]
Is there a mechanism to track which parameters are connected to a prior?

If I have a lot of parameters that are connected to different priors, when I change a prior's hyperparameters I would need to re-set only the subset of parameters that are connected to said prior, so I'd end up needing to track which parameters are connected to which priors.

I suppose it's fine if there isn't one such mechanism; tracking the parameters should only introduce insignificant overhead, though that's one possible point of error when developing a non-trivial model employing many different priors.
