### ISSUE TITLE
Multiple Output Gaussian Process Revision

### ISSUE THREAD

**Issue by peiyaoli** [SheffieldML/GPy#550]
Hi, everyone, I have one question regarding multiple output gaussian process.
In the tutorial, the project assume that tasks' observation model is same, but what if different task has different observation model(likelihood). For instance, one task is poisson model since it is a "count" problem, others are gaussian likelihood? What I want to do is to use MTGP framework to improve the prediction accuracy. I have been stuck at this place for a long time and didn't find a good solution, could anyone give me some hints or help? Thanks!

**Comment by ric70x7** [comment]
Hi peiyaoli,
The framework is built to allow different likelihoods for each output.
These are handled by the object MixedLikelihood. Unfortunately, the pieces
that are in place at the moment only allow the use of different Gaussian
likelihoods. At least that was the case last time I checked...
Could you work the Poisson output in the log-scale and treat it as
Gaussian?
Cheers,
Ricardo

**Comment by mzwiessele** [comment]
This Is being addressed in PR #596 and will be in the next release :)
