### ISSUE TITLE
Latest version of paramz missing dependencies for GPy

### ISSUE THREAD

**Issue by chase-dwelle** [SheffieldML/GPy#555]
If you follow the installation instructions in the `README`, the newest version of `scipy` will install `paramz-0.8.3`. This version does not have the `paramz.ties_and_remappings` module required for GPy.

As this is the only package that I use that I know uses paramz, I just uninstalled and reinstalled version 0.7.4 which does have the required module via:
```
pip uninstall paramz
pip install paramz==0.7.4
```
Just a note for future development work to find whatever module they have moved `ties_and_remapping` to.

**Comment by mzwiessele** [comment]
Thanks for the reminder, I will update GPy to the newest paramz.
