### ISSUE TITLE
Marginalize input dimensions?

### ISSUE THREAD

**Issue by roger-** [SheffieldML/GPy#567]
I have a model trained for an input dimension if size 3 but sometimes I want to test it with two of those dimensions missing (so a one input input dimension). 

Is there an easy way to marginalize/drop input dimensions in a trained GPy model?

**Comment by zhenwendai** [comment]
It is not supported in GPy. 

For marginalization, you need first to specify the prior distribution over the dimensions that will be marginalized out. Unfortunately, for most kernels and most prior distributions, the answers of such marginalization is not tractable. However, you can relatively easily get the answer through Monte Carlo Integration (sampling) by calling GPy prediction function for each sample.
