### ISSUE TITLE
Prod kernel does not unwrap component Prod kernels correctly

### ISSUE THREAD

**Issue by acruis** [SheffieldML/GPy#568]
The issue occurs when a `Prod` kernel is created with multiple `Prod` kernels as the argument. For example:

```python
k1 = GPy.kern.RBF(input_dim=1, variance=1, lengthscale=1)
k2 = GPy.kern.RBF(input_dim=1, variance=2, lengthscale=2)
k3 = GPy.kern.RBF(input_dim=1, variance=3, lengthscale=3)
k4 = GPy.kern.RBF(input_dim=1, variance=4, lengthscale=4)

print ((k1 * k2) * (k3 * k4))
```

The above code would produce:

```
  mul.               |  value  |  constraints  |  priors
  rbf.variance       |    1.0  |      +ve      |        
  rbf.lengthscale    |    1.0  |      +ve      |        
  rbf_1.variance     |    3.0  |      +ve      |        
  rbf_1.lengthscale  |    3.0  |      +ve      |        
  rbf_2.variance     |    4.0  |      +ve      |        
  rbf_2.lengthscale  |    4.0  |      +ve      |        
```

One of the RBF kernels (`k2`) has gone missing. Instead, if we do:

```python
print Prod([k1, k2, k3, k4])
```

We correctly get all 4 RBF kernels.

```
  mul.               |  value  |  constraints  |  priors
  rbf.variance       |    1.0  |      +ve      |        
  rbf.lengthscale    |    1.0  |      +ve      |        
  rbf_1.variance     |    2.0  |      +ve      |        
  rbf_1.lengthscale  |    2.0  |      +ve      |        
  rbf_2.variance     |    3.0  |      +ve      |        
  rbf_2.lengthscale  |    3.0  |      +ve      |        
  rbf_3.variance     |    4.0  |      +ve      |        
  rbf_3.lengthscale  |    4.0  |      +ve      |        
```

The root of this issue lies in [the `__init__` method for `Prod`](https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/prod.py#L33). The second instance of the outer `for` loop examines `i, kern` where `i` is 1 and `kern` is `Prod`, so `del kernels[1]` gets called, which deletes `k2` from the list of kernels.

One proposed fix is to change the logic in `Prod.__init__` to be the same as [`Add.__init__`](https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/add.py#L20), which is already immune to the above problem.

**Comment by mzwiessele** [comment]
Yes that should definitely be done, care to put in a Pull Request with the suggested fix?
