### ISSUE TITLE
"not positive definite, even with jitter" error on a StdPeriodic kernel

### ISSUE THREAD

**Issue by acruis** [SheffieldML/GPy#569]
The data that I am using is the [motorcycle crash dataset](http://www.stat.cmu.edu/~larry/all-of-statistics/=data/motor.dat). In particular, I'm using the `times` column as my `x`, and `accel` as my `y`.

The code that I'm using is the following:

```python
kern = GPy.kern.StdPeriodic(input_dim=1)
m = GPy.models.GPRegression(x, y, kern, noise_var=1.0)
m.likelihood.variance.fix(warning=False)
m.optimize()
```

Fixing `m.likelihood.variance` causes the not-positive-definite error to occur on `m.optimize()`. Even randomizing the kernel parameter array (using `kern.randomize()`) before assigning it to the model still causes the same issue to arise.

Is it something particularly wrong with the data that triggers this problem, or is it something to do with how `StdPeriodic` was implemented? I've attempted to slice the data in various ways, but the error still pops up unless I slice a very small section of the data.

**Comment by mzwiessele** [comment]
It might be in conjunction with `StdPeriodic`, but in any case, have you tried normalizing (standardizing) the inputs `x` and outputs `y`?

**Comment by mzwiessele** [comment]
Where do the parameters end up when the error occurs? It might be the period parameter, as it is highly non convex in the optimization.

**Comment by roshambo919** [comment]
I had this issue with an RBF+bias kernel, and normalizing the inputs fixed it!
