### ISSUE TITLE
Problem with multi dimensions GPy

### ISSUE THREAD

**Issue by malsioufi** [SheffieldML/GPy#577]
Hi there,
I am new to use GPy, I am trying to make a simple model that takes 2 input (xtrain1, xtrain2) and a single output so here's my code where `data` is an array of sensor readings and I am trying to estimate the coming readings

```
Xtrain1 = data[0:200]
Xtrain2 = data[23:223]

Ytrain = data[24:224]

Xtest1 = data[225:250]
Xtest2 = data[248:273]

Ytest = data[249:274]

Xtrain = [Xtrain1,Xtrain2]
Xtest = [Xtest1,Xtest2]

kernel = GPy.kern.RBF(input_dim=2, variance=1., lengthscale=1.)
m = GPy.models.GPRegression(Xtrain, Ytrain, kernel=kernel)

m.optimize()
simY, simMse = m.predict(Ytest)
```
 Everything work as expected when I insert `Xtrain1` and `Yrtain` to the model but when I tried to add another input `Xtrain2` I got this error
_**'list' object has no attribute 'ndim'**_

**Comment by wqinc** [comment]
ndim is an attribute for numpy ndarray, so I believe wrapping your Xtrain as a numpy array should solve this issue

**Comment by malsioufi** [comment]
Thank you for the reply, I changed my code like this 
```
Xtrain1 = data[0:200]
Xtrain2 = data[23:223]

Ytrain = data[24:224]

Xtest1 = data[225:250]
Xtest2 = data[248:273]

Ytest = data[249:274]

Xtrain =np.array([Xtrain1,Xtrain2])
Xtest = np.array( [Xtest1,Xtest2])

kernel = GPy.kern.RBF(input_dim=2, variance=1., lengthscale=1.)
m = GPy.models.GPRegression(Xtrain, Ytrain, kernel=kernel)

m.optimize()
simY, simMse = m.predict(Ytest)
```
and now I got this error 

....gp.py", line 41, in __init__
    assert X.ndim == 2

AssertionError

any idea?

**Comment by mzwiessele** [comment]
What are the dimensions of your data object?

GPy assumes at least one column array as input.

```python
assert(data.ndim == 2) # make sure the data object has a column
```

If not, you need to change the data input to a column array:

```python
data = data[:, None]
```

Be aware, that data has more than 2 dimensions the above won't work and you need to get rid of the excess dimensions.

**Comment by Kotsakis** [comment]
Had the same issue and solved it by reshaping my Y to 
    
    Y = responseData.values.reshape(X.shape[0], 1)
