### ISSUE TITLE
Cannot import Gpy, but installation correct

### ISSUE THREAD

**Issue by geilerloui** [SheffieldML/GPy#586]
Hi,
I have downloaded Gpy and installed with "pip install gpyopt"  I have the below message print

Installing collected packages: GPy, gpyopt
Successfully installed GPy-1.8.5 gpyopt-1.2.1

I have anaconda installed so I have checked
with "conda list" if all the packages were installed 

GPy                       1.8.5                     <pip>
GPyOpt                    1.2.1                     <pip>

Then I did:
> Python
> import Gpy 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Gpy'

I don't know what is the problem.
Thanks

**Comment by danlg** [comment]
@geilerloui got the same issue. How did you solve it ?

**Comment by danlg** [comment]
```
conda list|grep -i gpy
GPy                       1.9.5                     <pip>
GPyOpt                    1.2.5                     <pip>
$python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Gpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Gpy'
```
