### ISSUE TITLE
Normalization does not work with SparseGPRegression

### ISSUE THREAD

**Issue by slishak** [SheffieldML/GPy#590]
When building models with `SparseGPRegression`, the normalized outputs don't seem to be used for the model but the predictions are still de-normalized, resulting in a model that appears to have been "de-normalized" twice. Digging through the code, I think it's because in `sparse_gp.py` `self.Y` is used instead of `self.Y_normalized`:

https://github.com/SheffieldML/GPy/blob/c5fb6226e19e080af3ce29a29c7fdd6e5d8bba65/GPy/core/sparse_gp.py#L76-L80

In the base method in `gp.py` `self.Y_normalized` is used:

https://github.com/SheffieldML/GPy/blob/c5fb6226e19e080af3ce29a29c7fdd6e5d8bba65/GPy/core/gp.py#L246-L259

**Comment by mzwiessele** [comment]
Oh wow, that is terrible! 

Great spotting, have to fix it right away.
