### ISSUE TITLE
Combining models - possible?

### ISSUE THREAD

**Issue by qwer1304** [SheffieldML/GPy#594]
Is it somehow possible to combine models, e.g. MRD & LVMOGP?

**Comment by mzwiessele** [comment]
In what manner? What are you trying to achieve?

**Comment by qwer1304** [comment]
I need to build a model that deals with data coming from several sensors (so it's multi-view), but also has a hidden input (condition) (e.g., different subject) and some output which is a function of both datas.

Note that I cannot use the trick used in MRD for Automatic Correlation Learning of Output Dimensions because the conditions change and their number isn't fixed.

Both MRD and LVMOGP are in GPy, but I'd need to combine them in a single model.

The closest I found (IMHO) is input imputation with LVMGOP (Sensor Imputation experiment), but I'm not sure how to handle the output.

**Comment by mzwiessele** [comment]
If I understand right (and I am not sure about it) you could do a two step
approach, in which you feed the output of a LVMGOP to the MRD and learn the
last input dimension in a second step. You could iterate until convergence
or just take the greedy solution.

2018-01-17 14:49 GMT+01:00 qwer1304 <notifications@github.com>:
