### ISSUE TITLE
Error when creating a standard  model: _fblas.dsyrk to C/Fortran array

### ISSUE THREAD

**Issue by jpmerlet** [SheffieldML/GPy#595]
Hi there!

Im a little new in using GPy and GitHub, then sorry if im not clear enough. Im working with geostatistical data, and want to use Gpy to make regression. My code and the error message looks something like this :

```
# get data, and standarize it
X, y = get_training_set()
X_std = (X - X.mean()) / X.std()
y_std = (y - y.mean()) / y.std()

# set model functions
ker  = GPy.kern.Matern32(input_dim=2, active_dims=[0,1]) + GPy.kern.Bias(3)
lik = GPy.likelihoods.Gaussian()
inf = GPy.inference.latent_function_inference.ExactGaussianInference()
m = GPy.core.GP(X_std, y_std, kernel=ker, likelihood=lik, inference_method=inf)
.
.
.
error: failed in converting 2nd keyword `c' of _fblas.dsyrk to C/Fortran array 
```
I would like to know just some insights in order to dont get that error. Or how could i catch it (cause im creating models iteratively, so i just want this message  dont kill my for loop).

Thanks in advances

**Comment by mzwiessele** [comment]
I'm not certain, but it seems your training data is not in C order. Try making copies of your data set (X,y) before giving it to GPy.

**Comment by jpmerlet** [comment]
Oh at end it was very silly the reason: in some iteration of my code i was giving a  matrix of dimension zero 😅😅😅

I know one is not supposed to do such a mistake, but it could be helpful to make more clear the error message

By the way: what does 'to be in C order' mean?

**Comment by mzwiessele** [comment]
It is about the memory layout of the array. In memory an array is always sequential and the indices have to jump either for rows or columns of the array in order to index the right memory.

See e.g. https://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays for a better description.
