### ISSUE TITLE
how to train a multi-task GP under GPy framework

### ISSUE THREAD

**Issue by shalijiang** [SheffieldML/GPy#601]
with a single dataset (X, Y), we can optimize the model as follows:
m = GPy.models.GPRegression(X, Y, kernel=kernel, mean_function=mean_function)
m.optimize(messages=True, max_f_eval = 1000)

what if we want to optimize the model by minimizing the sum of negative log likelihood of multiple datasets (say the simplest case: independent multitask). Is there a way to do that with GPy?

**Comment by mzwiessele** [comment]
Yes, just provide GPy with a multidimensional dataset Y \in R^(N, D), where D is the number of tasks, and N are the number of smples/datapoints you have.

**Comment by shalijiang** [comment]
thanks. 
maybe I shouldn't say multitask. Actually what I want is: optimize the sum of likelihoods of several independent datasets (X_1, Y_1), (X_2, Y_2), ...., (X_k, Y_k)

**Comment by mzwiessele** [comment]
Yes you can just create a new model with GPs as parameters, but linking them ( The objective function will be the sum of the negative log-likelihoods (or just the objective functions of the GPs). 

See 
https://github.com/sods/paramz/blob/master/tutorial/ParamzSimpleRosen.ipynb or
https://github.com/sods/paramz/blob/master/paramz/examples/ridge_regression.py
for how to create a model.

You won’t need to implement the parameters changed method, as the gradient of each GP is handled internally. 

You can add as many GPs as you like and edit them according to your needs (kernels, likelihoods, inference etc.) as models are just parameters themselves.
