### ISSUE TITLE
Consultation

### ISSUE THREAD

**Issue by jorgeloaiza** [SheffieldML/GPy#608]
¿Can anybody tell me if the Spectral Mixture kernel is in GPy Framework?
Thanks a lot.

**Comment by zhenwendai** [comment]
As far as I know. we do not have spectral mixture kernel in GPy.

**Comment by jorgeloaiza** [comment]
Ok

Thanks of lot!

________________________________
De: Zhenwen Dai <notifications@github.com>
Enviado: viernes, 09 de marzo de 2018 5:30:21 p. m.
Para: SheffieldML/GPy
Cc: jorgeloaiza; Author
Asunto: Re: [SheffieldML/GPy] Consultation (#608)


As far as I know. we do not have spectral mixture kernel in GPy.
