### ISSUE TITLE
Incompatibility between matplotlib and visual

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#61]
Not sure of the solution yet, but when I try and close the matplotlib plot and/or visual scene window ipython crashes. I searched online and found this post:

http://www.wired.com/wiredscience/2010/07/visual-and-matplotlib-holding-hands-at-last/

which doesn't give any more info than "There is still one problem. If you try to run a visual display window and a matplotlib graph at the same time, bad things can happen. Sort of like crossing the streams in Ghostbusters."

Sounds nasty ... hmmmm ... will leave it crashing for the moment :-(

Worst case solution is we have to do a separate latent plot visualization in visual :-(

**Comment by jameshensman** [comment]
Dependency on visual has been resolved for some time. Closing
