### ISSUE TITLE
GPy delivers "wrong" results compared to gpflow

### ISSUE THREAD

**Issue by cs224** [SheffieldML/GPy#614]
The following gist shows the problem: http://nbviewer.jupyter.org/gist/cs224/7392f0f437f0a7c0a4d30bd4cc9dea47

I did a gaussian process regression with a very simple model with GPy and gpflow.

GPy delivers the parameters (see the gist for details) [40.030416, 9.384762,1.833270] and gpflow delivers the parameters [7.453232,1.534628,1.256520]. 

If I call optimize() twice on the GPy model then GPy agrees with the gpflow parameters.

I did not manage to provide parameters to optimize() (e.g. m.optimize(gtol=1e-08, bfgs_factor=10.0)) so that GPy would come to the "correct" conclusion on first attempt rather than calling optimize() twice. As far as I understand GPy only forwards the gtol and bfgs_factor parameters to scipy.optimize.fmin_l_bfgs_b: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html#scipy.optimize.fmin_l_bfgs_b

I would like to use GPy, because it actually is faster (even if calling optimize twice) than gpflow, but I would like to be sure that I get the correct results. How do I do that?

Thanks a lot,
Christian

**Comment by mzwiessele** [comment]
Here are some questions which could be the reason for the differing results:

- Are the initial conditions the same in both cases? 
- What happens if you give the intermediate result as initial parameters to GPFlow?
- Are the constraints the same between GPFlow and GPy (Logexp)?
- Is GPFlow using lbfgsb or just bfgs?

The easiest to check all the above is to compare the likelihoods of both frameworks with the respective parameters side by side, alongside their gradients, respectively. If the likelihoods are the same, then there could be slight differences in the gradients computed.

**Comment by cs224** [comment]
Please have a look at the attached notebook.

* The initial conditions are the same. See notebook
* I tried the same "cross check" that I tried with GPy also with gpflow and both, GPy and gpflow come up with the result that the gpflow result has the better objective.
* The constraints are the same.
* I debugged a bit into the deeper layers of gpflow and it also uses the SciPy Optimizer that uses by default the ''L-BFGS-B' method of SciPy.

GPy agrees that the objective is better at the point that gpflow finds and comes to the same conclusion as gpflow if you run the optimizer twice. Isn't that alone strange and a reason to investigate?

I am transforming a batch of curves and the discrepancy only shows up in some cases. I have several curves that show the discrepancy if you would need more cases. For the majority of cases gpflow and GPy agree.

**Comment by mzwiessele** [comment]
So the only reason could be the gradients coming up different in the moment when GPy stops optimizing. Are they the same?

**Comment by cs224** [comment]
I am neither an expert of gpflow nor an expert of GPy. I don't know.
At the moment the conclusion for me is to trust gpflow but not trust GPy. I would prefer to use GPy, becaue it actually runs faster.

As said above: why does GPy come up with the same answer as gpflow to the optimization problem if you run optimize() twice? Why would you need to compare the gehaviour of GPy with the behaviour of gpflow, if you can look into why does running optimize() twice deliver a considerably different result than running it once? Shouldn't the "stop" conditions for the optimization problem be the same in both cases and the second optimize() just confirm the result of the first optimize()?

**Comment by mzwiessele** [comment]
The only reason I can think of is the gradients, as they are used by the optimizer as stopping criterion.

**Comment by cs224** [comment]
I disagree with closing this issue. I spent quite a lot of time to create a minimal reproducible test case and do not understand why you would not use this as the basis for digging deeper.

**Comment by adamian** [comment]
I've modified the last cell of your notebook as follows:

```
m_start = create_gpy_model(X, Y, kl=90.0, kv=3.0 ** 2, lv=1.0)
m_start.optimize(optimizer='scg')  # Change optimizer to 'scg'
m_start
```

For what it's worth, if you use 'scg' optimizer (which in my experience is a little less "aggressive" than bfgs) gives the result you want. Something causes lbfgs to stop early (maybe the line-search), I don't know exactly how it's called within gpflow, maybe it's called with different default flags?

**Comment by cs224** [comment]
@adamian thanks a lot for looking into this!
I did some experiments. Of course correctness is more important than speed, but the scg method takes 14 seconds wall time vs. 1.17 seconds for the default method.

The other point is that I have several of such examples where GPy and gpflow disagree and while scg delivers the "correct" result for the example I posted above it does not create the correct result in other such cases. I'll create another example where the scg method also disagrees and post it here then.

**Comment by cs224** [comment]
For the following example: http://nbviewer.jupyter.org/gist/cs224/f98a892e9c64d967a65a5452905757d0
The time difference is enormous (nearly 1.5 minutes) and the Objective disagrees still.

**Comment by mzwiessele** [comment]
I have had a look and it is because of the initial conditions you set. 

If I start with `kl=1, kv=1, lv=1`, I get the result with a `log_lik = 777.<>` 

```
m_start = create_gpy_model(X, Y, kl=1, kv=1, lv=1.0)
m_start.optimize()
m_start
```

```
Model: GP regression
Objective: 777.7400256812708
Number of Parameters: 3
Number of Optimization Parameters: 3
Updates: True
```
GP_regression. | value | constraints | priors
-- | -- | -- | --
rbf.variance | 1.5346120873983926 | +ve |  
rbf.lengthscale | 7.453202482499298 | +ve |  
Gaussian_noise.variance | 1.2565150523330144 | +ve |
