### ISSUE TITLE
Importing GPy without installing

### ISSUE THREAD

**Issue by Erhanjinn** [SheffieldML/GPy#621]
Hello,

is it possible to import GPy without installing it?

I have packaged it into an egg file using provided setup.py script, but I cannot import it without installing it. After `easy_install`ing, I can import GPy just fine.

```
egg_path_gpy='/home/name/GPy-1.9.2-py3.4-linux-x86_64.egg'
egg_path_paramz='/home/name/paramz-0.9.1-py3.5.egg'

import sys

sys.path.append(egg_path_gpy)
sys.path.append(egg_path_paramz)

import os
os.environ['PYTHON_EGG_CACHE'] = '/home/name/.python-eggs'

#from setuptools.command import easy_install
#easy_install.main( ["-U","GPy"] ) # With this, GPy gets imported, otherwise it doesn't

import scipy as sp #fine
import paramz # fine
import GPy #throws error
```

The error I get when importing is 
`NotADirectoryError: [Errno 20] Not a directory: '/home/name/GPy-1.9.2-py3.4-linux-x86_64.egg/GPy/defaults.cfg'`

Does anyone have a clue, please?

**Comment by mzwiessele** [comment]
The installation installs the config file in either your installation directory or your home directory. In your .egg this config file seems to be missing. You could try to copy the defaults.cfg file from the zip over into the above directory so GPy can load the configuration from the directory.
