### ISSUE TITLE
Confused about how to implement 2d input and 2d output regression model

### ISSUE THREAD

**Issue by jonnyfrazer** [SheffieldML/GPy#625]
I'm trying to build a regression model with 2d input and 2d output but I'm getting a bit confused about how to implement this. Taking the tutorial [Coregionalized Regression Model](http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/coregionalized_regression_tutorial.ipynb) as an example, I would just like to modify the model such that f_output1 and f_output2 are functions of two variables. I then thought I could simply change input_dim = 2 everywhere but this does not seem to work. 

I'm pasting an example of the sort of thing I was trying below

```
f_output1 = lambda x, y: 4. * np.cos(x/5.) - .4*x - 35. + np.random.rand(x.size)[:,None] * 2. + y  
f_output2 = lambda x, y: 6. * np.cos(x/5.) + .2*x + 35. + np.random.rand(x.size)[:,None] * 8. + 2*y
X1 = np.random.rand(100)[:,None]; X1=X1*75
X2 = np.random.rand(100)[:,None]; X2=X2*70 + 30

X2d = np.array([(X1.T)[0],(X2.T)[0]]).T # Put input data in the form I was expecting to be necessary based on multiple input examples in other tutorials

Y1 = f_output1(X1,X2)
Y2 = f_output2(X1,X2)

K = GPy.kern.Matern32(1)
icm = GPy.util.multioutput.ICM(input_dim=2,num_outputs=2,kernel=K)
m = GPy.models.GPCoregionalizedRegression([X2d,X2d],[Y1,Y2],kernel=icm)
m['.*Mat32.var'].constrain_fixed(1.) #For this kernel, B.kappa encodes the variance now.
m.optimize()
print(m)
```
Any help would be much appreciated. I'm very new to all this.
Also, many thanks for your fantastic work.

**Comment by janvanrijn** [comment]
I'm not a contributor of this library, but to me it seems like your input array (X2d) has the wrong dimensions. 

According to [this notebook](http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/coregionalized_regression_tutorial.ipynb) it should be of shape: (num_tasks, num_observations, num_inputs) but in your case it seems to be just (num_observations, num_inputs).

**Comment by jonnyfrazer** [comment]
@janvanrijn thanks a lot for your response but alas I don't really follow. In the coregionalized_regression_tutorial notebook the input data is

```
X1 = np.random.rand(100)[:,None]; X1=X1*75
X2 = np.random.rand(100)[:,None]; X2=X2*70 + 30
```
and so `X1.shape` gives (100, 1). In my attempt above, `X2d.shape` gives (100, 2). So I don't really know what object it is that you are referring to that has tensor rank 3.

**Comment by ric70x7** [comment]
Yes, you just need to use input_dim=2 everywhere. Unfortunately in the
example input_dim is not explicit in the matern kernel.
GPy.kern.Matern32(1) is in fact GPy.kern.Matern32(input_dim=1).
Just change it for GPy.kern.Matern32(input_dim=2) and it should work.

**Comment by jonnyfrazer** [comment]
@ric70x7 Yup! Now it appears to be working! THANK YOU!!!

**Comment by SiyuanHuang95** [comment]
> @ric70x7 Yup! Now it appears to be working! THANK YOU!!!

Quick Question. So now you have a input_dim = 2, output_dim = 2, but how could you make a prediction, with m(np.asarray(X2d),Y_,etadata)? It always ask me:
`AssertionError: need at least column vectors as inputs to kernels for now, given X2.shape=(1, 100, 2)
`
Any help is greatful!

**Comment by gehbiszumeis** [comment]
``` python
def convert_input_for_multi_output_model(x, num_outputs):
    """
    This functions brings test data to the correct shape making it possible to use the `predict()` method of a trained
    `GPy.util.multioutput.ICM` model (in the case that all outputs have the same input data).

    Behind the scenes, this model is using an extended input space with an additional dimension that points at the
    output each data point belongs to. To make use of the prediction function of GPy, this model needs the input array
    to have the extended format, i.e. adding a column indicating which input should be used for which output.

    This function works also for input dimensions > 1.

    :param x: the x data you want to predict on
    :param num_outputs: The number of outputs in your model
    """

    xt2d = np.array([x[:, i] for i in range(x.shape[1])]).T
    xt = [xt2d] * num_outputs
    identity_matrix = np.hstack([np.repeat(j, _x.shape[0]) for _x, j in zip(xt, range(num_outputs))])
    xt = np.vstack(xt)
    xt = np.hstack([xt, identity_matrix[:, None]])

    return xt
```
@SiyuanHuang95
To make predictions your inputs must be reshaped the same way as the model does shape it internally during training (i.e. adding an additional dimension indicating which input belongs to which output). 

In the case that all outputs have common input values, this function might help.
