### ISSUE TITLE
Using seaborn with GPy

### ISSUE THREAD

**Issue by masenov** [SheffieldML/GPy#626]
Is it possible to use seaborn on top of matplotlib with GPy? I tried adding 

`import seaborn`
`seaborn.set()`

on top of the imports and in various places around the code of the library, but it does not seem to be working..

Thank you for the help in advance!

**Comment by mzwiessele** [comment]
We have our own setup for plotting parameters, see:
https://github.com/SheffieldML/GPy/blob/devel/GPy/plotting/matplot_dep/plot_definitions.py

**Comment by mzwiessele** [comment]
https://github.com/SheffieldML/GPy/blob/devel/GPy/plotting/matplot_dep/defaults.py
