### ISSUE TITLE
Optimizing parameters of a kernel within another kernel

### ISSUE THREAD

**Issue by yenicelik** [SheffieldML/GPy#627]
I have the following class, which is a kernel itself, but which also contains a kernel in it (called `inner_kernel`) as follows:

    TripathyMaternKernel(Kern):
        def __init__(self):
            self.inner_kernel = Matern32(
                input_dim=self.active_dim,
                variance=self.sample_variance() if variance is None else variance,
                lengthscale=self.sample_lengthscale() if lengthscale is None else lengthscale,
                ARD=True)

For TripathyMaternKernel, I have the following function to update the parameters with (this is specifically for the kernel variance):

    def set_s(self, s, safe=False):
        assert isinstance(s, float) or isinstance(s, Param), type(s)
        self.inner_kernel.variance = s
        self.s = Param('outerKernel.variance', self.inner_kernel.variance)
        self.link_parameters(self.s, self.inner_kernel)
        self.inner_kernel.parameters_changed()

Now I am trying to update the kernel parameters for `inner_kernel`, but calling `GPRegression.optimize`, where the `GPRegression` object is instantiated using the outer kernel (the `TripathyMaternKernel`. But when I call 

        gp_reg = GPRegression(self.X, self.Y.reshape(-1, 1), self.kernel, noise_var=sn)
        gp_reg.optimize("lbfgs")

then the parameters stay the same. Do I have to link them in a special manner?
I would like to optimize over both the gaussian parameter (Gaussian.NoiseVar) AND the parameters of the inner kernel (inner_kernel.lengthscale and inner_kernel.variance).

Am I missing anything where I have to link the parameters with the outer kernel etc, or should this be working?

**Comment by mzwiessele** [comment]
Try just linking the other kernel to your kernel. It’s variance gets updated automatically.

**Comment by yenicelik** [comment]
Thanks a lot, that solved it! :)
