### ISSUE TITLE
No module named msvccompiler in numpy.distutils; trying from distutils

### ISSUE THREAD

**Issue by Arttii** [SheffieldML/GPy#63]
Running on Python 2.7 64 bit on Windows with msvccompilers installed.

**Comment by zaikazoo** [comment]
I had the same configuration  as @kzangi . And the same problem. So is there any update on how it can be solved?

**Comment by mikecroucher** [comment]
@zaikazoo I'd like to try to reproduce your error on my machine. Are you installing GPy using pip?

**Comment by zaikazoo** [comment]
I have windows7, I installed GPy with pip install GPy from conda

**Comment by zaikazoo** [comment]
@mikecroucher I red my yesterday's comment and only now understand that it is confusing: I have windows 7, I install anaconda, and to get GPy i ran pip install GPy from command promt

**Comment by jameshensman** [comment]
This should be fixed by @mikecroucher 's work for 0.8

**Comment by mikecroucher** [comment]
Confirmed that there are no problems with devel GPy on Windows. This will soon be released as version 0.8 so I am closing this issue.
