### ISSUE TITLE
How to specify a GP-LVM with p(x)~GP

### ISSUE THREAD

**Issue by DragonCircle** [SheffieldML/GPy#634]
the original setting of latent space p(X) is i.i.d Gaussian distribution.
However, I want to place a Gaussian Processes prior on the latent space p(X)~GP(0,k_{t,t'})
Is GPy able to do this?
If can, how?
Please!

**Comment by zhenwendai** [comment]
Unfortunately, GPy does not support this functionality at the moment. The GPLVM in GPy is implemented with the closed form integral of kernel function with respect to diagonal Gaussian distribution. Maybe the matlab version by @adamian has this functionality.

**Comment by adamian** [comment]
@zhenwendai is right, one can find this functionality in this MATLAB package: https://github.com/SheffieldML/vargplvm 

Implementing this functionality in GPy would be better than using the MATLAB package, but it's not in my short-term plans. Nevertheless, all derivations can be found here: http://etheses.whiterose.ac.uk/9968/1/Damianou_Thesis.pdf for anyone interested (or one could do a simpler approximation without reparameterization and simplify the derivations/code).
