### ISSUE TITLE
Different priors for ARD lengthscales

### ISSUE THREAD

**Issue by cwlgadd** [SheffieldML/GPy#636]
A quick issue which can probably be resolved quickly.

I wasn't able to find any tests or demos which placed different priors on each lengthscale for an ARD kernel. I found this issue which is related https://github.com/SheffieldML/GPy/issues/529? However, the indexing seems to have changed:

`import GPy
import numpy as np
X = np.random.randn(10,2)
Y = np.reshape(np.cos(X[:,0]), (-1,1))
gp = GPy.models.GPRegression(X, Y, kernel=GPy.kern.RBF(input_dim=2, ARD=True))
gp.rbf.lengthscale[:,[0]] ` or
`gp.kern.lengthscale[:,[0]]
`

gives `IndexError: too many indices for array`.

Is this the correct way to do this now?

`gp.kern.lengthscale[[0]].set_prior()`

**Comment by darthdeus** [comment]
@cwlgadd Have you figured out if this works? Indexing as `[[0]]` or `[[0:1]]` definitely returns the right type, but I'm not sure how to check if the prior is actually being used in the right way.

**Comment by cwlgadd** [comment]
@darthdeus This issue is a year old, so I am not sure if what I did is relevant to the current release of GPy, but what I suggested seemed to work for me back then. 

Without looking at the actual code, a quick and dirty check is to try this with duplicates of the same model, but with a different lengthscale prior, and see if the posterior density changes as expected?

**Comment by darthdeus** [comment]
@cwlgadd Thanks for the response. What I did was try setting different priors on each lengthscale and then `.optimize()` and see that the parameters end up with different scale, which did end up happening.

But I'm a bit confused what you mean by checking the posterior support? I thought the prior can only be used as part of a MAP estimate during `optimize`?

**Comment by cwlgadd** [comment]
@darthdeus Sorry, not support. I fixed my last comment.

Optimization is non-convex in these models, which means that you will converge to a local optima. That will make it harder to see if the difference is because of the prior, or because of the optima. Try using https://github.com/SheffieldML/GPy/blob/devel/GPy/inference/mcmc/hmc.py. If the samples posteriors are different, you can be pretty confident that the priors are too. Of course, this is a heuristic check.
