### ISSUE TITLE
GPLVM: how to predict x_star given new y_star?

### ISSUE THREAD

**Issue by LuckyTiger** [SheffieldML/GPy#638]

**Comment by LuckyTiger** [comment]
I find [https://github.com/SheffieldML/GPy/issues/395](url) very helpful.
using ` m_gplvm.infer_newX(Y_new)` is ok.
But how does it work?

**Comment by LuckyTiger** [comment]
How to get predicted latent variance?

**Comment by mzwiessele** [comment]
I think it is all well described:

https://github.com/SheffieldML/GPy/blob/devel/GPy/inference/latent_function_inference/inferenceX.py

**Comment by LuckyTiger** [comment]
But this don't have X's variance

**Comment by mzwiessele** [comment]
If the model you begin with is a Bayesian GPLVM the output of inferX will be a variational posterior, which has the means and variances attached.

**Comment by LuckyTiger** [comment]
But how did Lawrence's first GP-LVM paper [https://papers.nips.cc/paper/2540-gaussian-process-latent-variable-models-for-visualisation-of-high-dimensional-data.pdf](url) have uncertainty plotted?

**Comment by mzwiessele** [comment]
Ah, try looking into the plotting function plot_latent for details on that measure.
