### ISSUE TITLE
Getting numpy.linalg.linalg.LinAlgError: not positive definite, even with jitter on optimize_restart for simple example

### ISSUE THREAD

**Issue by pietromercati** [SheffieldML/GPy#642]
Hello,
I'm trying to understand why the following example with GPRegression triggers an error in jitchol
I know that I can use the "robust" option to ignore this, but I would still like to understand why this is happening.
Thanks !!

> File "/home/pmercati/anaconda3/lib/python3.6/site-packages/GPy/util/linalg.py", line 78, in jitchol
>     raise linalg.LinAlgError("not positive definite, even with jitter.")
> numpy.linalg.linalg.LinAlgError: not positive definite, even with jitter.
> 

Code:

```
import sys
import numpy as np
from random import seed

import GPy

my_seed = 1
np.random.seed(my_seed)
seed(my_seed)


def main():

    training_data = np.array([[0.2, 0.0 ],
                              [0.0, 1.0 ],
                              [1.0, 0.0 ],
                              [0.0, 0.2 ],
                              [0.1, 0.1 ]])

    training_targets_i = np.array([[-0.731925],
                                   [ 0.99655765],
                                   [ 1.40693001],
                                   [ 1.0       ],
                                   [ 0.0       ]])

    kernel = GPy.kern.RBF(input_dim=2, ARD=True)
    model = GPy.models.GPRegression(training_data, training_targets_i,kernel)
    model.optimize_restarts(num_restarts = 10)


if __name__=='__main__':
    main()

```

**Comment by mzwiessele** [comment]
Could you try using the output normalizer? It can be set at creation of the GPRegression model.
