### ISSUE TITLE
What is model.predict(X) returning?

### ISSUE THREAD

**Issue by kentcov** [SheffieldML/GPy#650]
Forgive me if this is obvious, in the documentation, I cannot find any explanation.

I'm performing a Gaussian Process Regression on a substantial dataset, predicting a single outcome variable. However the m.predict() function returns 2 values. 

Examples/Tutorials seem to suggest that m.predict()[0] is the prediction value I'm looking for. Is this the mean value (and therefore the MLE) and the second value is the Credible region equidistant around that estimate?

An example of my code :

```
k = GPy.kern.RBF(input_dim=21)
m = GPy.models.GPRegression(TrainData,ObsData,k)
m.optimize(messages=True)
print(m.predict(X))
```
Returns : 

(array([[4.20722099e-07]]), array([[6.03336666e-09]])))

**Comment by BracketJohn** [comment]
This is the predicted mean and variance at points `X`.

**Comment by enushi** [comment]
Hi, I think in the second argument returned by `model.predict(X)` is not just the **posterior variance** at points `X` but rather **posterior variance + Gaussian noise variance**. If you need just the posterior variance you have to call `model._raw_predict(X)` instead.
