### ISSUE TITLE
Extract GP posterior covariance function as a kernel object? 

### ISSUE THREAD

**Issue by Riskneutral** [SheffieldML/GPy#658]
Dear GPy users,

Hi!
I wonder is it possible to extract the GP posterior covariance: 
![image](https://user-images.githubusercontent.com/11962979/43855576-f6a711ce-9b3d-11e8-826f-3396913f7c08.png)
from a fitted `GPy` model with data $X$ and wrap it into a kernel? It can be viewed as a kernel with additional parameters $\mathbf{X}$ but I would like to fix them. 
If so, is there shortcut way to do that? I would appreciate any practical suggestions.

Many thanks in advance!

**Comment by mzwiessele** [comment]
You should have a look at the posterior object of a GP object. It has all object to do predictions, including the posterior covariance. You can use a fixed kernel to use the posterior covariance in a new GP object.
