### ISSUE TITLE
AttributeError: module 'GPy' has no attribute 'kern'

### ISSUE THREAD

**Issue by AliBaheri** [SheffieldML/GPy#659]
Thanks for great repo.

I am using GPy for a while, but I have recently faced with the following error after installing python 3.5 on mac:

`AttributeError: module 'GPy' has no attribute 'kern'`

Would you please guide me how can I resolve the issue?

**Comment by AliBaheri** [comment]
solved...by upgrading to the new version.

**Comment by ballabeta** [comment]
Hi, was this solved by upgrading to the new version of python or the GPy package? I am having a similar error: 

AttributeError: module 'GPy.kern' has no attribute 'rbf'

Many thanks,
Alice

**Comment by ToMdAvI** [comment]
Hello,

I have also just got this error. Using Python 3.12.4 in Spyder/Anaconda. GPy has been downloaded within last few hours.

Thanks
![Screenshot 2024-07-25 164552](https://github.com/user-attachments/assets/addb8d65-effe-451d-b8c6-09c68ee3c7ec)
