### ISSUE TITLE
Evaluating models

### ISSUE THREAD

**Issue by xorb0ss** [SheffieldML/GPy#661]
I couldn't find any info in the current documentation to aid me in evaluating my GPR model, nor in the notebooks. I have trained a GPR model and would now like to evaluate it, for example using the EMRMSE or calculating the accuracy for a given prediction using `m.predict(x_)`.

Apologies if this is indeed documented somewhere.

**Comment by mzwiessele** [comment]
When you predict, you get back the mean and variance for the prediction, which you can then compare to your left out test set y
