### ISSUE TITLE
Lot of build errors

### ISSUE THREAD

**Issue by KOLANICH** [SheffieldML/GPy#664]
https://gitlab.com/KOLANICH1/UniOpt.py/-/jobs/92012869

**Comment by mzwiessele** [comment]
Which python are you running on?

**Comment by KOLANICH** [comment]
>Using docker image sha256:825141134528aa58f1c0c6c7ad02e080968847338506c23c14a063ac6645bca5 for python:latest ...


it is the image for 3.7 as 3.7 is now the latest. I guess it may even be nightly.

**Comment by oysstu** [comment]
See https://github.com/SheffieldML/GPy/issues/649#issuecomment-410241513

**Comment by mzwiessele** [comment]
Cython is not compatable with py37. I’ve tried building it and it didn’t work for me either. Do you havea a solution to this? Thank you very much :)
