### ISSUE TITLE
Unable to find documentation

### ISSUE THREAD

**Issue by pjpessi** [SheffieldML/GPy#672]
Hi, I am sorry to bother you but I am trying to modify an old code and I am not being able to find the GPy.kern.RBF() and GPy.kern.BIAS() documentation. I am trying to go into the pages I bookmarked and it says that the pages do not exist. Where can I find the documentation?

**Comment by wilocw** [comment]
Documentation for GPy can be found online at https://gpy.readthedocs.io, e.g. for the `GPy.kern.RBF()` documentation, you can [look here](https://gpy.readthedocs.io/en/deploy/GPy.kern.src.html#GPy.kern.src.rbf.RBF).
