### ISSUE TITLE
Save and load regression model

### ISSUE THREAD

**Issue by dpkPrasadPaudel** [SheffieldML/GPy#762]
According to tutorials the GP regression model can be saved and loaded according to

saving
```
rb = GPy.kern.RBF(nd,1,10)
m = GPy.models.GPRegression(xtrain,ytrain,rb)
m.optimize()
np.save('gmodel.npy',m.param_array)
```
Loading
```
m=GPy.models.GPRegression(xtrain,ytrain,initialize=False)
m[:]=np.load('gmodel.npy')
m.initialize_parameter()
mu,var=m.predict(xtest)
```
However this is not working !

**Comment by Amir-Arsalan** [comment]
@DpakPaudel Did this work eventually? Could you successfully save/load your model this way?

**Comment by dpkPrasadPaudel** [comment]
Yeah, it was working with some modification, can't remember exactly how. you could google for some other similar posts, and try different options and should work.
