### ISSUE TITLE
Asymmetric kernel for GP regression

### ISSUE THREAD

**Issue by Chris-Pedersen** [SheffieldML/GPy#778]
I am training the GP regression class on an 8 dimensional data set. Our training set varies much faster along certain dimensions than others so optimising one kernel for all dimensions simultaneously seems suboptimal. Has anyone experimented with asymmetric kernels on this kind of problem?

Thanks!

**Comment by mzwiessele** [comment]
Yes if you specify ARD=True in the kernel creation each dimension of the input will be assigned its own lengthscale :)

**Comment by Chris-Pedersen** [comment]
Great, I'll try this out, thank you very much!
