### ISSUE TITLE
Tutorial: creating new kernels

### ISSUE THREAD

**Issue by telish** [SheffieldML/GPy#786]
Hello, 
the code in the tutorial "Creating new kernels" (https://gpy.readthedocs.io/en/deploy/tuto_creating_new_kernels.html) does not work. To get it to run one needs to add "from ...core.parameterization import Param" and replace "add_parameters" with "link_parameters". Then it runs just fine.

**Comment by ekalosak** [comment]
I think this PR fixes the issue: https://github.com/SheffieldML/GPy/pull/805
If you agree @telish please close :)

**Comment by bobturneruk** [comment]
@lawrennd - I think this should be closed, although this appears only in the `devel` version of readthedocs (which is not the default).
