### ISSUE TITLE
a question about notation

### ISSUE THREAD

**Issue by DongweiYe** [SheffieldML/GPy#787]
Hi,

I am a new user of Gpy. I have a question about the notation printed out during training. I saw (runtime, i, f, |g|). 

'i': I guess is the number of iteration. 
'f': I guess its log likelihood? (Is that means bigger f, better fitting?)
|g|: I don't know what is g

Could anyone help me out?
Thanks a lot!

**Comment by zhenwendai** [comment]
'i': the number of iteration.
'f': the value of the objective function
'|g|': the norm of the gradient.
