### ISSUE TITLE
Am I doing something wrong when saving the GP Regression model?

### ISSUE THREAD

**Issue by Amir-Arsalan** [SheffieldML/GPy#807]
I am trying to save the GP regression model parameters on disk but when I call the `to_dict()` and `_to_dict()` methods to get the dictionary containing the model parameters I get the following error for both of them:

> to_dict() missing 1 required positional argument: 'self'

Based on the documentation [here](https://gpy.readthedocs.io/en/deploy/GPy.models.html#GPy.models.gp_regression.GPRegression.to_dict) it seems that it must be pretty easy to get the dictionary but I am currently getting this error. Am I doing something wrong? 

Assuming that the model is saved on disk, for loading the model, should I simply call `from_dict(preStoredDict)` method?

I also tried saving the model with `save_model()` and `_save_model()` methods but get a similar errors as follow:

> save_model() missing 1 required positional argument: 'self'

> _save_model() missing 1 required positional argument: 'self'

Finally, I tried the old-school method for saving the model as suggested [here](https://github.com/SheffieldML/GPy/issues/762) and [here](https://github.com/SheffieldML/GPy/issues/535) but I get the following errors when trying to save `GP.param_array`:

>   File "<__array_function__ internals>", line 6, in save
>   File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 542, in save
>     pickle_kwargs=pickle_kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/lib/format.py", line 659, in write_array
>     pickle.dump(array, fp, protocol=3, **pickle_kwargs)
>  TypeError: can't pickle property objects

**Comment by nbeuchat** [comment]
Could you share your code on how you use `to_dict()` and `save_model()`. From the error, it seems you're not calling it on an instance of your GP Regression. You should be doing something like:

```
gp = GPy.models.GPRegression(...)
...
gp.save_model(filename)
dict_object = gp.to_dict()
```

As for the pickling error, I suppose that you'd need to install on older version of GPy or pickle. I haven't followed much the development of these libraries but I suppose there are breaking changes that make the code you found on older issues incompatible. 

Hope that helps!

**Comment by Amir-Arsalan** [comment]
@nbeuchat Thanks. I was wrapping the GPRegression object in some other classes and that was causing the issue. Now things work fine but unfortunately the saved model parameters are not the same as the parameters before saving the model. It could be because I'm using `float64` and the `save_model` method assumes `float32` ...
