### ISSUE TITLE
is:issue function log_predictive_density_sampling ImportError

### ISSUE THREAD

**Issue by kae-mihara** [SheffieldML/GPy#816]
It import function `logsumexp` from `scipy.misc`, which has moved into `scipy.special` in version 1.3.0.

Please fix this in some new version.

**Comment by lawrennd** [comment]
It would be great if you could do this fix and submit a pull requeest!


Neil
--
Professor Neil Lawrence
http://inverseprobability.com
________________________________

**Comment by kae-mihara** [comment]
glad to do this.
