### ISSUE TITLE
Bug in GPCoregularizedRegression constructor

### ISSUE THREAD

**Issue by lagph** [SheffieldML/GPy#823]
The constructor takes `W_rank` as an argument, but it's never used anywhere. Presumably it's supposed to set `W_rank` for the default kernel if a custom one is not provided, but instead we have
```python
if kernel is None:
    kernel = kern.RBF(X.shape[1]-1)

    kernel = util.multioutput.ICM(input_dim=X.shape[1]-1, num_outputs=Ny, kernel=kernel, W_rank=1,name=kernel_name)

```
Either this should be changed to
```python
    kernel = util.multioutput.ICM(input_dim=X.shape[1]-1, num_outputs=Ny, kernel=kernel, W_rank=W_rank,name=kernel_name)
```
or `W_rank` should be removed from the constructor's argument list. Thanks!

**Comment by zhenwendai** [comment]
It seems to be a bug. Thanks for spotting it. Would you mind creating a pull request to fix it?

**Comment by zhenwendai** [comment]
The pull request has been merged. Thanks!
