### ISSUE TITLE
GPy no longer works with Python 2.7

### ISSUE THREAD

**Issue by jbect** [SheffieldML/GPy#833]
GPy no longer works with Python 2.7, as can be seen on Travis:
https://travis-ci.org/github/SheffieldML/GPy/builds/672561189.

The reason is that the minimal version of scipy has be raised from 0.16 to 1.3.0 in commit 31ef0f2844a778b89b5fea1cd0705b1eb0ca5838, and scipy 1.3.0 requires Python 3.

If Python 2.7 support is really to be dropped, changes must be made in various places (including `README.md` and `.travis.yml`).

**Comment by jbect** [comment]
Remark: since Python 2.7 has reached its end of life in January this year (see https://devguide.python.org/devcycle/#end-of-life-branches), it seems indeed reasonable to drop Python 2.7 support.

**Comment by willfurnass** [comment]
+1.  All CI jobs against master will break until this is fixed.

**Comment by bobturneruk** [comment]
+1 As far as I can see, this blocks all current PRs.
