### ISSUE TITLE
Readthedocs not up to date

### ISSUE THREAD

**Issue by bobturneruk** [SheffieldML/GPy#847]
Despite merge of https://github.com/SheffieldML/GPy/pull/836 the readthedocs site (https://gpy.readthedocs.io/en/deploy/) is not showing the new documentation. I will investigate further.

**Comment by bobturneruk** [comment]
This is because readthedocs points to the `deploy` branch, not the `devel` branch. I suggest that readthedocs should point to the default branch in GitHub, which is `devel` and that an authorised person makes this change.

**Comment by jbect** [comment]
Hi @bobturneruk.  I think that the doc for `devel` is available here on RTD:

https://gpy.readthedocs.io/en/devel/

(but as you said, this is not the one that you reach by default).

**Comment by lawrennd** [comment]
We can certainly revisit the approach to branches. 

I think original idea was to have devel as the branch with the latest updates, and deploy to be the branch which people would use in practice. 

Typically, we would put out a new deploy before the GPSS (which is coming up in September).

Thoughts @zhenwendai @apaleyes?

**Comment by jbect** [comment]
@lawrennd IMHO it's ok if the default doc shown on RTD is the one from the latest published release, which seems to be the case currently (?).  People interested in the latest developments can easily switch to other branches anyway.

**Comment by bobturneruk** [comment]
> Hi @bobturneruk. I think that the doc for `devel` is available here on RTD:
> 
> https://gpy.readthedocs.io/en/devel/
> 
> (but as you said, this is not the one that you reach by default).

Yes - it's definitely being built and accessible. I'm, of course, happy with whatever the community wants to do. Maybe I should put an extra link the the readme?

**Comment by zhenwendai** [comment]
> > Hi @bobturneruk. I think that the doc for `devel` is available here on RTD:
> > https://gpy.readthedocs.io/en/devel/
> > (but as you said, this is not the one that you reach by default).
> 
> Yes - it's definitely being built and accessible. I'm, of course, happy with whatever the community wants to do. Maybe I should put an extra link the the readme?

This is a good idea. I will add the link on the readme.
