### ISSUE TITLE
model.plot() not working

### ISSUE THREAD

**Issue by CGavrila** [SheffieldML/GPy#85]
Not sure if this is an actual issue or if I am doing something wrong, but I can't seem to get model.plot() working.

I have the following code, where the times and years variables contain some olympic data.

```
kernel = GPy.kern.rbf(1, variance=1, lengthscale=1)
model = GPy.models.GPRegression(times, years, kernel)

model.plot()
```

A separate window which should contain the plot does open, but closes instantly, without displaying anything.

Any ideas as to why this is happening?

**Comment by Christian-B** [comment]
I had the same issue. 
The fix:
matplotlib.pylab.show(block=True) 
Worked fine and the above explanation is a valid one.

Too bad I had to google to find this issue as the documentation does not work outside of ipython.

**Comment by Christian-B** [comment]
In case anyone find this later.
If doing a figure with multiple plots as in the example:

figure, axes = plt.subplots(3,1)
for ax, y in zip(axes, [-1, 0, 1.5]):
    m.plot(fixed_inputs=[(1,y)], ax=ax)
    ax.set_ylabel('y=%d'%y)
plt.suptitle('horizontal slices through the function')

and 
matplotlib.pylab.show(block=True) 
after the last final setup call for that plot.
In the above example after the suptitle line
