### ISSUE TITLE
reproducible sparse GP results with inducing points

### ISSUE THREAD

**Issue by jacowp357** [SheffieldML/GPy#851]
Hi,

Each time I retrain a spare GP (with fixed number of inducing points) it returns different results. Is it perhaps possible to fix it with a random seed? Or alternative?

Thanks!

**Comment by Amir-Arsalan** [comment]
@jacowp357 How did you resolve this issue? I'm afraid what you posted about is relevant to the issue I posted about earlier in #803 .
