### ISSUE TITLE
LinAlg error

### ISSUE THREAD

**Issue by ndalchau** [SheffieldML/GPy#857]
I've been struggling with a problem with the initialization of kernels in a loop. There is some kind of bizarre interaction with matplotlib, but I can't figure out what's going on. Here is a short example:
```python 
import matplotlib.pyplot as pp
import GPy
import numpy as np

num_folds = 3
n_inputs = 3
n_obs = 50
for fold in range(num_folds):
    x = np.random.rand(n_obs,n_inputs)
    y = np.random.rand(n_obs,1)
    kern = GPy.kern.RBF(n_inputs)
    model = GPy.models.GPRegression(x, y, kern)
    pp.plot([0, 1], [0, 1], 'k--')
```
When I do this, I always get:
`numpy.linalg.LinAlgError: Eigenvalues did not converge`

However, when I comment out pp.plot, the program runs to completion with no problem. I've been using various workarounds to avoid this, but it keeps rising up again. 

Any ideas?

**Comment by zhenwendai** [comment]
I could not recreate your issue. What is the GPy and matplotlib version that you are using? Can you provide the full error log?

I have
GPy == 1.9.9
matplotlib == 3.1.1
numpy == 1.17.2

**Comment by ndalchau** [comment]
Thanks for checking for me. I was convinced things were working okay at some point in the past, but have not for a while now.

I have:
GPy == 1.9.9
matplotlib == 3.3.0
numpy == 1.18.1

```
Traceback (most recent call last):
  File "kernel_bug.py", line 11, in <module>
    kern = GPy.kern.RBF(n_inputs)
  File "C:\depot\TransfectionOXB\venv\lib\site-packages\paramz\parameterized.py", line 53, in __call__
    self = super(ParametersChangedMeta, self).__call__(*args, **kw)
  File "C:\depot\TransfectionOXB\venv\lib\site-packages\GPy\kern\src\rbf.py", line 24, in __init__
    super(RBF, self).__init__(input_dim, variance, lengthscale, ARD, active_dims, name, useGPU=useGPU)
  File "C:\depot\TransfectionOXB\venv\lib\site-packages\GPy\kern\src\stationary.py", line 62, in __init__
    super(Stationary, self).__init__(input_dim, active_dims, name,useGPU=useGPU)
  File "C:\depot\TransfectionOXB\venv\lib\site-packages\GPy\kern\src\kern.py", line 61, in __init__
    self.psicomp = PSICOMP_GH()
  File "C:\depot\TransfectionOXB\venv\lib\site-packages\GPy\kern\src\psi_comp\gaussherm.py", line 22, in __init__
    self.locs, self.weights = np.polynomial.hermite.hermgauss(degree)
  File "C:\depot\TransfectionOXB\venv\lib\site-packages\numpy\polynomial\hermite.py", line 1572, in hermgauss
    x = la.eigvalsh(m)
  File "<__array_function__ internals>", line 6, in eigvalsh
  File "C:\depot\TransfectionOXB\venv\lib\site-packages\numpy\linalg\linalg.py", line 1160, in eigvalsh
    w = gufunc(a, signature=signature, extobj=extobj)
  File "C:\depot\TransfectionOXB\venv\lib\site-packages\numpy\linalg\linalg.py", line 103, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.LinAlgError: Eigenvalues did not converge
```

I tried installing the same versions of numpy and matplotlib as you, but that didn't solve it. 

I am running on Windows, which perhaps changes the behaviour being seen. I'll spin up a linux VM and see what happens there.

**Comment by ndalchau** [comment]
So, it turns out that the code example runs fine on Linux. This is only an issue on Windows.

**Comment by zhenwendai** [comment]
> self.locs, self.weights = np.polynomial.hermite.hermgauss(degree)

From your error message, the line that it fails on is the one calling numpy. The variable `degree` is a constant. It seems that the failing does not relate to GPy. I would suggest to check the numpy installation.

**Comment by ndalchau** [comment]
After a bit of debugging, I've located the problem as being to do with `np.polynomial.hermite.hermgauss`, when a high degree polynomial is used.
``` python
import matplotlib.pyplot as pp
import numpy as np

degree = 11
locs, weights = np.polynomial.hermite.hermgauss(degree)
pp.plot([0, 1], [0, 1], 'k--')
locs, weights = np.polynomial.hermite.hermgauss(degree)
```

The problem goes away when degree < 10 (and as before, when removing/commenting out the pp.plot call). I'll close this issue and post on the numpy repo issues. But out of curiosity, why are degree 11 polynomials required when initialising a kernel?
