### ISSUE TITLE
BLAS is never used in linalg.py (even if available)

### ISSUE THREAD

**Issue by nfusi** [SheffieldML/GPy#86]
See https://github.com/SheffieldML/GPy/blob/devel/GPy/util/linalg.py#L24
The statements used to verify whether BLAS is available are in a try/except block that catches ALL exceptions. 

The problem is that 

hasattr('dsyrk_',_blaslib)

has the arguments in the wrong order, it should be:

hasattr(_blaslib, 'dsyrk_')

the exception that gets thrown is then ignored and blas support is disabled.

scipy 0.13 has dsyrk (wrapped) but no dsyr. The cleanest solution would be to rely on the scipy wrapper for dsyrk and fix the bug described above for dsyr.

Let me know if it's a good solution and I will close.

**Comment by jameshensman** [comment]
After discussion with Max, we think that the solution is to depend on the scipy blas libraries. A lot of this functionality was in place before scipy tidied up their linalg package and made more of the blas routines accessible. 

TODO: remove some of this config code which detects anaconda etc, and depend on scipy.linalg.blas instead.

**Comment by mzwiessele** [comment]
This is done now @mikecroucher, right?

**Comment by mikecroucher** [comment]
Yes
