### ISSUE TITLE
Error(s) when installing GPy

### ISSUE THREAD

**Issue by mttmtt31** [SheffieldML/GPy#874]
I downloaded Anaconda today for the first time on my laptop to work on a jupyter notebook I was given. In its first chunk of code it imports gpy, assuming it is already installed on my machine - which is not. 
I open the Anaconda Prompt, I run `conda update scipy` and everything works fine. Then i run `pip install gpy` and I get two errors. 

First: ERROR: Failed building wheel for gpy

Second: ERROR: Command errored out with exit status 1: [...] Check the logs for full command output.

I copied and pasted every single error that on the net I get but I can't find a solution. Can you please help me? What shall I do?

**Comment by jvesely** [comment]
Are you running python3.9?

**Comment by wilocw** [comment]
see #881
