### ISSUE TITLE
Strange behaviour when generating two models

### ISSUE THREAD

**Issue by dmrd80** [SheffieldML/GPy#876]
Hello all, I am really fairly new to GPs and GPy, but while setting up my first tries according to the Jupyter Notebook examples, I stumbled across a behaviour that I do not understand: While trying to compare model outputs with and without setting of a prior mean, I found that at least the plot output for the first model depends on actions on the second model.

A minimal example (generated in JupyterLab 2.1.5 on Windows):

```
%matplotlib inline

import numpy as np
import GPy

n_points = 10
x = np.linspace(-1, 1, n_points)
y = np.sin(x)
# Add Gaussian white noise
y += np.random.normal(size=n_points, loc=0, scale=.1)

kernel = GPy.kern.RBF(input_dim=1)
# GPy seemingly needs at least one column...
x, y = x[:, None], y[:, None]

model_1 = GPy.models.GPRegression(x, y, kernel=kernel)
model_1.optimize()
model_1.plot(title='model 1')

# Use a prior mean for another model
mf = GPy.core.Mapping(1,1)
mf.f = np.sin
mf.update_gradients = lambda a, b: None
model_2 = GPy.models.GPRegression(x, y, kernel=kernel, mean_function=mf)
model_2.optimize()

model_1.plot(title='still model 1, why does it look different?')
model_2.plot(title='model 2')
```

This generates the following output, and I struggle to understand why the first two plots are different:

![image](https://user-images.githubusercontent.com/75118548/100445341-3e70fe00-30ad-11eb-9c01-4a731aca8590.png)
![image](https://user-images.githubusercontent.com/75118548/100445382-4cbf1a00-30ad-11eb-9b45-83ee7c0ef2d8.png)
![image](https://user-images.githubusercontent.com/75118548/100445406-5779af00-30ad-11eb-89af-634ca3b4e943.png)

Only if I comment out `model_2.optimize`, I get identical results for the first 2 plots.
Any pointers are welcome, and sorry in advance for the noob question.

**Comment by lawrennd** [comment]
Hi Daniel! I’ve not rerun it .. but I think this is because the kernel in model_2 and model_1 are the same object.

When you optimise model_2 the mean function explains the variance of the data, so variance of kernel (I suspect) goes to zero and model_1 is inly predicting with a noise variance.

Does that make sense? I can look deeper if that’s not it.

**Comment by ghost** [comment]
Dear Neil,
thank you very much for the explanation - this really seems to have been the problem, it gives me the expected results when I assign two seperate Kernel objects. Your explanation on the noise variance also is on spot, as a look on the number of hyperparameters revealed upon disp()..., I should have dug deeper into the API first, mea culpa.

Thank you for the quick help, I really appreciate it!

**Comment by lawrennd** [comment]
No need for a 'mea culpa' Daniel, these things only seem obvious in retrospect, and it's great to have an issue up that covers this particular 'gotcha'. Thanks for raising it.
