### ISSUE TITLE
Need beginner advice: How to prevent overfitting

### ISSUE THREAD

**Issue by will-colea** [SheffieldML/GPy#901]
My datasets are small (somewhere between 8-15 data points) and I am worried about over fitting. I was suggested trying the heteroscedastic GP. However, the fits are really poor and the hills and valleys are not captured by the surrogate function. I have also been suggested regularization methods, but I am unsure how I can apply these in GPy. I am looking for some advice on this. Thank you!

**Comment by ekalosak** [comment]
Heteroskedastic GPs usually require more data than their homoskedastic counterparts, and 8-15 data points is pretty limited - there are just more free parameters in a heteroskedastic model. First, I'd suggest using a homoskedastic GP on your limited data.

As for regularization, it's another way to get the effect of applying a prior over the function space (Rasmussen & Williams 2006, chapter 6.2). Fortunately, this means that you get regularization with the GP prior - _this comes from your choice of kernel_ (and potentially your choice of prior over kernel hyperparameters, though the latter isn't totally necessary, you can usually happily learn the hyperparameters via the joint likelihood optimization "model fitting" procedure).

So,
1. Use a homoskedastic GP
2. Try a few different kernels, better yet, read Chapter 4 of Rasmussen & Williams and make a educated guess
3. Moreover, if you post the data you're using and the regression results you're seeing, it'll be _much_ easier to provide more pointed suggestions.

Rasmussen & Williams 2006 is free and the standard text on Gaussian processes: www.GaussianProcess.org/gpml

**Comment by will-colea** [comment]
Hello Eric -

Thank you for your advice. I did end up going with the homoskedastic GP intstead. Thank you for the details on why the heteroskedastic may not work for my data. Thank you so much for your help. Also, thank you so much for your work on the library - it is very awesome!

Best,
Alex

Alexandria Will-Cole

NDSEG Graduate Research Fellow
PhD Candidate, Northeastern University
Electrical Engineering Dept.
Advanced Microsystems and Materials Lab

email: ***@***.***
phone: 443.866.4663

________________________________

**Comment by lionfish0** [comment]
I might be too late to add: but the uncertainty on the hyperparameters is
going to be bigger with fewer points: the point estimate from maximum
likelihood might be poor unless you've got a strong prior... It might be
worth integrating over the hyperparameters (I'm not sure which are
implemented in gpy to be honest. Four years ago I tried helping get CCD
introduced but it sits as a derelict breach, sorry. Mcmc or vi, etc are
other options).
Mike
