### ISSUE TITLE
How can I get the mean_function after training? 

### ISSUE THREAD

**Issue by HongminWu** [SheffieldML/GPy#906]
After a GP training, how can I get the mean_function?

**Comment by ekalosak** [comment]
You don't get a mean function, per-se; you get a posterior process and you can pick the mean out of that.
```
X=np.array(your full space)
mu, _ = your_gp_model.predict(X)
```
Then `mu` is the mean of the posterior process at the locations specified in `X`.

**Comment by HongminWu** [comment]
Ok, thanks for your help, we can use it to meet my requirements now.

Best regards,
--
Hongmin Wu

**Comment by ekalosak** [comment]
Epic, I am happy to be able to help.
@HongminWu Please close the issue if you're all set!
