### ISSUE TITLE
Next Release of GPy

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#907]
@ekalosak would you be happy to take charge of pushing out the next release?

Also tagging @alansaul @mzwiessele @zhenwendai @apaleyes @maalvarezl for awareness.

**Comment by ekalosak** [comment]
I've tagged the release here: https://github.com/SheffieldML/GPy/releases/tag/v1.10.0
I'll open the PR to `deploy` in a moment.
If that PR passes CI, I'll merge it. That should kick off the automatic deployment configured in `.travis.yml`.

NB: I've started a Wiki page for the release process. It wasn't really documented anywhere so hopefully this lowers the activation energy required for future releases.

**Comment by lawrennd** [comment]
Thanks so much Eric!

**Comment by ekalosak** [comment]
Here's the PR: https://github.com/SheffieldML/GPy/pull/908

**Comment by ekalosak** [comment]
<img width="1412" alt="Screen Shot 2021-05-11 at 8 32 23 PM" src="https://user-images.githubusercontent.com/6068321/117914481-4bb72900-b298-11eb-8c20-3dd28c66f981.png">
