### ISSUE TITLE
`GPy/util/ln_diff_erfs.py:111:15`: F821 undefined name 'I'

### ISSUE THREAD

**Issue by ekalosak** [SheffieldML/GPy#912]
There's a reference to `I` in the [source here](https://github.com/SheffieldML/GPy/blob/devel/GPy/util/ln_diff_erfs.py#L103) but it isn't defined anywhere.

**Comment by lawrennd** [comment]
Ah ... I think it is defined on line 48 ... but in a previous if/else branch that checks if x1.size == 1

I'll look at a fix.

**Comment by lawrennd** [comment]
OK ... so it doesn't seem to be called by anything (it wasn't even exposed when GPy is imported).

There is another shorter implementation in GPy.util.functions under the name "differfln". 

That also doesn't seem to be used anywhere. 

Digging further, it looks like the only place that these functions are used is in core/symbolic.py, which was an attempt to build in some automatic integration/differentiation for non-Gaussian likelihoods.  

Note that none of these functions have tests and ... it looks like several are superseded by updated provision from scipy.

I've implemented a fix locally, but not a test for it yet. Maybe it's worth discussing removing the symbolic functionality ... it's cute but I'm not sure it's useful/used.

**Comment by ekalosak** [comment]
If there's a need for auto differentiation, there are other toolkits for that (tensorflow, e.g.)
Seems reasonable to remove it here and, maybe, make a notebook showing how that functionality can be achieved by bringing in TF's autodif sometime in the future.

**Comment by lawrennd** [comment]
Yes ... I think there's some settling needed of JAX, PyTorch and Tensorflow ... I think it might be interesting to try some stuff in JAX. Long term. Again, don't know whether that's a discussion, issue or whatever.

What's best? Close this issue and start a new one suggesting removal  of symbolic.py, util.functions.py and ln_diff_erfs.py?

**Comment by lawrennd** [comment]
(historical note ... when symbolic.py was created Theano was the only autodiff framework ...)

**Comment by ekalosak** [comment]
This makes sense. Ok, so I do think there's scope creep here and we'd be better off removing the symbolic stuff - it's done well elsewhere by projects focused on autodifferentiation.
