### ISSUE TITLE
error in prior.plot()

### ISSUE THREAD

**Issue by flydream0428** [SheffieldML/GPy#925]
When the prior.plot() is called, it gives the error below, 
```
gamma_prior = GPy.priors.Gamma.from_EV(1.5, 0.7)
gamma_prior.plot()
```
> AttributeError: 'Rectangle' object has no property 'normed'

This should be fixed by replacing "normed" with "density".

**Comment by ekalosak** [comment]
Thanks for the productive post @flydream0428 💪 Would you mind cutting a PR that fixes this?

**Comment by flydream0428** [comment]
@ekalosak Sure, I will have a go

**Comment by ekalosak** [comment]
Done, thank you.
