### ISSUE TITLE
How to get exact interpolation/prediction from GPy model?

### ISSUE THREAD

**Issue by flydream0428** [SheffieldML/GPy#931]
In a normal Kriging implementation, we will get very low/zero variance if the prediction location is very close/collocated to/with a training sample. However, it seems like that I always get a higher variance from GPy at such locations when compared to some Kriging implementation. Is this due to the Gaussian noise included in the model? Or there is some more fundamental theoretical reason here?

**Comment by ekalosak** [comment]
Which model are you using? I ask because, for some of the out-of-the-box GPy models there's a fixed noise variance e.g. for [`GPy.models.GPRegression`](https://github.com/SheffieldML/GPy/blob/devel/GPy/models/gp_regression.py#L29) we have
```
    def __init__(self, X, Y, kernel=None, Y_metadata=None, normalizer=None, noise_var=1., mean_function=None):
```
^ see the default `noise_var=1.` kwarg.

**Comment by flydream0428** [comment]
@ekalosak Hi Eric, I figured out that I didn't apply the cross variance component in the kernel when I set up the active dimensions.

**Comment by flydream0428** [comment]
@ekalosak I have figured this out. I
