### ISSUE TITLE
Setting Student t likelihood degrees of freedom

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#95]
If the degree of freedom is too low on the student-t likelihood things don't work. Maybe things aren't concave any more. Regardless, we need to detect when this happens and throw a warning that is interpretable, currently warnings are thrown the origin of which isn't that clear. Do we need to check the positive-definiteness of the Hessian?

**Comment by mzwiessele** [comment]
Maybe a standard prior on the degrees of freedom would solve this? We could use a Gamma Prior, which does not allow small values, but is uninformative for the rest?

**Comment by mzwiessele** [comment]
Ny news? Did you try the priors?

**Comment by mzwiessele** [comment]
@alansaul did you have a look?

**Comment by mzwiessele** [comment]
Hello?

**Comment by alansaul** [comment]
Hi sorry Max. I think this might have been from before the parametrized
framework existed and has nothing to do with prior's unless I'm mistaken?

The student-t now has a degrees of freedom parameter, which can be set at
creation with GPy.likelihood.StudentT(deg_free=5.6), and can be optimized
as I implemented the gradients for it some time ago.

Kernels can of course also have parameters in the standard way nowadays. Am
I missing something? I feel like I must be!

Alan

**Comment by mzwiessele** [comment]
When I read Neils comment I thought he meant, that during optimization the dof can get low and then stuff doesnt work anymore? Dont know though, Ill just close : )
