### ISSUE TITLE
pylab causes hanging import on Ubuntu 20.04

### ISSUE THREAD

**Issue by mschrader15** [SheffieldML/GPy#977]
GPy is a dependency of a library I am using (HEBO). Rather unusually, my program was hanging on the import of the HEBO library and ultimately GPy. After tracing the hanging import back through GPy, I found that it is caused by pylab here:

https://github.com/SheffieldML/GPy/blob/bb1bc5088671f9316bc92a46d356734e34c2d5c0/GPy/util/pca.py#L9

For reference, I am running:
```
Python 3.9.12 (main, Apr  2 2022, 14:29:03) 
[GCC 9.4.0] on linux

----
5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
It is likely related to https://stackoverflow.com/questions/17490444/import-matplotlib-pyplot-hangs

While I suspect that this is a very uncommon problem, wanted to document for future users.

**Comment by ekalosak** [comment]
<img width="1162" alt="Screen Shot 2022-04-17 at 12 40 00 PM" src="https://user-images.githubusercontent.com/6068321/163724021-618d50a9-4d8e-4d2e-996f-c66cdae22a7c.png">

Hi @mschrader15 - thank you for reporting the issue. If you find a moment, adding this under the Wiki would be a great addition. Then we can close this issue and reference it over in the Wiki.

**Comment by mschrader15** [comment]
Will do!
