### ISSUE TITLE
Kernel request: sinc

### ISSUE THREAD

**Issue by danstowell** [SheffieldML/GPy#98]
The sinc kernel would be handy for applying GP e.g. in bandlimited DSP applications.

**Comment by mzwiessele** [comment]
This has been a long time ago. 

If you still want this kernel to be in GPy, and you know how to implement it, it would be great 
if you could try to implement it.

See [the docs](http://gpy.readthedocs.org/en/devel/tuto_creating_new_kernels.html) for how to implement a kernel. All you need to implement is written in there. 

Were happy if you get a pull request in, so we can put this feature in.

**Comment by mzwiessele** [comment]
Any updates?

**Comment by lawrennd** [comment]
I keep meaning to do it as it's a useful one for demonstrating at the
summer school ... but haven't got around to it!

We are seeing Thomas on Thursday. Is it in the plan for him to implement
pandas-kernels. Would it be useful 'warm up' for him to do the sinc kernel?
We shouldn't ask him if it's not something that will progress his project
though.

**Comment by mzwiessele** [comment]
Did we get this done? If not, can you give me a reference?

**Comment by jorgeloaiza** [comment]
Hello mzwiessele.
¿Do you know how to set a new kernel in GPy?

Thanks

**Comment by ekalosak** [comment]
Stale.
