### ISSUE TITLE
Stop using `print()` for logging

### ISSUE THREAD

**Issue by Kruszylo** [SheffieldML/GPy#984]
I've noticed that `GPy` uses a non-uniform system of logging, some messages are logged with `logging` lib, some with `warning`, and there are many cases where the `print()` function is used ([sourcegraph scan](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/SheffieldML/GPy%24+print%28+rev:refs/tags/v1.10.0&patternType=literal)). It makes difficult to control output messages of the lib. Please, can you use only `logging` lib with a defined logger?

**Comment by ekalosak** [comment]
This is a good idea but would benefit from a contribution from the reporter. As this is stale, I'll close it, but that doesn't invalidate the concern by any means.
