### ISSUE TITLE
How to check lengthscales when ARD=True

### ISSUE THREAD

**Issue by ktakihara2000** [SheffieldML/GPy#994]
I do Bayesian optimisation in 2D.
When 'ARD' is set to 'True', printing kernel outputs '(2, )'.
I would like to check the respective lengthscale in 2D, is there a way to do this?
and what does (2,) mean?

code below

ker = GPy.kern.RBF(input_dim=2, variance=0.3, lengthscale=2, inv_l=True, ARD=True)
print(ker)
m = GPy.models.GPRegression(XYsmp, Zsmp, ker)
m.optimize('tnc', max_f_eval=1000)
print(ker)
-------------------------------------------------------------------------------------------------
rbf.             |  value  |  constraints  |  priors
  variance         |    0.3  |      +ve      |        
  inv_lengthscale  |   (2,)  |      +ve      |        
 rbf.             |              value  |  constraints  |  priors
  variance         |  26.35246144408414  |      +ve      |        
  inv_lengthscale  |               (2,)  |      +ve      |

**Comment by dtorre38** [comment]
The '(2,)' means that there are 2 lengthscales since your system is 2D this checks out. The simplest way to check the lengthscales would be:

print(m.kern.lengthscale)

**Comment by ktakihara2000** [comment]
@dtorre38 
Thank you for answering my question!
I can now check the lengthscales.

I have an additional question.
Have you heared of how to set the initial value of each lengthscales?

**Comment by dtorre38** [comment]
There are two ways that I am aware of:

1) When setting your kernel you can pass values to the lengthscale argument as follows:

`GPy.kern.RBF(input_dim=2, lengthscale=l, ARD=True)`

where l is your initial lengthscale.

2) You can also set the lengthscale as:

`m.kern.lengthscale = lengthscale`

where m is your model name.

**Comment by ktakihara2000** [comment]
@dtorre38 
Everything has been resolved.
Thank you very much for your kind attention!
